### ISSUE TITLE
Drop the vpn==0 and vpn==1 modes

### ISSUE THREAD

**Issue by respasa** [riscv/riscv-isa-manual#100]
I suggest we drop the vnp == 0 case altogether. We're building a vector machine, so not having a mask register is not acceptable :-). You have a paragraph explaining that when vnp == 0 the machine treats vp0 as "all 1s". Just drop that and say that vp0 must always be present. 

In fact, given the encoding we have, I think compiler and assembler people will hate us if we don't dictate that BOTH vp0 and vp1 must ALWAYS be implemented. I think this is the more sane option.

**Comment by kasanovic** [comment]
outdated.
