### ISSUE TITLE
No new PDF 'releases' generated since end of Jan

### ISSUE THREAD

**Issue by asb** [riscv/riscv-isa-manual#1016]
Prior to Jan 31st, it seems PDFs were generated very regularly (every commit?). But as of last now, the last release of a draft PDF is https://github.com/riscv/riscv-isa-manual/releases/tag/draft-20230131-c0b298a

Did something break with the automation?

**Comment by rpsene** [comment]
@aswaterman I was told you create the releases manually for the main branch.

**Comment by aswaterman** [comment]
@rpsene Nope.  We rely on github actions to do that, but as Alex said, it has been broken since January.

**Comment by rpsene** [comment]
@aswaterman let me raise a PR with a fix.

**Comment by rpsene** [comment]
@asb fix in place https://github.com/riscv/riscv-isa-manual/releases/tag/isa-449cd0c

**Comment by asb** [comment]
Thanks! Marking this issue closed as it appears to be be fixed.
