### ISSUE TITLE
Zfa with Z[h|f|d]inx

### ISSUE THREAD

**Issue by kito-cheng** [riscv/riscv-isa-manual#1020]
Does `Zfa` is compatible with `Z[h|f|d]inx`? If so, I would like to having some clarification on spec if possible.

**Comment by ptomsich** [comment]
@kito-cheng Per discussions with Andrew it is not compatible (and the spec is explicitly calling for Zfh,F,D, inclusive-or Q to be present.

**Comment by kito-cheng** [comment]
Yeah, that make sense, I missed this sentence before: "The Zfa extension depends on the F extension.".

Thanks :)

**Comment by jnk0le** [comment]
Zfa is redundant to `lui` in this scenario.
