### ISSUE TITLE
Zfa effect on Zfinx

### ISSUE THREAD

**Issue by christian-herber-nxp** [riscv/riscv-isa-manual#1033]
The current proposal of Zfa should affect the text in Zfinx, as it has to address additional instructions not being implemented. How will this be done in the process? Or will it even be done?

**Comment by aswaterman** [comment]
The Zfa text explicitly states that it requires the F extension.  Since F is incompatible with Zfinx, Zfa is incompatible with Zfinx.  Thus, no alterations to the Zfinx spec are necessary.

(In the future, a Zfa-like extension that's compatible with Zfinx could be specified.)
