### ISSUE TITLE
Add Multi-page version of HTML Docs?

### ISSUE THREAD

**Issue by Patronics** [riscv/riscv-isa-manual#1040]
It would be great if there was a multi-page version of the HTML, perhaps one page per chapter?

I'm trying to work on creating a [dash docset](https://kapeli.com/dash) for easy and searchable offline reference, and my[ initial attempt ](https://github.com/Patronics/RISC-V_ISA_Dash_Docs) seems to work, but the singular huge documentation file is too big and Dash hangs when jumping between sections. 

Using various tools as described [here](https://stackoverflow.com/questions/28161393/can-asciidoctor-render-a-separate-html-page-per-chapter), you can generate individual pages from the ASCIIDocs as an alternative layout to the singular monolithic HTML file.

**Comment by wmat** [comment]
This is on the list of future todos.  In the meantime, feel free to clone locally and use the [asciidoctor-multipage](https://github.com/owenh000/asciidoctor-multipage) extension to achieve what you're looking for.  Alternatively, if you wanted you could setup a local [Antora](https://antora.org/) based site.

I'm going to close this for now as it's already on the roadmap.

Thanks for the input.
