### ISSUE TITLE
MXR user mode

### ISSUE THREAD

**Issue by jrahmeh** [riscv/riscv-isa-manual#1045]
Should the MXR bit be supported in User privilege?  Is it useful in that privilege?

**Comment by aswaterman** [comment]
The ratified definition is that it affects how any load accesses virtual memory.  The normal use case is that S-mode enables it briefly then clears it, so it is not normally active while in U-mode, but by definition it can be in effect in U-mode.

**Comment by jrahmeh** [comment]
Thanks.  Closing.
