### ISSUE TITLE
Privileged spec 1.10: "MSIE" not explained

### ISSUE THREAD

**Issue by maikmerten** [riscv/riscv-isa-manual#105]
Figure 3.12 (page 29) of the Privileged Architecture 1.10 spec includes a field "MSIE". This is the only mention of "MSIE" in the complete document.

In chapter 4 "USIE" is defined, so a reader can infer that "MSIE" may stand for "Machine-level Software Interrupt Enable" (or something similar).

Perhaps related to #93?

**Comment by aswaterman** [comment]
There is a missing sentence: "The MSIE, SSIE, and USIE fields in the {\tt mie} CSR enable M-mode software interrupts, S-mode software interrupts, and U-mode software interrupts, respectively."  I will add it.
