### ISSUE TITLE
Code formatting in asciidoctor-pdf

### ISSUE THREAD

**Issue by dhower-qc** [riscv/riscv-isa-manual#1050]
The current font (Computer Modern) for code in the asciidoctor-pdf template is not a monospace font. As a result, code sequences do not line up nicely, e.g., the listing in Section 10.2:

![image](https://github.com/riscv/riscv-isa-manual/assets/134728312/e950667b-7767-4650-8067-e9e33f70a314)

The comments are supposed to be lined up, but aren't. This only applies to the PDF backend; the html backend formats code nicely.

Can we please switch the font?

**Comment by aswaterman** [comment]
Agreed. @wmat, can you fix this?

**Comment by wmat** [comment]
Fixed.  I set the default font for source code to the M+ 1mn monospaced font.  Comments now align properly.

[commit](https://github.com/riscv/riscv-isa-manual/commit/d122646f2cf8dad21f26af5c8f8a78e9b72807be)
