### ISSUE TITLE
typo in compressed ntl encoding description

### ISSUE THREAD

**Issue by jnk0le** [riscv/riscv-isa-manual#1053]
https://github.com/riscv/riscv-isa-manual/blob/main/src/zihintntl.adoc?plain=1#L93
" C.NTL.P1 is encoded as C.ADDi"

the rest of document uses "C.ADD" for ntl encodings

**Comment by aswaterman** [comment]
@wmat the report is correct, and this might be an adoc translation error. Can you remove the errant “i”?

**Comment by wmat** [comment]
Thanks for the report @jnk0le .
