### ISSUE TITLE
Incorrect constraints on HINT instructions

### ISSUE THREAD

**Issue by Maato** [riscv/riscv-isa-manual#1063]
This is regarding [the table](https://github.com/riscv/riscv-isa-manual/blob/9d49cc632417db08ba2fecf2e91b423656ce92a8/src/rv32.adoc?plain=1#L1016) in 2.9. HINT Instructions
Note that there is a [similar table](https://github.com/riscv/riscv-isa-manual/blob/9d49cc632417db08ba2fecf2e91b423656ce92a8/src/rv64.adoc?plain=1#L188) in section 7.4. HINT Instructions, which does not have these errors.

An excerpt from the current table for reference:
| Instruction | Constraints | Code Points | Purpose |
|--------|--------|--------|--------|
| ADD | rd=x0,rs1=x0 | 2^10-32 |  |
| ADD | rd=x0,rs1=x0,rs2=x2-x5 | 28 |  |
| ADD | rd=x0,rs1=x0,rs2=x2-x5 | 4 | (rs2=x2) NTL.P1<br /> (rs2=x3) NTL.PALL <br />(rs3=x4) NTL.S1 <br /> (rs2=x5) | 
| FENCE | rd=rs1=x0,fm=0,pred!=W,succ!=0 | 15 |  |

The issues:
- Row 1 should have rs1!=x0
- Row 2 should have rs2!=x2-x5
- Row 3 has one 'rs3' in the purpose column instead of rs2 (this made me chuckle)
- Row 3 is missing the NTL.ALL text
- Row 4 should have succ=0

**Comment by aswaterman** [comment]
@wmat these look like asciidoc transliteration errors; can you fix them?
