### ISSUE TITLE
When csr menvcfg.PBMTE=0,  whether Svpbmt extension is not available in S-mode but can be available in U-mode?

### ISSUE THREAD

**Issue by zhangjingru111** [riscv/riscv-isa-manual#1070]

**Comment by gfavor** [comment]
Svpbmt is either completely enabled or completely disabled by menvcfg.PBMTE.  When enabled, it affects address translation of all addresses - whether S-mode or U-mode addresses.

**Comment by zhangjingru111** [comment]
> 

"The PBMTE bit controls whether the Svpbmt extension is available for use in S-mode and G-stage
address translation (i.e., for page tables pointed to by satp or hgatp). When PBMTE=1, Svpbmt
is available for S-mode and G-stage address translation. When PBMTE=0, the implementation
behaves as though Svpbmt were not implemented."
That's what the spec says. It doesn't mention U mode. So, does PBMTE also affect U mode by default?

**Comment by gfavor** [comment]
Svpbmt affects address translation - which applies to virtual addresses in
both S-mode and U-mode.  And if Svpbmt is disabled, then that is true for
address translation in both modes as well.

Greg

Greg
