### ISSUE TITLE
Idea: Make `I` version 2.2 knowing even if unchanged from 2.1 (related to toolchain with `Zicntr` and `Zihpm`)

### ISSUE THREAD

**Issue by a4lg** [riscv/riscv-isa-manual#1082]
This issue arose from the fact that toolchains handled counters without any specific names as a part of `I` for a long time.
https://sourceware.org/pipermail/binutils/2023-August/128895.html

In my RFC PATCH to GNU Binutils (add support to `Zicntr` and `Zihpm`), I chose to check the ISA version to possibly switch the behavior of `Zicntr` and `Zihpm` (just looks like it happened on the unprivileged ISA version 20190608, which started requiring the `Zicsr` extension).  However, to switch implication of `Zicsr`, we used the version of the `I` extension because we had an extension name for CSR instructions when they are splitted from the `I` extension (version 2.1).  In that time, we did have "counters" (without extension names) but neither `Zicntr` nor `Zihpm`.  So, if the version of the `I` extension doesn't change, the toolchain will need some kind of additional workarounds.

I think advancing the version of the `I` extension is *not mandatory* (fortunately, required effort for additional workarounds will not be very large).

However, I would appreciate if you consider this as an option (to make the situation simpler).

**Comment by kasanovic** [comment]
We don't want to advance the RISC-V spec versions unless there is a substantive change in the RISC-V specs (which shouldn't happen after ratification).  In the case of a misinterpretation of the spec by the toolchain providers (as here), the toolchain can have its own flags to select between the different toolchain behaviors based on incorrect/correct reading of the spec.
