### ISSUE TITLE
Document behavior of access faults when translation hardware reads/writes page tables

### ISSUE THREAD

**Issue by jhauser-ucberkeley** [riscv/riscv-isa-manual#109]
I've searched the current document and I can't find a clear specification for the exceptions that may be raised when a memory access by the address translation hardware (to read/write a page table entry) fails due to memory protection or another cause, such as an address region that's read-only or contains no memory.  Although such a case shouldn't happen when operating system software is acting sanely, the hardware must be ready to handle it.

Given the entirety of the document, I think an informed reader can guess that this condition ought to raise a load access fault or store access fault exception for the instruction that triggered the failing address translation.  But even if you think that's "obvious", there's still the question of what value should be written to mtval or stval.  For access faults, the document states that mtval or stval is written with "the faulting virtual address", which in this case would presumably be the virtual address that the hardware was attempting to translate.  But, as this address has no direct connection to the physical address that failed (which is actually a PTE address), I fear some implementors may instead put the failing PTE address in mtval/stval.

At the very least, I think it would be wise to have a more explicit clarification of this corner case in the document.

**Comment by aswaterman** [comment]
In "Virtual Address Translation Process", we write: "If accessing pte violates a PMA or PMP check, raise an access exception corresponding to the original access type."  I think that addresses the cause register.  Can you propose new or different wording to convey what gets written to tval?  Indeed, the intent is that the virtual address the hardware was attempting to translate gets written to tval.
