### ISSUE TITLE
C.SWSP: Incorrect bit indices

### ISSUE THREAD

**Issue by danlehmann** [riscv/riscv-isa-manual#1092]
Page 100 describes the instruction format of C.SWSP, C.SDSP etc.

The bit indices above the gray bar are wrong: op has 2 bits, so rs2 should start at 2 (not 1). This is wrong in all fields, making funct3 one big too wide (it is only 3 bits, so its 13..15)

**Comment by wmat** [comment]
Thanks. Fix has been applied.
