### ISSUE TITLE
[asciidoc] pdf releases are 8x bigger than latex ones

### ISSUE THREAD

**Issue by jnk0le** [riscv/riscv-isa-manual#1124]
see: https://github.com/riscv/docs-spec-template/issues/9

same issue is scattered across other repos such as V, Zce etc.

**Comment by aswaterman** [comment]
Does the improvement proposed on the thread you mentioned apply here? If so, can you make a PR?

**Comment by jnk0le** [comment]
does it require CLAs?

**Comment by aswaterman** [comment]
It does not.

**Comment by jnk0le** [comment]
done, will try with rest of the offending repos

**Comment by aswaterman** [comment]
Cool, thanks for lending a hand.
