### ISSUE TITLE
Add LCOFI field to {m,s,vs}{ie,ip} CSRs

### ISSUE THREAD

**Issue by aswaterman** [riscv/riscv-isa-manual#1127]
And add a non-normative note explaining what the bit does, as a temporary measure until the Sscofpmf spec is integrated into the priv spec.

**Comment by ved-rivos** [comment]
If the AIA spec integration is not imminent, could we also introduce the interrupt numbers 35 and 43 defined by AIA spec as local interrupts for low-priority and high-priority RAS events as a temporary measure?

**Comment by aswaterman** [comment]
Can you raise that as a separate github issue, tag it with the priv 1.13 label, and solicit input from the usual subjects?

**Comment by ved-rivos** [comment]
Sorry to have mixed the subjects. Will do.
