### ISSUE TITLE
Zcmop and depending compressed extension

### ISSUE THREAD

**Issue by a4lg** [riscv/riscv-isa-manual#1132]
It theoretically requires existence of the 16-bit encoding space (and possibly the smallest compressed instruction subset, `Zca`).

However, just requiring `Zca` causes problems (recent Toolchain SIG discussion suggests separating `C` and its subset `Zca` as two "bases" and not implying `Zca` from `C`).

The most realistic solution (as of now) would be to write like:

> `Zcmop` requires either `C` or `Zca` extension.

and let the toolchain to handle the conflicts.  The toolchain will not be able to imply anything from `Zcmop` but able to check whether `Zcmop` and either `C` or `Zca` co-exists.

Note that, it means that we have to specify both

1. `zcmop` (or some extension that depends on `zcmop`) and
2. Base compressed extension (or its supersets)

in the architectural string like

*   `-march=rv64gc_zimop_zcmop` (`c` + `zcmop`) or
*   `-march=rv32e_zce_zcmop` (`zce`→`zca` + `zcmop`).

**Comment by aswaterman** [comment]
Not sure I agree.  We're converging elsewhere on M implying Zmmul https://github.com/riscv/riscv-isa-manual/pull/1121 -- I realize this is a pain for the toolchain devs, but the toolchain devs aren't the only constituency here, and in any case they can't unilaterally define this policy.  I'll leave this open until the M/Zmmul issue is decided; don't expect a decision until then.

**Comment by nick-knight** [comment]
I'm not familiar with Zcmop. Do its encodings or CSRs overlap with other extensions? If not, it may be sufficient to simply say that it relaxes the lower bound on ILEN to 16 (or whatever the C chapter says).

**Comment by aswaterman** [comment]
I also considered that approach, @nick-knight, and I do think that would suffice. But I’d rather force the issue re: Zca and C. If things go the way you’ve proposed re: Zmmul/M, then Zca/C will fall in line.

**Comment by aswaterman** [comment]
I moved the M->Zmmul scheme forward.  Let's assume the same will happen for C->Zca.  Then, I think this issue devolves to Zcmop->Zca.

**Comment by aswaterman** [comment]
@tariqkurd-repo following the chaos in #1121, do you agree that the Zca spec should be updated to indicate that C implies Zca?  If so, can you make it so?

**Comment by tariqkurd-repo** [comment]
That sounds ok to me, I'm out for the next week so I'll try and do it when I'm back.

**Comment by a4lg** [comment]
Since `C` now implies `Zca`, unless we need a good reason to depend directly on `C`, depending on `Zca` would be better.

> `Zcmop` requires the `Zca` extension.

**Comment by aswaterman** [comment]
@a4lg Indeed.
