### ISSUE TITLE
\unspecified latex command not copied into asciidoc

### ISSUE THREAD

**Issue by Timmmm** [riscv/riscv-isa-manual#1135]
For example in Section 3.4 of the privileged spec, the Latex version says:

    All other hart state is \unspecified.

The Asciidoc version says:

    All other hart state is .

Very profound. I didn't check other instances of `\unspecified`.

**Comment by wmat** [comment]
Thanks! I thought I had all of these cleaned up.  Looks like I missed one.  Fixed now.
