### ISSUE TITLE
Request for new GH release now Zfa is marked as ratified

### ISSUE THREAD

**Issue by asb** [riscv/riscv-isa-manual#1137]
It would be helpful if we could have a new GH release of the draft spec with generated PDFs now zfa is marked as ratified. This is handy to reference in the corresponding toolchain patches.

**Comment by wmat** [comment]
I've generated a new release, does this meet your needs? https://github.com/riscv/riscv-isa-manual/releases/tag/riscv-isa-release-056b6ff-2023-10-02

**Comment by asb** [comment]
Perfect, thanks!
