### ISSUE TITLE
Add a definition for hart

### ISSUE THREAD

**Issue by ilg-ul** [riscv/riscv-isa-manual#114]
Following the discussions in the [sw-dev](https://groups.google.com/a/groups.riscv.org/forum/?utm_medium=email&utm_source=footer#!msg/sw-dev/QKjUDjz_vKo/JjhJf8rxBgAJ) forum, could you please add a definition for _hart_, possibly with some explanations and history how this name was introduced?

Also a better definition for _core_ would help, possibly with an explicit differentiator between core and hart, since, for single hart cores, people tend to mix their names (including the SiFive manuals), increasing confusion.

I guess the definitions should target both simple readers, for a clean logical level understanding, and silicon vendors, with the technical requirements for a compliant implementation.

**Comment by kasanovic** [comment]
Added text to hopefully make execution environments and hart definitions clearer as part of push for ISA ratification.
