### ISSUE TITLE
Sample mvendorid has confusing bank field

### ISSUE THREAD

**Issue by yf13** [riscv/riscv-isa-manual#1151]
Section 3.1.2 of privleged manual says the `bank` field shall contain number of continouation codes. The example has 12 continuation codes, but the bank field is 6 in sample value `0x60a` , should the value be  `0xc0a` instead?  
If the `Bank` field takes value of JEDEC bank number minus 1, then it shall be `0xb0a` instead. 
The specification looks confusing though.

**Comment by allenjbaum** [comment]
Note that the bank field is not byte aligned, so (in hex) it is the bank
field is  bank..1. If Bank# were odd, the low bank bit would appear in the
upper bit of the last 2 hex digits.

**Comment by yf13** [comment]
thanks!
