### ISSUE TITLE
CSR tables in priv section 2.2 are rendered incorrectly

### ISSUE THREAD

**Issue by aswaterman** [riscv/riscv-isa-manual#1156]
See original vs. current.  The third column is wrapping.  All columns should have the same number of rows.
![Screenshot 2023-10-30 at 5 05 32 PM](https://github.com/riscv/riscv-isa-manual/assets/1031106/89ba0017-5c9e-48da-bec5-1231ee3da986)
![Screenshot 2023-10-30 at 5 05 39 PM](https://github.com/riscv/riscv-isa-manual/assets/1031106/5c1d9e9c-de93-46eb-8463-f872f9c3a6b1)

**Comment by wmat** [comment]
Fixed with https://github.com/riscv/riscv-isa-manual/commit/3c5943d67bc2c9f3ed1f85d730964e9845e942b5

**Comment by aswaterman** [comment]
Thanks!
