### ISSUE TITLE
user-mode software interrupt in mtvec section

### ISSUE THREAD

**Issue by yf13** [riscv/riscv-isa-manual#1158]
In Machine-Level ISA v1.12, the section describing Machine Trap Vector Base Address register (`mtvec`), there is a Note about user-mode software interrupt cause. But in the list at table 14 there is no such user-mode software interrupt. Is this right?

**Comment by aswaterman** [comment]
The note is out of date and should be deleted. The N extension was never brought to fruition.

**Comment by yf13** [comment]
Okay, will send a PR later.

**Comment by yf13** [comment]
@aswaterman please help to review PR #1159.

**Comment by aswaterman** [comment]
Thanks.
