### ISSUE TITLE
Pseudoinstruction table refers to "rs" and "rt", which aren't used elsewhere

### ISSUE THREAD

**Issue by asb** [riscv/riscv-isa-manual#116]
The pseudoinstruction tables 20.2 and 20.3 refer to "rs" and "rt", while "rs1" and "rs2" are used consistently throughout the rest of the document. Is this intentional?

**Comment by kasanovic** [comment]
This was intentional, as rs and rt represent register names that don't necessarily correspond to rs1 or rs2.
