### ISSUE TITLE
Clarification on SIP.SEIP read

### ISSUE THREAD

**Issue by jrahmeh** [riscv/riscv-isa-manual#1174]
When the SIP CSR is read with a CSR instruction, is the value of the SEIP bit the logical-or of the CSR bit and the interrupt signal from the interrupt controller?  Does the same process that applies to the SEIP bit in MIP applies to that bit in SIP?

**Comment by gfavor** [comment]
The SEIP bit is implemented as spec'ed in the mip.SEIP description of the Priv spec.  That specifies both the read and write behaviors.

And that one bit has two _aliases_: a read-write alias as mip.SEIP, and a read-only alias as sip.SEIP.

**Comment by jrahmeh** [comment]
Thank you. Closing.
