### ISSUE TITLE
Should implementation check whether D/A/U bits of non-leaf PTEs are zero?

### ISSUE THREAD

**Issue by jinyinghan324** [riscv/riscv-isa-manual#1187]
In "riscv privileged architects" 4.3.1, it is said that "For non-leaf PTEs, the D, A, and U bits are reserved for future standard use. Until their use is defined by a standard extension, they must be cleared by software for forward compatibility." 
Should implementation check whether D/A/U bits of non-leaf PTEs are zero and report page fault?

**Comment by ved-rivos** [comment]
Please see step 3 of the virtual address translation process in section 5.3.2 that specifies:
> If pte.v=0, or if pte.r=0 and pte.w=1, or if any bits or encodings that are reserved for future standard use are set within pte, stop and raise a page-fault exception corresponding to the original access type.

PS: Section number 4.3.1 is 5.3.1 in the latest manual.
