### ISSUE TITLE
Specify implementation requirements for WIRI and WPRI fields

### ISSUE THREAD

**Issue by jhauser-ucberkeley** [riscv/riscv-isa-manual#119]
For many register fields defined as WIRI and WPRI, the documents don't (as far as I know) explicitly say what is required of an implementation.  For forward compatibility, it should be made explicit that implementations must hardwire those bits to zeros.

**Comment by aswaterman** [comment]
Can you offer your opinion on https://github.com/riscv/riscv-isa-manual/pull/121?

**Comment by jhauser-ucberkeley** [comment]
Good enough for me.

**Comment by aswaterman** [comment]
Thanks.  Closed by #121.
