### ISSUE TITLE
For misaligned store, is it allowed that another hart may observe part of data updated? 

### ISSUE THREAD

**Issue by jinyinghan324** [riscv/riscv-isa-manual#1194]
For instance, if a misaligned store cross two cacheline, a load of the same address from another hart may only observe one cacheline is updated, the other is not. It is a bug or it is allowed?

**Comment by aswaterman** [comment]
Yes, this is the implication of the spec's statement that misaligned loads and stores might not execute atomically.  The non-atomicity could manifest in another hart observing only part of a misaligned store being performed.

**Comment by pdonahue-ventana** [comment]
Every operation must be atomic:
> A memory operation can be either a
load operation, a store operation, or both simultaneously. All memory operations are single-copy
atomic: they can never be observed in a partially complete state.

But your case can involve multiple operations:
> A misaligned load or store instruction may be decomposed into a set of component memory
operations of any granularity.

(So I agree with Andrew who just posted.)
