### ISSUE TITLE
Relationship between RNMI and UNMI in Smrnmi

### ISSUE THREAD

**Issue by hwliu-tommy** [riscv/riscv-isa-manual#1211]
Hi, I'm confusing about the relationship between UNMI and RNMI in Smrnmi extension.

The spec says "The Smrnmi extension adds support for resumable non-maskable interrupts (RNMIs) to RISC-V."
I've got 2 different interpretations, but I'm not sure which one is correct. 

1. Smrnmi makes the NMI resumable. So with Smrnmi support all NMI will be RNMI; without Smrnmi, NMI is unresumable, so it'll be UNMI.   
-> This Implies that RNMI and UNMI won't be support at the same time. And for CPU with Smrnmi support, interrupt source pin of NMI should be `rnmi` (defined in RNMI).  

2. Smrnmi adds a resumable subset (RNMI) to NMI. NMI triggered by the input `rnmi` will be RNMI, and the other is UNMI, which is triggered by `nmi` and it is unresumable.
-> This implies that RNMI and UNMI can be supported at the same time. and the CPU will have 2 interrupt source pins, `rnmi` and `nmi`.

Many thanks

**Comment by gfavor** [comment]
On Tue, Jan 30, 2024 at 7:52 AM Hao-Wei Liu ***@***.***>
wrote:

> Hi, I'm confusing about the relationship between UNMI and RNMI in Smrnmi
> extension.
>
> The spec says "The Smrnmi extension adds support for resumable
> non-maskable interrupts (RNMIs) to RISC-V."
> I've got 2 different interpretations, but I'm not sure which one is
> correct.
>
>    1.
>
>    Smrnmi makes the NMI resumable. So with Smrnmi support all NMI will be
>    RNMI; without Smrnmi, NMI is unresumable, so it'll be UNMI.
>    -> This Implies that RNMI and UNMI won't be support at the same time.
>    And for CPU with Smrnmi support, interrupt source pin of NMI should be
>    rnmi (defined in RNMI).
>
> I don't say this definitively, but #1 is the intention.  Either NMIs are
handled the old unresumable way or the new resumable way.  There is no need
to rename an NMI pin, although an implementation is free to name its "NMI"
signal however it likes.  The arch spec simply refers to "rnmi interrupt
signals" as an architectural abstraction.  Also note that the spec allows
for multiple signals.  But ultimately all that matters wrt Smrnmi is that
some sort of signaling to a hart conceptually raises a request to take a
nonmaskable interrupt.

Now having said all that, I think (?) a compliant implementation can choose
to process only some non-maskable interrupt sources via Smrnmi.  But that
requires software to recognize this bifurcation and the fact that not all
NMIs are resumable despite the Smrnmi extension being supported.  But
another way, can an implementation claim to implement the Smrnmi extension
yet not support resumability for all NMIs.  If, for example, there
eventually is a Machine-level ISA profile spec and it spec's support for
Smrnmi, I would think the implicit expectation would be that all NMI
sources fall under the Smrnmi support.

Greg
