### ISSUE TITLE
Delegating SSIP and VSSIP to VS mode

### ISSUE THREAD

**Issue by jrahmeh** [riscv/riscv-isa-manual#1214]
Can SSIP (bit 1 of MIP) and VSSIP (bit 2 of MIP) be both delegated to  VS mode using mideleg and hideleg? We would set bit 1 in middleg (bit 2 is always set when hypervisor extension is enabled), and we would set bits 1 and 2 in hideleg.

If both SSIP and VSSIP can be delegated to VS,  do bit 1 and 2 in the VSIE CSR become writeable or just bit 1?

**Comment by pdonahue-ventana** [comment]
> we would set bits 1 and 2 in hideleg

but you can't set bit 1 in hideleg:

> Among bits 15:0 of hideleg ... bits 12, 9, 5, and 1 (corresponding to the standard S-level interrupts) are read-only zeros.

So the answer is no.

**Comment by jrahmeh** [comment]
thank you
