### ISSUE TITLE
Zimop/Zcmop - interaction with E extension?

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-isa-manual#1220]
This is a review feedback comment for the Zimop/Zcmop specification, version 0.1.

If this extension is implemented in combination with the E extension, what is the behavior when `x[rd]` specifies a register in the range 16-31, or if either `x[rs1]` or `x[rs2]` specify a register in this range?

Thanks.

**Comment by gfavor** [comment]
See the RVE spec - its says "All encodings specifying the other registers x16-x31 are reserved."  By default this applies to all extensions.

**Comment by JamesKenneyImperas** [comment]
Ok, thanks.
