### ISSUE TITLE
[Svvptc extension] SRET/MRET questions about Svvptc

### ISSUE THREAD

**Issue by terranfund** [riscv/riscv-isa-manual#1244]
1. Does MRET also guarantee the page visible with Valid bit of PTEs from 0 to 1 like statement SRET in 
https://github.com/riscv/riscv-svvptc/blob/main/svvptc.adoc?
2. If question 1 is true, does it mean SRET/MRET has the overhead of gauranteeing previous stores visible to the current hart are ordered before subsequent instructions executed by the same hart, like FENCE?

**Comment by aswaterman** [comment]
The question should be moved over to that spec (but I believe it has been modified in such a way that the answer is “no”).
