### ISSUE TITLE
mie.MEIE missing in figure 16 in the privileged specification

### ISSUE THREAD

**Issue by tzwaenn** [riscv/riscv-isa-manual#1261]
Looking for mie.MEIE in figure 16, we see that it is missing, screwing up the layout and adding to a trailing "2" for the last 2 bits.
![MEIE](https://github.com/riscv/riscv-isa-manual/assets/45827187/8399181e-35df-4e70-b2ed-7627e2d3b94a)

**Comment by tzwaenn** [comment]
The LCOFI bits are a new addition, so they should stay in IMHO.

**Comment by wmat** [comment]
How does this look?

![Screenshot from 2024-03-15 10-13-35](https://github.com/riscv/riscv-isa-manual/assets/57188/5b562177-dbde-4612-a361-901d06429299)

**Comment by tzwaenn** [comment]
13 is LCOFIE, 11 MEIE (same as in fig 15 mip just with trailing p instead of e)

**Comment by wmat** [comment]
Am I missing a MEIE bit in there?  Fig 15 has a MEIP at bit 11.

**Comment by wmat** [comment]
NVM, I see that's what you said.

**Comment by wmat** [comment]
How's this now?
![Screenshot from 2024-03-15 10-27-38](https://github.com/riscv/riscv-isa-manual/assets/57188/cc43ee3b-4470-456e-aa9a-78b797f868e8)

**Comment by wmat** [comment]
Fix pushed.

**Comment by aswaterman** [comment]
Thanks!
