### ISSUE TITLE
when hlvx happened guest page fault, what value should mtinst  record

### ISSUE THREAD

**Issue by zhangjingru111** [riscv/riscv-isa-manual#1286]

**Comment by zhangjingru111** [comment]
In spec, hlv and hlvx is transformed with rs2 field, but hlvx doesn't have rs2. Should rs2 fields write 0 or 0x00011 in mtinst when hlvx instrution happened guest fault?
![Uploading Snipaste_2024-03-25_14-15-59.png…]()

**Comment by zhangjingru111** [comment]
![Snipaste_2024-03-25_14-15-59](https://github.com/riscv/riscv-isa-manual/assets/139855798/eb52651d-6c47-42b7-b4ca-7cfa7138f3c1)

**Comment by jrahmeh** [comment]
I believe for hlvx.hu/hlvx.wu, the rs2 field must be preserved since it is necessary for the correct decoding of those instruction. So in the transformed instruction corresponding to halve.hu/hlvx.wu, the rs2 field should be binary 00011.

**Comment by aswaterman** [comment]
Yeah, as the caption says, "all fields are the same as the trapping instruction" except [...], meaning that bits 24:20 are preserved, even though they don't represent rs2.

**Comment by zhangjingru111** [comment]
Ok, thank you very much:)
