### ISSUE TITLE
Fix duplication of zbkb, zbkc, zbkx.

### ISSUE THREAD

**Issue by wmat** [riscv/riscv-isa-manual#1298]
With the recent integration of numerous ratified specs, some content is duplicated. In particular, the zbkb, zbkc, znc zbkx extensions and the applicable instructions are defined in the Bitmanip chapter as well as the Crypto Scalar chapter.

Should this be the case?  If not, where should the content live?

**Comment by aamartin0000** [comment]
Perhaps it would be sufficient to augment the table in unpriv ch28.4 with the zbk* extensions.

**Comment by wmat** [comment]
> Perhaps it would be sufficient to augment the table in unpriv ch28.4 with the zbk* extensions.

Augment in what way?  Are you suggesting just referencing the Zbk* definitions in ch33.3?

**Comment by aamartin0000** [comment]
The table in Ch28.4 should have the unique instructions from Zbk* added, and then columns added for Zbkb/Zbkc/Zbkx.  Overlapping instructions would have checkmarks in two columns, for example clmul would have checkmarks in both  Zbc and Zbkc.

The Zbk* definitions in Ch33.3 are redundant with the definitions in Ch28.4.  One of those places should be changed to refer to the other.
