### ISSUE TITLE
Inquiry regarding the conditions for LR/SC success.

### ISSUE THREAD

**Issue by Codemaker-1** [riscv/riscv-isa-manual#1305]
Hi!

Asking if an SC should succeed when there are other AMO or store operations between LR and SC (within the same hart, not from other harts), and these operations target the same address reserved by LR?

Thank you!

**Comment by aswaterman** [comment]
The SC is allowed to succeed in this case, but it is by no means guaranteed to succeed (even if the address is the same).  Implementations are allowed, but not required, to unconditionally fail the SC if there are any memory accesses from the same hart in between the LR and SC.
