### ISSUE TITLE
Is OP-P the official name of major opcode 0b1110111?

### ISSUE THREAD

**Issue by topperc** [riscv/riscv-isa-manual#1310]
The Zvk* extensions call it OP-P in their encoding tables. The opcode table in the `RV32/64G Instruction Set Listings` calls it "reserved".

CC @aswaterman

**Comment by aswaterman** [comment]
For context, the current P-extension proposal moves those instructions elsewhere, but OP-P is used for Zvk* etc., so another name might be more appropriate.

**Comment by aswaterman** [comment]
@topperc The ARC wanted to know whether renaming the major opcode was a headache for toolchains.  If it's not onerous to change, we would like to rename it to OP-VE ("Vector Extensions") to more accurately reflect its current use and likely future use.

**Comment by topperc** [comment]
> @topperc The ARC wanted to know whether renaming the major opcode was a headache for toolchains. If it's not onerous to change, we would like to rename it to OP-VE ("Vector Extensions") to more accurately reflect its current use and likely future use.

The only place I can think the name might be exposed to users by the toolchain is in the `.insn` handling. It doesn't look like binutils documented or implemented a name https://sourceware.org/binutils/docs/as/RISC_002dV_002dFormats.html. I think LLVM did expose it as OP_P. LLVM doesn't have its own documentation for .insn so if someone figured that out they had to look at the source code. So the risk is low.

Within the toolchain source code it should be a quick search and replace.

I think we should proceed with renaming.

**Comment by aswaterman** [comment]
Sounds reasonable to me, especially if we change it promptly.
