### ISSUE TITLE
[Sstc] Are writes to read-only henvcfg.STCE ignored when menvcfg.STCE=0?

### ISSUE THREAD

**Issue by YenHaoChen** [riscv/riscv-isa-manual#1312]
Hello,

I am curious whether writes to the read-only-zero henvcfg.STCE are ignored when menvcfg.STCE=0.

The preliminary isa spec says, "writes to read-only bits (of a RW CSR) are ignored." Does the rule apply to the read-only henvcfg.STCE when menvcfg.STCE=0?

![image](https://github.com/riscv/riscv-isa-manual/assets/39526191/c8e26da8-40e7-4edf-a9e4-2e9eeb656f14)

@jscheid-ventana

**Comment by gfavor** [comment]
The sstc spec says "When STCE in menvcfg is zero, ..., STCE in henvcfg is read-only zero."  So standard read-only-zero behavior applies, i.e. this bit is not an exception to the general rule (since there is no explicit specifiation of different behavior).

**Comment by YenHaoChen** [comment]
Thank you. Thus, when mevncfg.STCE=0, henvcfg.STCE is read-only zero, and writes to the read-only-zero henvcfg.STCE are ignored.

**Comment by viktoryou** [comment]
In a previous issue: https://github.com/riscv-software-src/riscv-isa-sim/issues/1497, we came to the conclusion that in such situation, from the Spec, the bit of henvcfg(pbmte, stce, adue) doesn't require a determinism. Since the spike finally changes into ignoring the write, should this issue be regarded as a bug or just a preference for implementation? If there is the bug, why the explanation in section 2.4 of the Privileged Spec doesn't work here?

**Comment by YenHaoChen** [comment]
Both statements apply to this case, although software may not easily observe the violation.

+ (Section 2.1) ... writes to read-only bits (of a RW CSR) are ignored.
+ (Section 2.4) ... change from previously read-only to now writable, that field immediately gets an unspecified but legal value ...

The statements require an implementation to ignore writes to read-only bits, but they allow an unspecified legal value in the bits when they change from read-only to writable. The requirement implies no side effect on writing read-only bits, and the allowing clarifies that changing writability may also change the value.

**Comment by rbuchner-aril** [comment]
Do you know where in the spec I can find this: `The spec requires the value function to be independent of the writes when the bits are read-only.`?

**Comment by YenHaoChen** [comment]
The statements are the rewordings of:
+ ```(Section 2.1) ... writes to read-only bits (of a RW CSR) are ignored.```
+ ```(Section 2.4) ... change from previously read-only to now writable, that field immediately gets an unspecified but legal value ...```

Ignoring writes implies no side effects. In other words, the ignored writes do not contribute to the value by any means. Thus, the value function is independent of the ignored writes.

**Comment by rbuchner-aril** [comment]
Thank you for clarifying that for me!
