### ISSUE TITLE
What is the behavior if a CMO operation's effective address points to the middle of a cache block?

### ISSUE THREAD

**Issue by rbohn** [riscv/riscv-isa-manual#1325]
In describing the operation of the various CMO operations, the spec uses the phrase "the cache block whose effective address **is** the base address specified in rs1". Some are reading the first part of that to imply that the rs1 base address must be aligned to the cache block size. While likely sensible for software to do that anyway, the question is what should the hardware behavior be if rs1 were to point to the middle of the cache block? 

The spec explicitly rules out address misalignment exceptions so I assume that is not the intent. I think we are left with either:

1. The instruction acts as normal on the cache block that **contains** the effective address contained in rs1?
2. The behavior is unspecified.

Which is the intent?

**Comment by gfavor** [comment]
Spec has been updated.
