### ISSUE TITLE
Ambiguous sentence in 4.1.10 of supervisor ISA

### ISSUE THREAD

**Issue by lorddoskias** [riscv/riscv-isa-manual#133]
The first sentence of the second paragraph of the supervisor ISA states: 

> The Interrupt bit in the scause register is set if the contains a code identifying the last exception.

At a minimum a word or a phrase is missing after the 'if' and the sentence looks unfinished. Secondly I think the text could be made more explicit to state that the interrupt bit is used to distinguish between an exception and an interrupt as per the following comment in entry.S in the linux port: 

```
/*                                                                          
     * MSB of cause differentiates between                                      
     * interrupts and exceptions                                                
     */                                                                         
    bge s4, zero, 1f  
```

s4 contains the scause register.

**Comment by aswaterman** [comment]
Thanks; this error was fixed last year in commit b43657ca5a4266c39eb99b186a5af5449e913eb1
