### ISSUE TITLE
Some state-enable text should be normative.

### ISSUE THREAD

**Issue by jhauser-us** [riscv/riscv-isa-manual#1340]
In the chapter on extensions Smstateen/Ssstateen, the following text is incorrectly formatted as commentary:

> The FCSR bit controls access to fcsr .... regardless of whether they really do.

and:

> The AIA bit in hstateen0 controls access to all state introduced by the Ssaia extension and is not controlled by either the CSRIND or the IMSIC bits of hstateen0.

These statements should be normative.  (Else, there is no normative specification for bits FCSR and AIA.)

**Comment by aswaterman** [comment]
@ved-rivos since you integrated that spec, can you address this one?

**Comment by ved-rivos** [comment]
I didn't integrate this chapter but I can address this one. Should I fix up other sections in the chapter as well as part of this -  such as renaming the "Proposal" section and removing duplicated  description of mstateen ?

**Comment by aswaterman** [comment]
Oh, my mistake.  Yeah, if you don't mind doing that, it would be much appreciated.

**Comment by ved-rivos** [comment]
Updates in PR #1342

**Comment by kersten1** [comment]
These look fixed as well.
