### ISSUE TITLE
Name of CSR jvt is not capitalized

### ISSUE THREAD

**Issue by jhauser-us** [riscv/riscv-isa-manual#1343]
The ISA documents are showing the name of CSR `jvt`, added by extension Zcmt, as capitalized (`JVT`).  No standard CSR names are capitalized.

This appears not only in the Zc* extensions chapter of the Unprivileged ISA Spec, but also in the Smstateen/Ssstateen extensions chapter of the Priv spec.

**Comment by kersten1** [comment]
Closing as this appears fixed.
