### ISSUE TITLE
Correct user level ISA extension naming convention

### ISSUE THREAD

**Issue by atishp04** [riscv/riscv-isa-manual#1348]
As discussed on this thread:
https://lists.riscv.org/g/tech-privileged/message/1911

The combined priv spec says
"CSR address space is reserved for a possible future "Sucsrind" extension that extends
indirect CSR access to user mode."

As per @gfavor , Sucsrind is correct naming as it is a user level ISA extension instead of Unpriv extension.

"The rough distinction being that this is User level specific functionality, whereas Unpriv extensions (e.g. Zi* instructions) can be used at all privilege levels."

This issue is just to confirm that understanding and filed as requested on the mailing list. @wmat

**Comment by aswaterman** [comment]
What Greg wrote sounds right to me.  So I think the spec says nothing misleading and we can close this, right?

**Comment by atishp04** [comment]
Yes. Closing the issue.
