### ISSUE TITLE
Ordering of names in titles

### ISSUE THREAD

**Issue by kersten1** [riscv/riscv-isa-manual#1352]
Noticed this as I was looking through the TOC. Some register names are like this: 

"Supervisor Status Register (sstatus) 

and then others look like this: 

"Supervisor Trap Value (stval) Register"

I like the second better but not enough that I'll argue if everyone else likes the first.  Let me know which is preferred and I can fix up titles.

**Comment by kasanovic** [comment]
I'll vote for the second version also.

**Comment by aswaterman** [comment]
Likewise.

**Comment by gfavor** [comment]
Ditto.

Greg

**Comment by kersten1** [comment]
Most of these are done. Have to catch the errant ones as we go.
