### ISSUE TITLE
satp.MODE WARL is unprobable as specified

### ISSUE THREAD

**Issue by sorear** [riscv/riscv-isa-manual#137]
WARL fields only solve the probing problem if writing to the CSR has no other side effects, but since writing to satp causes an immediate control transfer, a supervisor cannot probe for Sv48 support by writing a Sv48 page table base to satp.

An implementation which does not support Sv48 but does support other modes defined in the future could switch to one of them on seeing an invalid MODE, and a supervisor cannot be expected to support arbitrary modes defined in the future.

satp could be made probable by making it WLRL or by specifying more specific behavior for unsupported values (like mapping all of them to Sbare), but neither approach maintains compatibility with priv-1.10.  The issue may be moot if both Device Tree and ACPI include MMU features in their configuration tables.

**Comment by aswaterman** [comment]
Actually, we already wrote this into the spec... ```Implementations are not required to support all MODE settings, and if {\tt satp} is written with an unsupported MODE, the entire write has no effect; no fields in {\tt satp} are modified.```

**Comment by sorear** [comment]
I see that now.  Sorry!
