### ISSUE TITLE
hyphenated exception names?

### ISSUE THREAD

**Issue by davidharrishmc** [riscv/riscv-isa-manual#1370]
Are exception names now hyphenated?  The machine section seems inconsistent.
For example, page-fault exceptions is hyphenated in 8 places in the text.  However "page fault" is not hyphenated in 5 places in Tables 6 and 7.

https://github.com/riscv/riscv-isa-manual/blob/main/src/machine.adoc

**Comment by aswaterman** [comment]
They should be hyphenated when used as a compound adjective (“page-fault exception”) but not when used as a noun (“page fault”). I do think this was changed recently, so there may be some inconsistencies.

**Comment by kersten1** [comment]
Found a couple and fixed them. Also there is "guest-page fault", which seems fine to me as it is consistent.

**Comment by kersten1** [comment]
All fixed so closing
