### ISSUE TITLE
Chapter 7.1  issues

### ISSUE THREAD

**Issue by bcstrongx** [riscv/riscv-isa-manual#1372]
The use of "currently" here is probably not appropriate:
`Currently, these counters are not filtered by privilege mode, and thus they continue to increment while traps (e.g., page faults or interrupts) to more privileged code are handled. `

I would replace "Currently" with "By default".

I would also replace "This proposal" below with "Smcntrpmf".
`This proposal remedies these issues by introducing privilege mode filtering for the cycle and instret counters.`

**Comment by aswaterman** [comment]
Agreed.  Can you make a PR?

**Comment by bcstrongx** [comment]
sure
