### ISSUE TITLE
Does misaligned exception in nottaken branches cause an exception?

### ISSUE THREAD

**Issue by omerguzelelectronicguy** [riscv/riscv-isa-manual#1379]
I couldn't understand the misaligned exception when the branch is not taken and the target has a misaligned address. Is there any explanation in the spec? If not I think it should be added to the spec.

**Comment by stnolting** [comment]
This is from an older release of the spec:

![grafik](https://github.com/riscv/riscv-isa-manual/assets/22944758/c879c2c5-a389-49c4-a77e-28ce31875b97)

So, no, there will be no exception in that case.

**Comment by omerguzelelectronicguy** [comment]
Thank you. I think it should be in the latest version of the spec too.

**Comment by aswaterman** [comment]
> it should be in the latest version of the spec

It is: https://github.com/riscv/riscv-isa-manual/blob/87edab70ddd2fedc6d01603a65f393163025633f/src/rv32.adoc#L648-L653
