### ISSUE TITLE
privileged isa spec. table 3 read-only csr's

### ISSUE THREAD

**Issue by farukyld** [riscv/riscv-isa-manual#1421]
are those ones correct in the `Table 3` in the document `Volume 2, Privileged Specification version 20240411`?
![image](https://github.com/riscv/riscv-isa-manual/assets/120921965/c55c0140-5cd8-4eff-a1b3-cdcc2f053d39)
![image](https://github.com/riscv/riscv-isa-manual/assets/120921965/67af64c9-dc40-48d2-80c3-a13dcf1b9247)

**Comment by allenjbaum** [comment]
Is there some reason you believe that the spec has a bug in that table?

**Comment by farukyld** [comment]
here:

in `Table 6`
![image](https://github.com/riscv/riscv-isa-manual/assets/120921965/aa4e80b0-f262-43d6-9883-3f115e041a13)

in `Table 7`
![image](https://github.com/riscv/riscv-isa-manual/assets/120921965/dee3ccfe-851e-4489-9770-67cebd9041e4)

**Comment by farukyld** [comment]
and also in the previous versions of privileged spec. (I have downloaded 20211203) those ranges were specified as read-only or custom read-only.

in this document: `The RISC-V Instruction Set Manual Volume II: Privileged Architecture Document Version 20211203` in `Table 2.1` 

![image](https://github.com/riscv/riscv-isa-manual/assets/120921965/6fcc2bd7-6022-4e46-93fc-96ac6ca38694)

**Comment by aswaterman** [comment]
This is a transcription error (cc @wmat).  I'll fix it.
