### ISSUE TITLE
What will happen if a hart executes `sinval.vma` with no fence before `sfence.w.inval`

### ISSUE THREAD

**Issue by huxuan0307** [riscv/riscv-isa-manual#1423]
Is some mechinism needed to handle this software mistake? If the implementation do no fence operation when excuting `sinval.vma`, is it necessary for implementation to check if there is an opening `sfence.w.inval` before `sinval.vma`.

**Comment by gfavor** [comment]
In short, No and No.  It is software's responsibility to use these instructions appropriately, and (for that matter) it is its choice to use them in unexpected ways.  The architectural intent is to provide these instructiosn as the tools for software to do what it wants.  There is no expectation for hardware to catch and/or defend against what it might (correctly or incorrectly) consider to be a software bug.

**Comment by huxuan0307** [comment]
Ok, thanks
