### ISSUE TITLE
Svadu chapter in Privileged arch spec is missing details

### ISSUE THREAD

**Issue by kdockser** [riscv/riscv-isa-manual#1426]
When the ratified Svadu specification was merged into the privileged specification, a lot of the normative text was lost.

As an important example, the ratified document states
`Svadu extension requires the page tables to be located in memory with hardware page-table write access and RsrvEventual PMA`.

This requirement did not make it into supervisor.adoc or any other files that make up the Privileged Architecture.

Was this intended?

**Comment by aswaterman** [comment]
The text isn’t missing; it is moved. The Svadu chapter has mostly been integrated into the mainline Supervisor chapter so that only ADUE needs to be defined within the Svadu chapter. If you search the Supervisor chapter for the RsrvEventual, you’ll find what you’re looking for.
