### ISSUE TITLE
Update generated filenames to be more desciptive.

### ISSUE THREAD

**Issue by wmat** [riscv/riscv-isa-manual#1437]
To more desciptively name the generated filenames, updating to be:
riscv-unprivileged and riscv-privileged.

**Comment by aswaterman** [comment]
I'm mucking around in the Makefile now anyway, so I'll handle this one.

**Comment by wmat** [comment]
Didn’t I make a PR today for this? I know there’s a 1536- branch.

Bill Traynor
Documentation Build and Release Engineer
RISC-V International

Join us in Munich, Germany at RISC-V Summit Europe
<https://riscv-europe.org/summit/2024/> from 24-28 June. Be a part of the
new wave of European computing innovation!

**Comment by aswaterman** [comment]
I must have missed it; I only saw this unlinked issue. Sorry about that.
