### ISSUE TITLE
use docs-resources as submodule to pull in shared resources (pdf theme, fonts, etc)

### ISSUE THREAD

**Issue by kbroch-rivosinc** [riscv/riscv-isa-manual#1448]
relates to:

* https://github.com/riscv-admin/docs-sig/issues/48
* https://github.com/riscv-non-isa/riscv-iommu/pull/342#issuecomment-2150847986

**Comment by wmat** [comment]
Recolved by https://github.com/riscv/riscv-isa-manual/pull/1449
