### ISSUE TITLE
Remove note on performance counters interrupt on overflow not supported

### ISSUE THREAD

**Issue by dgptha** [riscv/riscv-isa-manual#1450]
The specification states that the performance counters don't support interrupt on overflow (see link below), but the same specification introduces the "Sscofpmf"  extension which seems to propose such feature. Thus the note should be removed, doesn't it?

https://github.com/riscv/riscv-isa-manual/blob/6ee57d8997021aaa8025e208164763fe12e03c19/src/machine.adoc?plain=1#L1439C1-L1445C5

**Comment by aswaterman** [comment]
Indeed.
