### ISSUE TITLE
funct7 values of SRA,SUBW,SRAW appear to be incorrect in unpriv section 4.2.2 of version 20240411.

### ISSUE THREAD

**Issue by puyogo-suzuki** [riscv/riscv-isa-manual#1452]
Hi,
I think that the funct7 values in unpriv section 4.2.2 of version 20240411 are incorrect.  
In the V20191213, funct7 values are 7-bits (in section 5.2).  
The values are 0000000 or 0100000.  
![image](https://github.com/riscv/riscv-isa-manual/assets/20222016/e8481803-ce41-414f-b823-ec587d5b9e11)

However, in the version 20240411, funct7 values have only 6-bits; the least significant bits seem to be missing.  
The values are 000000 or 010000.   
![image](https://github.com/riscv/riscv-isa-manual/assets/20222016/826dd100-4ab2-468e-b1e2-24c94b03679b)

Is this correct?  

The relevant file is:  
https://github.com/riscv/riscv-isa-manual/blob/353e88f8d5c629be5a42ada8618fcfa9acb5d287/src/images/wavedrom/rv64i_int-reg-reg.adoc?plain=1#L13

**Comment by aswaterman** [comment]
@wmat this is indeed a bug; these funct7 fields should all have another 0 appended on the right.

**Comment by puyogo-suzuki** [comment]
Thank you!
