### ISSUE TITLE
Helping the reader with complex mangled immediate fields

### ISSUE THREAD

**Issue by gameboo** [riscv/riscv-isa-manual#146]
In several places in the document, when a value is derived from an immediate field, it appears just below the instruction along with the corresponding bit-slice (for example, `offset[11:0]` below `imm[11:0]` in JALR's definition).
Sometimes, the immediate bits are somewhat mangled, but the value is kept as one bit-slice (for example, `offset[20:1]` below `imm[20], imm[10:1], imm[11], imm[19:12]` in JAL's definition).
Sometimes, the mangling appears in the value being defined (for example, `offset[4:2|7:6]` below `imm` in C.LWSP's definition).
Even though it is a bit awkward to follow, it mostly makes sense. I do believe however that it would help a lot to disambiguate how the values are constructed a bit in the text accompanying the instruction's definition, especially when reaching cases such as C.J or C.JAL (where `offset[11|4|9:8|10|6|7|3:1|5]` appears below `imm`) which are a bit hard to wrap your head around. Something like `offset = imm[10|6|8:7|4|5|9|0|3:1]` in the text (or `offset = imm[11|7|9:8|5|6|10|1|4:2]` if we consider imm to be 12 bits?) would greatly help: even though I know  this is what `offset` is meant to be _(at least I think that's what it is meant to be)_, it is always tempting to read it as `offset = imm[10|3|8:7|9|5|6|2:0|4]`).

Would that be a useful/acceptable addition to the text?

Thanks.

**Comment by aswaterman** [comment]
I actually think the additional clutter could make it more confusing.  Yes, it's messy and easy to screw up when typing it into a program.  But it's also intuitive enough, as you point out.
