### ISSUE TITLE
Allow FS to be imprecise

### ISSUE THREAD

**Issue by palmer-dabbelt** [riscv/riscv-isa-manual#147]
I can't find anything in the spec that explicitly allows FS to be imprecise.  This table lists the possible FS state transitions:

https://github.com/riscv/riscv-isa-manual/blob/5f8294b56e0447775c444c5c641713d8e67c4b88/src/machine.tex#L824

There's some vague "When the status is Dirty, the corresponding state has potentially been modified since the last context save.", but the state transition table makes it appear that it'l not legal to set the dirty state without executing an instruction.

**Comment by aswaterman** [comment]
@palmer-dabbelt i still agree this is a problem, but i'm going to punt it back to you to propose a PR.
