### ISSUE TITLE
Reasoning behind extended vshape encoding in V draft as of 0472bcd?

### ISSUE THREAD

**Issue by eternaleye** [riscv/riscv-isa-manual#149]
In reading the V draft, table 17.2 (the extended `vshape` encoding) confused me somewhat. There are two main questions I have:

- First, `01100` seems to be entirely absent from the table, not even marked as reserved.
- Second, I'm having trouble finding a consistent rule or pattern to the encoding assignments

I'm curious as to why the encoding isn't along the lines of `rnmls`, such that:
- The `n`, `m`, and `l` bits denote that the corresponding `v[lmn]` register is used as a dimension
   - If one is set, then it's either a 1-dimensional vector or (if `s` is set) a square matrix
   - If two are set, it's a rectangular matrix with dimensions in lexicographical order (`vl × vm`, `vl × vn`, `vm × vn`), and `s` being set swaps the dimensions
- All three being set is reserved
- `r` is reserved

This would yield the following table:

`vshape`|Shape
---------|----------
`00000`|Scalar
`00001`|Reserved
`00010`|1-D vector `vl`
`00011`|2-D matrix `vl × vl`
`00100`|1-D vector `vm`
`00101`|2-D matrix `vm × vm`
`00110`|2-D matrix `vl × vm`
`00111`|2-D matrix `vm × vl`
`01000`|1-D vector `vn`
`01001`|2-D matrix `vn × vn`
`01010`|2-D matrix `vl × vn`
`01011`|2-D matrix `vn × vl`
`01100`|2-D matrix `vm × vn`
`01101`|2-D matrix `vn × vm`
`0111x`|Reserved
`1xxxx`|Reserved

**Comment by aswaterman** [comment]
Since the vtype/vshape proposal has changed repeatedly since you opened this issue (apologies that some of the changes haven't made it back into this repo yet), I'm closing this for now.  If the next rev doesn't address your concerns, do re-open.
