### ISSUE TITLE
Typographical error in extended verepn encoding (table 17.4)

### ISSUE THREAD

**Issue by eternaleye** [riscv/riscv-isa-manual#150]
Table 17.4 has duplicate values of `verepn` between prime and binary extension Galois fields:

`verep`|Representation
---|---
`01000`|Prime Galois field - integer representation
`01001`|Prime Galois field - Montgomery representation
`01000`|Binary extension Galois field - polynomial basis
`01001`|Binary extension Galois field - normal basis

This was probably intended to be:

`verep`|Representation
---|---
`01000`|Prime Galois field - integer representation
`01001`|Prime Galois field - Montgomery representation
`01100`|Binary extension Galois field - polynomial basis
`01101`|Binary extension Galois field - normal basis

**Comment by kasanovic** [comment]
Fixed.
