### ISSUE TITLE
[RNMI] What is the impact of MNRET instruction on the value of MNSTATUS.MNPP?

### ISSUE THREAD

**Issue by zengderui** [riscv/riscv-isa-manual#1503]
Should .MNPP be set to the least-privileged supported mode on MNRET instruction as .MPP on MRET instruction?

**Comment by aswaterman** [comment]
Because the spec is silent on the matter, the implication is that MNPP is left unchanged.

**Comment by zengderui** [comment]
@aswaterman Thanks for confirming this!

**Comment by aswaterman** [comment]
You're welcome!
