### ISSUE TITLE
Proposal: explicitly allow _ to be used as a separator for standard extensions in ISA naming strings

### ISSUE THREAD

**Issue by asb** [riscv/riscv-isa-manual#151]
RV64I2p0M2p0A2p0F2p0D2p0 is horrible to read. It can of course be abbreviated RV64G2, but as new extensions are introduced with different version information we're not always going to have that choice. Explicitly allowing the underscore to be used would allow a representation with significantly enhanced human readability: RV64_I2p0_M2p0_A2p0_F2p0_D2p0. It would also seem consistent with the use of _ for separating X and proposed Z extensions.

**Comment by kasanovic** [comment]
Changed as requested.
