### ISSUE TITLE
nit (doc issue): remove reference to Zam in chapter 36 of unpriv ISA

### ISSUE THREAD

**Issue by deepak0414** [riscv/riscv-isa-manual#1523]
It's a nit documentation issue.

In unpriv spec,

`36.6. Additional Standard Extension Names` says

```
If multiple "Z" extensions are named, they should be ordered first by category, then alphabetically within a
category—for example, "Zicsr_Zifencei_Zam".
```

Since `Zam` doesn't exist anymore, I don't think it makes sense to use it as an example here.

**Comment by aswaterman** [comment]
Indeed.  I'll replace it here with Ztso.
