### ISSUE TITLE
Remove stale non-normative comment referring to a future version adding interrupt-based sampling

### ISSUE THREAD

**Issue by bcstrongx** [riscv/riscv-isa-manual#1553]
The priv spec still includes this out-dated comment in 3.1.10:

> A future revision of this specification will define a mechanism to generate an interrupt
> when a hardware performance monitor counter overflows.

The spec now includes the Sscofpmf extension, to which this comment was referring.  Better to modify this comment to say something like:

> See the Sscofpmf extension (Chapter 17) for how hardware performance counter overflows can generate interrupts.

**Comment by aswaterman** [comment]
One step ahead of you; we removed that sentence last month. c575e53ec36c6b1afbd908fd646da8f4cdc66dd7
