### ISSUE TITLE
Zama16b requires no more than MXLEN bits for F/D/Q extensions? 

### ISSUE THREAD

**Issue by romanheros** [riscv/riscv-isa-manual#1569]
In 3.6.4. Misaligned Atomicity Granule PMA, 
"The misaligned atomicity granule PMA applies only to AMOs, loads and stores defined in the base
ISAs, and loads and stores of no more than MXLEN bits defined in the F, D, and Q extensions".

If Zama16b has been supported, why no more than MXLEN bits width is required for F/D/Q？

**Comment by aswaterman** [comment]
The ISA already says that floating-point loads and stores wider than XLEN bits are not guaranteed to be atomic. (See the D extension chapter.)
