### ISSUE TITLE
Forgotten Sentence

### ISSUE THREAD

**Issue by AFOliveira** [riscv/riscv-isa-manual#1572]
While going through the spec I found this line on the [Cryptographic Extensions](https://github.com/riscv/riscv-isa-manual/blob/7ad72686a9bc7169abb581224de18062dfd3e1e3/src/scalar-crypto.adoc#cryptography-extensions-scalar--entropy-source-instructions-version-101) manual - p.408 - ["We expect to pick up this work in earnest in Q4-2021 or Q1-2022."](https://github.com/riscv/riscv-isa-manual/blob/7ad72686a9bc7169abb581224de18062dfd3e1e3/src/scalar-crypto.adoc?plain=1#L40) I don't know if it has been addressed or not but it seems to be forgotten in the manual.

**Comment by aswaterman** [comment]
The whole paragraph should be deleted, as this has long since been resolved.
