### ISSUE TITLE
Outdated page number

### ISSUE THREAD

**Issue by AFOliveira** [riscv/riscv-isa-manual#1574]
Hello!

There's a hardcoded page number reference that has become outdated:

https://github.com/riscv/riscv-isa-manual/blob/2f2f75dbc4160cb6cef22267bc133ca5aa6ac4c0/src/hypervisor.adoc?plain=1#L182

Current situation:
- The line references "page 19" for a specific table.
- The table is now actually on page 24.

I don't know if there is a way of dinamically linking pages based on a specific element (like a table) or if it is just better to remove the page reference since I believe this will keep getting outdated with  ISA manual revisions.

**Comment by aswaterman** [comment]
Hardcoded page numbers are a definite no-no.  If you see more of these, feel free to keep filing issues (or PRs to fix them).  In this case, the `<<misabase>>` link suffices, and we can just delete the page number.
