### ISSUE TITLE
When rm is added to the assembly, GCC fails to compile for fcvt.d.w/fcvt.d.wu/fcvt.s.h/fcvt.d.h/fcvt.d.s instructions

### ISSUE THREAD

**Issue by Shanchuang666** [riscv/riscv-isa-manual#1577]
![1722502872636](https://github.com/user-attachments/assets/93a79288-a03c-4bb7-9391-f1160cce54ca)

**fcvt.d.w / fcvt.d.wu / fcvt.s.h / fcvt.d.h / fcvt.d.s**

Although these instructions are always accurate, and the implementation is not affected by the rounding mode, the specification appears to be able to configure rm, but after adding rm to the assembly, gcc cannot compile successfully, indicating "illegal operands", then does the display at the specification screenshot need to be modified?

**Comment by aswaterman** [comment]
The ISA manual is correct. Just because the GNU assembler doesn’t support generating a given instruction doesn’t mean the instruction isn’t part of the ISA.

(You can always manually assemble the instruction using `.word` or `.insn`.)
