### ISSUE TITLE
Clarify Zicfilp landing pad fault behavior

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-isa-manual#1584]
The Zicfilp extension specifies three different ways that a landing pad fault can be generated:

1. When the target address is not 4-byte aligned;
2. When the target address does not contain an `LPAD` instruction;
3. When the target address contains an `LPAD` instruction with mismatching label.

If these faults occur, is it the _jump_ address or the _target_ address that is saved in `xepc` in each case?

Thanks.

**Comment by aswaterman** [comment]
I’ll just remark that it doesn’t matter what the answer is, because it’s a fatal trap.

**Comment by aswaterman** [comment]
My preference is that all of these traps are associated with the landing pad, rather than with the jump.

**Comment by JamesKenneyImperas** [comment]
I agree. A clarifying note on permitted behavior would be helpful I think.

**Comment by ved-rivos** [comment]
> If these faults occur, is it the jump address or the target address that is saved in xepc in each case?

Its the instruction at the target.  If the instruction at the target is not a landing pad instruction then it is that instruction which raises  the exception. Likewise when it is a landing pad instruction then the landing pad instruction  may itself raise an  exception if it is  misaligned or  has  a label mismatch.

See "Listing 7. LPAD operation"
```
if (xLPE == 1 && ELP == LP_EXPECTED)
    // If PC not 4-byte aligned then software-check exception
    if pc[1:0] != 0
        raise software-check exception
    // If landing pad label not matched -> software-check exception
   else if (inst.LPL != x7[31:12] && inst.LPL != 0)
        raise software-check exception
   else
        ELP = NO_LP_EXPECTED
else
       no-op
endif
```
Also please see this note (see  next instruction in the instruction stream):
>  When ELP is set to LP_EXPECTED, if the next instruction in the instruction stream is not 4-byte aligned, or is not LPAD, or if the landing pad label encoded in LPAD is not zero and does not match the expected landing pad label in bits 31:12 of the x7 register, then a software-check exception (cause=18) with xtval set to "landing pad fault (code=2)" is raised else the ELP is updated to NO_LP_EXPECTED.

The section 3.5 also makes it clear that the jump completes and updates the ELP. The instruction at the target may then fault based  on the ELP setup by the jump.

**Comment by JamesKenneyImperas** [comment]
Ok, I now understand the intent. I do think it would help to state this more explicitly though, because the "next instruction in the instruction stream" wording doesn't make it clear whether the fault is raised on _this_ instruction or the _next_ instruction in my mind.

I'll close this anyway and leave it up to you whether to clarify it. Thanks.
