### ISSUE TITLE
should mseccfg.MLPE be cleared at reset?

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-isa-manual#1591]
The `Zicfilp` specification states that ELP is cleared on reset, but specifies no requirement to reset any `Zicfilp` enable bits. I'm wondering whether this is safe - is it OK not to reset (at least) `mseccfg.MLPE` so that indirect jumps early in the reboot sequence do not fail unexpectedly?

Thanks.

**Comment by ved-rivos** [comment]
I will add a note to Zicfilp to state it it is reset to 0. I think it was not called out specifically as `mseccfg` if I recall right had a requirement to be reset to 0.

**Comment by ved-rivos** [comment]
Please see #1592

**Comment by JamesKenneyImperas** [comment]
Thanks for that clarification.
