### ISSUE TITLE
Reference Bug

### ISSUE THREAD

**Issue by AFOliveira** [riscv/riscv-isa-manual#1593]
Hello,

there is a bug in referencing which is noticeable in this type of referencing:

>===== (<<crypto_scalar_es_req_ptg2>>) BSI AIS-31
https://github.com/riscv/riscv-isa-manual/blob/cb6a5245a15e02c4152b74cd480fc3828bd9a5ba/src/scalar-crypto.adoc?plain=1#L4703

Both on HTML and PDF, the output generated is:

![image](https://github.com/user-attachments/assets/75d54d5d-b123-4e82-9a23-62d3582f02de)

Which is missing the first Section Number(34).  This happens in more references that have the same structure.

However, this does not happen when the number being referenced has less Levels such as:

>===== (<<crypto_scalar_es_access>>) Security Considerations for Direct Hardware Access
https://github.com/riscv/riscv-isa-manual/blob/cb6a5245a15e02c4152b74cd480fc3828bd9a5ba/src/scalar-crypto.adoc?plain=1#L4752

Which outputs:

![image](https://github.com/user-attachments/assets/01318aa0-217d-481d-9536-32d30cce80fe)

**Comment by wmat** [comment]
Note that references in section titles is not supported.  I'll clean these up.
