### ISSUE TITLE
Zicfiss/Zicfilp interaction with Zc extension

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-isa-manual#1595]
The Zc extension introduces some kinds of indirect jump that are not mentioned in the Zicfiss/Zicfilp specification. Specifically:
1. cm.jt (indirect table jumps);
2. cm.popret, cm.popretz (indirect returns).
Should Zicfiss/Zicfilp have any effect on the behavior of those?

Thanks.

**Comment by ved-rivos** [comment]
There is no interaction specified between Zc and Zicfiss/Zicfilp extensions.

1. The cm.jt/cm.jalt instructions use a jump table in instruction memory - not data memory. The table entry that the instruction selects is considered an extension of the instruction itself and thus execution of this instruction involves two instruction fetches -one to read the cm.jt/cm.jalt instruction and second to read the entry from the JVT. Both accesses require execute permission but not any other permission. Given this model, the cm.jt and cm.jalt were classified as instruction fetches and hence a form of direct branch for the purposes of Zicfilp and are not tracked by the ELP similar to other direct branches.
2. The cm.popret/popretz are not extended for Zicfiss. Software that wants to use Zicfiss would need to use CM.POP + C.SSPOPCHK + RET sequence. 

Zicfilp/Zicfiss are primarily targeting application processor class implementations. Zcmt is targeting embedded class CPUs and is not compatible with RVA profiles.

**Comment by JamesKenneyImperas** [comment]
Thanks.
