### ISSUE TITLE
Is the Length of the Guest Physical Address Implementation-Defined or Fixed to a Wider 2-Bit Format?

### ISSUE THREAD

**Issue by Wangrodman** [riscv/riscv-isa-manual#1606]
If the GPA length is implementation-defined, please consider the following questions:

1: When VSATP is SV48, the GPA length can be implementation-defined to be less than 50 bits (even though limits memory footprint). Before the G-stage, it is zero-extended to the length of HGATP.MODE (e.g., a GPALEN of 48 would require extending 2 zero bits to meet the SV48x4 format). 
2: When VSATP is BARE, the accessed address is truncated according to the implementation-defined narrower GPA length and then zero-extended to the length of HGATP.MODE.

**Comment by aswaterman** [comment]
I don't see anything in the spec that justifies that the GPA size is implementation-defined; AFAICS it's fixed for a given HGATP mode.

Your second question is still relevant, though.  It's misleading to say that bare VAs are truncated before conversion to GPA.  The entire XLEN-bit address is checked, and if any bit >= GPA-width is set, an exception is raised.

**Comment by Wangrodman** [comment]
When VSATP is BARE, is my understanding correct?
RV32: The wider 2-bit is zero-extended.
RV64: The wider 2-bit is accessing address[HGATP.GPALEN-1:HGATP.GPALEN-2].

**Comment by aswaterman** [comment]
Right.  And, for RV64, an exception is raised if address[XLEN-1:HGATP.GPALEN] != 0.

**Comment by Wangrodman** [comment]
> Right. And, for RV64, an exception is raised if address[XLEN-1:HGATP.GPALEN] != 0.

Got it, thanks. No further questions.

**Comment by MarkHillCodasip** [comment]
Can I just confirm that the RV-I position is that GPA widths (unlike PA widths) are not implementation defined. I just ask because this increases the costs associated with adding hypervisor support to TLB/page table caches as the GPA width could be many more bits than the PA.

For example, limiting the guest OS to the size of the physical address space available if it ran as the host OS seems a reasonable implementation choice to make. 

Also note that htval/mtval2 are WARL and "must be able to hold zero and may be capable of holding only an arbitrary subset of other 2-bit-shifted guest physical addresses" so are not required to support the full GPA associated with the G-stage  Sv(39/48/47)x2 translation schemes.

**Comment by aswaterman** [comment]
GPA widths are not implementation-defined.  They are set only by the hgatp.MODE setting.

(For what it's worth, I would not characterize PA widths as being implementation-defined, either.  The ISA doesn't have the concept of PA width as a parameter.  Instead, I'd characterize different parts of the PA space as being vacant on different implementations.)

**Comment by Wangrodman** [comment]
@aswaterman 
Due to the thread becoming active again, I came up with a related but not entirely identical question.

Is it really necessary to store GPA[11:2] in mtval2/htval? My understanding is that this might help software identify that a guest page fault occurred during the GPA-to-PA translation stage. However, this information is not entirely precise. For example, since VPN[2] and VPN[1] can have the same value, the recorded faulted GPA could end up being identical as well.

I also noticed that ARM does not record the faulted GPA[11:0], which makes me curious about the actual purpose of recording this information in RISC-V.

**Comment by aswaterman** [comment]
I'll leave it to someone else to discuss the rationale, but we are not going to subset the ISA at this point.  Providing this information is only a minor inconvenience.

**Comment by MarkHillCodasip** [comment]
Thanks for the confirmation @aswaterman.

I would say that the architecture does have implementation-defined PA width, specifically, the Privileged ISA spec has references to the parameter PABITS.

**Comment by allenjbaum** [comment]
PA width is a concise way of describing when PAs are non-canonical.
Canonical means all the bits above  bit position PA_width-1 are zero, which
has been used in discussions, though I don't see it mentioned in the spec.

**Comment by aswaterman** [comment]
> specifically, the Privileged ISA spec has references to the parameter PABITS.

Not that I'm aware of, nor can I find it by grepping.

> PA width is a concise way of describing when PAs are non-canonical.

I agree it's useful as informal shorthand, but it has no place in the spec.  It's much easier to describe the concepts if PA widths aren't limited.  Implementations are obviously free to do whatever they want if they implement the ISA correctly for their particular address maps.

**Comment by MarkHillCodasip** [comment]
OK that's fine, but just FYI it's in the pointer masking extension: https://github.com/search?q=repo%3Ariscv%2Friscv-isa-manual%20PABITS&type=code

**Comment by aswaterman** [comment]
Ah.  And nowhere else.  That should probably be deleted.
