### ISSUE TITLE
Include a sentence about being nondestructive to the stack pointer for C.ADDI4SPN

### ISSUE THREAD

**Issue by h-chal** [riscv/riscv-isa-manual#1618]
After a lot of puzzling and searching, @EdNutting found in v0.0.1 of the manual (before it was called such) that the N in C.ADDI4SPN stands for "nondestructive". https://stackoverflow.com/questions/78900543/what-does-n-stand-for-in-c-addi4spn. However, this is missing from the current description. While full instruction names are also missing from the manual, it would be nice to include that the stack pointer is not overwritten.

**Comment by aswaterman** [comment]
It's pretty obvious from the description that the stack pointer is not overwritten, since the description says the instruction expands to `addi rd′, x2, nzuimm[9:2]`. But I agree it would be helpful to include the parenthetical that expands the acronym.
