### ISSUE TITLE
Some doubts about interrupt and assembler

### ISSUE THREAD

**Issue by clx7913** [riscv/riscv-isa-manual#162]
I want to implement timer interrupt.

After I use asm volatile("li t0,0x08\n" "csrrs zero,mstatus,t0\n"),I successfully create the executable file.

But when I run it with `spike pk` ,the terminal tells me:

```
z  0000000000000000 ra 00000000000100e2 sp 000000007f7e9b40 gp 00000000000123d8
tp 0000000000000000 t0 0000000000000008 t1 0000000000000000 t2 0000000000000000
s0 000000007f7e9b50 s1 0000000000000000 a0 0000000000000001 a1 000000007f7e9b58
a2 0000000000000000 a3 0000000000000001 a4 0000000000000010 a5 0000000000000002
a6 000000000000001f a7 0000000000000000 s2 0000000000000000 s3 0000000000000000
s4 0000000000000000 s5 0000000000000000 s6 0000000000000000 s7 0000000000000000
s8 0000000000000000 s9 0000000000000000 sA 0000000000000000 sB 0000000000000000
t3 0000000000000000 t4 0000000000000000 t5 0000000000000000 t6 0000000000000000
pc 00000000000101a4 va 000000003002a073 insn       3002a073 sr 8000000200046020
An illegal instruction was executed!

```
I don't know what's wrong.Maybe I haven't get the Machine-mode priority?But how could I get the Machine-mode priority?By Trap?By exception?

I've saw the “risc-v-spec-v2.2" and "riscv-privileged-v1.10" but I'm still in chaos.

Any suggesstion would be greatly appreciated.

**Comment by aswaterman** [comment]
This is a cross-post from https://github.com/freechipsproject/rocket-chip/issues/1392
