### ISSUE TITLE
EPUB image not show

### ISSUE THREAD

**Issue by sequencer** [riscv/riscv-isa-manual#1621]
See images below:
![image](https://github.com/user-attachments/assets/6ea2b569-22f1-4203-8e1a-fe3dd5c9ebc2)

**Comment by TommyMurphyTM1234** [comment]
Duplicate of this? 

- https://github.com/riscv/riscv-isa-manual/issues/1607

I tried Moon+ and ReadEra on Android and neither displayed the images in the section cited above.

**Comment by sequencer** [comment]
Yes, it's seems to be duplicated.
