### ISSUE TITLE
Figure caption for Figure 1 is in the wrong place.

### ISSUE THREAD

**Issue by wmat** [riscv/riscv-isa-manual#1624]
For Figure 1, Types of immediate produced by RISC-V instructions.  The caption is appearing after the first wavedrom, it should be after the last wavedrom.

**Comment by kersten1** [comment]
This is in the unpriv guide. Looks like [rv32.adoc](https://github.com/riscv/riscv-isa-manual/blob/8b9dc50e562af27c9ab22ae0a2d3bf528c6bd41d/src/rv32.adoc#L199).

**Comment by wmat** [comment]
I’m already working on this one.
