### ISSUE TITLE
Incorrect status of Public Review version

### ISSUE THREAD

**Issue by mipsrobert** [riscv/riscv-isa-manual#1625]
Public review version has contradictory state (should be Frozen on first page, while it is water-marked Draft). Both State names are a layout of spec is well defined.

**Comment by wmat** [comment]
Is this referring to the Privileged spec v. 1.13?

**Comment by aswaterman** [comment]
@wmat yes, this was mentioned on an email thread.

However, I think no change is necessary.  As we move towards integrating specs into the main manuals, which might include other extensions that are at different stages, using a "FROZEN" watermark could be highly misleading for extensions that haven't yet reached that stage.  "DRAFT" is the conservative choice.
