### ISSUE TITLE
Wording problem in section 8.3

### ISSUE THREAD

**Issue by montedalrymple** [riscv/riscv-isa-manual#1626]
In section 8.3 the first sentence starts with "This proposal adds..."
Shouldn't that be "This extension adds..."

**Comment by kersten1** [comment]
It is in the [rnmi.adoc](https://github.com/riscv/riscv-isa-manual/blob/8b9dc50e562af27c9ab22ae0a2d3bf528c6bd41d/src/rnmi.adoc#L33) file

**Comment by kersten1** [comment]
fixed with https://github.com/riscv/riscv-isa-manual/pull/1662
