### ISSUE TITLE
URET from U-mode without N extension

### ISSUE THREAD

**Issue by gameboo** [riscv/riscv-isa-manual#163]
Hello.
I think the spec is not clear in [3.2.2](https://github.com/riscv/riscv-isa-manual/blob/ba5cfa4d1eb0aeb9e694dbaf6ccb05312cca02b0/src/machine.tex#L1970) about what should happen when a URET is executed from U-mode when the N extension is not present:

> URET is only provided if user-mode traps are supported

I presume that implicitly means "raise an illegal instruction exception if URET is executed from U-mode when the N extension is not present"?

**Comment by benjaminselfridge** [comment]
Yep, that's right. "Not supported" generally means "is considered an illegal instruction."

**Comment by gameboo** [comment]
OK cool. It would be worth being explicit here, no?
Thanks again.

**Comment by benjaminselfridge** [comment]
If you like, go ahead and submit a pull request; it has a decent chance of being integrated, I'd bet.
