### ISSUE TITLE
Zip and Unzip descriptions are reversed

### ISSUE THREAD

**Issue by wmat** [riscv/riscv-isa-manual#1632]
As reported on reddit "In the standard page 267 the description of the zip instruction doesn't match the operation, which is correct?" by PColim in the risc-v subreddit.  This applies to the 20240811 published version of unpriv.

**Comment by aswaterman** [comment]
@kdockser I'm having deja vu; I thought we already resolved this.

It looks like the SAIL code is correct but the descriptions are swapped.  Can you confirm and either file a PR or let me know so I can do so?

**Comment by kdockser** [comment]
As I recall, no one was sure how to modify and rebuild the scalar crypto spec, so fixing errors like this kept getting put off.
Please go ahead and file a PR for this (and any other outstanding fixes for Scalar crypto).
Thx

**Comment by pierrecolim** [comment]
Not only the description but also the encoding is incorrect, wording should be the same as in the ratified paper ( https://github.com/riscv/riscv-crypto/releases/download/v1.0.1-scalar/riscv-crypto-spec-scalar-v1.0.1.pdf )

**Comment by aswaterman** [comment]
@pierrecolim could you file a PR?

**Comment by pierrecolim** [comment]
no sorry, i never used github, i only have an account to open issues and comment

**Comment by aswaterman** [comment]
OK, done.  LMK if you spot any further issues @kdockser @pierrecolim https://github.com/riscv/riscv-isa-manual/pull/1635
