### ISSUE TITLE
C.ADDI16SP range clarification.

### ISSUE THREAD

**Issue by atoomnetmarc** [riscv/riscv-isa-manual#1633]
https://github.com/riscv/riscv-isa-manual/blob/af961756090d34139dd1ca81f16d5497bb485f7d/src/c-st-ext.adoc?plain=1#L612

Now: `represent multiples of 16 in the range (-512,496).`

Suggestion: `represent multiples of 16 in the range -512 to 496.`

I read `(-512,496)` as a single negative number. While `-512 to 496` is more clear and more in the style of: https://github.com/riscv/riscv-isa-manual/blob/af961756090d34139dd1ca81f16d5497bb485f7d/src/v-st-ext.adoc?plain=1#L2728

**Comment by aswaterman** [comment]
(x, y) is a standard representation for ranges, and we don't want to ban that.  The right fix is to add a space after the comma.  I'll handle that.

(Also, it should be [x, y], not (x, y), since the range is inclusive.)
