### ISSUE TITLE
weird instruction access fault

### ISSUE THREAD

**Issue by yf13** [riscv/riscv-isa-manual#1637]
Dear experts,

I encountered a weird exception with qemu-system-riscv32 v6.2 on Ubuntu:

```
Instruction access fault(1) mepc=0 mtval=0
```

I am wondering what case can lead to such an exception?

**Comment by allenjbaum** [comment]
A branch to (physical) address zero that has a hardcoded value of 0
would do that, I think.

**Comment by yf13** [comment]
thanks. my case was zero loaded to mepc before a mret.
