### ISSUE TITLE
Move register layout definitions into wavedrom

### ISSUE THREAD

**Issue by christian-herber-nxp** [riscv/riscv-isa-manual#1639]
The privileged spec defines the CSR layouts using wavedrom. The CLIC spec doesn't. This should be aligned.
The layout diagrams do not include descriptions, while the CLIC tables do.

Proposed Resolution:
Move CLIC CSR layouts to wavedrom. Merge the description text with from the layout table with the rest. There might be redundancies, in which the text that doesn't come from the table should take presedence.

**Comment by wmat** [comment]
Yes, absolutely.  Please let me know where I can see the CLIC CSR layouts.
