### ISSUE TITLE
Is uideleg a typo ?

### ISSUE THREAD

**Issue by gameboo** [riscv/riscv-isa-manual#165]
In [machine.tex](https://github.com/riscv/riscv-isa-manual/blob/master/src/machine.tex#L2078), the spec mentions

>the delegation registers {\tt [m|s|u]ideleg}

I presume `uideleg` is a typo... Or is there such a register?

**Comment by aswaterman** [comment]
I thought the register is named by the privilege level being delegated from, not to... In which case uideleg should not exist?

**Comment by mwachs5** [comment]
Good point! I defer to you.
-- 
Megan A. Wachs
Engineer | SiFive, Inc
1875 South Grant Street
Suite 600
San Mateo, CA 94402
megan@sifive.com

**Comment by aswaterman** [comment]
Confirmed and fixed.
