### ISSUE TITLE
Is there any GCC support for Smrnmi?

### ISSUE THREAD

**Issue by Silabs-ArjanB** [riscv/riscv-isa-manual#1651]
Hi,

Is there any GCC support for Smrnmi? Specifically I am looking for an equivalent of the 'interrupt' attribute which would add an m**n**ret instruction instead of an mret instruction as the epilogue (so that we don't have to write the interrupt handler entirely in assembly.

Best regards,
Arjan

**Comment by aswaterman** [comment]
Not that I'm aware of.

The RISC-V C API is documented at https://github.com/riscv-non-isa/riscv-c-api-doc.  The spec indicates that only regular interrupts are supported via the `interrupt` attribute.  But I see nothing wrong in principle with extending that scheme to support `__attribute__((interrrupt("rnmi")))` using `mnret`.

**Comment by Silabs-ArjanB** [comment]
Thank you for your feedback @aswaterman .
