### ISSUE TITLE
Vector CSRs missing from CSR listing table

### ISSUE THREAD

**Issue by Timmmm** [riscv/riscv-isa-manual#1671]
The table [Currently allocated RISC-V unprivileged CSR addresses](https://riscv-specs.timhutt.co.uk/spec/20240411/priv-isa-asciidoc.html#ucsrnames) is missing all of the vector registers:

* `vstart`
* `vxsat`
* `vxrm`
* `vcsr`
* `vl`
* `vtype`
* `vlenb`

**Comment by aswaterman** [comment]
Resolved by #1712 / #1714
