### ISSUE TITLE
Which interrupt has higher priority between LCOFI and SGEI?

### ISSUE THREAD

**Issue by demin-han** [riscv/riscv-isa-manual#1678]
section 3.1.9
Multiple  simultaneous  interrupts  destined  for  M-mode  are  handled  in  the  following  decreasing  priority
order: MEI, MSI, MTI, SEI, SSI, STI, LCOFI

section 19.2.3:
Multiple  simultaneous  interrupts  destined  for  HS-mode  are  handled  in  the  following  decreasing  priority
order: SEI, SSI, STI, SGEI, VSEI, VSSI, VSTI.

for LCOFI and SGEI, which has higher priority?

**Comment by gfavor** [comment]
For both M-mode and S-mode, LCOFI is lower priority than STI.  So, for consistency, one would expect LCOFI to also be lower priority than VSTI for HS-mode.

@jhauser-us Do you agree?

@demin-han Please go ahead and create a PR that adds LCOFI to the end of the list from section 19.2.3 that you quoted.  @jhauser-us or @aswaterman can then approve the PR (assuming they agree with it).

Thanks.

**Comment by demin-han** [comment]
> For both M-mode and S-mode, LCOFI is lower priority than STI. So, for consistency, one would expect LCOFI to also be lower priority than VSTI for HS-mode.
> 
> @jhauser-us Do you agree?
> 
> @demin-han Please go ahead and create a PR that adds LCOFI to the end of the list from section 19.2.3 that you quoted. @jhauser-us or @aswaterman can then approve the PR (assuming they agree with it).
> 
> Thanks.

In AIA, I found:
![image](https://github.com/user-attachments/assets/8f7d4474-bd0e-4a31-8a9c-e7807ffb0010)

LCOFI has lowest priority in standard interrupt, which is consistent with your said.

**Comment by aswaterman** [comment]
Agreed with the above; fix via #1679 has been merged.
