### ISSUE TITLE
menvcfg.CBIE not specified as WARL or other behavior

### ISSUE THREAD

**Issue by davidharrishmc** [riscv/riscv-isa-manual#1682]
menfcfg is defined in privileged spec Section 3.1.18 Figure 25.  CBIE is a 2-bit field, with the 10 encoding Reserved (see unprivileged spec Table 23).  

The privileged spec does not define the behavior of writing 10 to menvcfg.CBIE. Should it be WARL, WLRL, WPRI, etc. ?

**Comment by aswaterman** [comment]
@gfavor any objections to changing this text to declare the field WARL?  That's what Spike does.

**Comment by gfavor** [comment]
No objections.  And I assume you feel that WARL is more appropriate than WLRL (as well as being what Spike does)?

**Comment by aswaterman** [comment]
Yeah, in this case, it seems preferable to leaving the machine in an unspecified state.
