### ISSUE TITLE
How and when the RISC-V Virtual Memory plans to support DEP/SMEP/SMAP and Memory Encryption?

### ISSUE THREAD

**Issue by Steven-Li-Xiaogang** [riscv/riscv-isa-manual#1683]
https://github.com/riscv/riscv-isa-manual/blob/virtual-memory/src/supervisor.tex
1. For most modern PC and Server platform, virtual system security to be more important and almost to be mandatory requirements, virtual memory system should support memory encryption from PTE level to enable system to be more security. I also have notice that RISC-V virtual memory group ever set a C-bit in PTE but removed it quickly.
2. Also DEP/SMEP/SMAP also supported by most modern OS (Windows and Linux), like ARM MMU which relative PTE bits to support these features, I only figure out that we can use X-bit (=0) to implement SMEP feature.

Thanks,
Steven-Li

**Comment by lfiolhais** [comment]
SMAP and SMEP are already supported, see SUM bit in the `sstatus` CSR and the U and X bits in the PTE, respectively.

As far as I'm aware, memory encryption within the virtual memory system is considered non-ISA and implementation-specific.
