### ISSUE TITLE
When satp =bare, can we configure vsatp and hgatp !=bare for two-stage address translation ?

### ISSUE THREAD

**Issue by chara811** [riscv/riscv-isa-manual#1704]

**Comment by gfavor** [comment]
satp controls S/HS-mode translation.  vsatp and hgatp control two-stage transation.  So they are quite independent of each other.  Plus, in any case, all three can be configured independently of each other (the architecture expresses no constraints on this).

**Comment by rock-ifly** [comment]
> satp controls S/HS-mode translation. vsatp and hgatp control two-stage transation. So they are quite independent of each other. Plus, in any case, all three can be configured independently of each other (the architecture expresses no constraints on this).

Does this mean that, when HostOS doesn't use the MMU(satp.mode=Bare),  the hypervisor and guestOS can still work correctly if vsatp.mode != Bare and hgatp.mode != Bare ?

**Comment by aswaterman** [comment]
Yes.
