### ISSUE TITLE
fence pseudoinstruction clarification

### ISSUE THREAD

**Issue by jeras** [riscv/riscv-isa-manual#171]
Hi I am writing a RISC-V ISA disassembler in SystemVerilog, so I am going through the ISA spec (the current code is still based on an older version of the ISA).
https://github.com/jeras/riscv_asm_sv
I might have other comments later.

The fence pseudoinstruction is defined as:
https://github.com/riscv/riscv-isa-manual/blob/master/src/assembly.tex#L105
  fence iorw, iorw
which makes it unclear which specifies the predecessor and which is the successor.
I was trying to check if there is a better definition in the document (version 2.2), but I could not find anything explicit.

Regards,
Iztok Jeras

**Comment by johnwinans** [comment]
Risc-v spec 2.2 page 104 says that a FENCE is:

0000 pred succ 00000 000 00000 0001111

**Comment by aswaterman** [comment]
Pred is the first operand and succ is the second operand.

**Comment by jeras** [comment]
Is this something that will be updated in the document or should I try to ignore this kind of issues.

**Comment by aswaterman** [comment]
It belongs in riscv-asm-manual for sure. Eventually the assembly chapter will be deleted from the ISA manual, so that riscv-asm-manual is the canonical resource.
