### ISSUE TITLE
Understanding hypervisor extension

### ISSUE THREAD

**Issue by yf13** [riscv/riscv-isa-manual#1717]
I have some basic questions regarding hypervisor extension v1.0:

- Can we take `virtualization mode` as separate control in the hart? This means privilege mode value 2 is still reserved, the `privilege mode` value for both HS and VS are `1`, and that for both U and VU are `0`.

- Is there any way to learn current `virtualzation mode` of a hart from registers or debugging interfaces?

- Like we use `mret/sret` and `ecall` instructions to change privilege modes, how can we change the `virtualizaton mode`?

**Comment by aswaterman** [comment]
1. It is an orthogonal state, separate from mode.
2. Not from the current hart (by design). An external debugger can learn whatever it wants.
3. Read the hypervisor spec again.
