### ISSUE TITLE
Suggest removing outdated reference to user-mode interrupts

### ISSUE THREAD

**Issue by davidharrishmc** [riscv/riscv-isa-manual#1739]
Section 10.1.3 states

“Interrupts to S-mode take priority over any interrupts to lower privilege modes.”  

This appears to be a throwback to the unratified user mode interrupt N extension.  There are no longer interrupts to any lower privilege modes than S-mode, and this sentence seems it could be deleted.

**Comment by pdonahue-ventana** [comment]
If the H extension is implemented then this sentence seems relevant. You can have interrupts to VS mode which is less privileged than S/HS mode.

**Comment by davidharrishmc** [comment]
Fair enough.  I wasn't thinking about VS.  I'll close the issue.
