### ISSUE TITLE
Understanding m-mode SRET

### ISSUE THREAD

**Issue by yf13** [riscv/riscv-isa-manual#1746]
What is the use case of doing SRET in M-mode? Is it for classical virtualization support?

**Comment by Timmmm** [comment]
I had [the exact same question](https://stackoverflow.com/questions/77114054/why-would-you-sret-from-machine-mode) - there's a good answer there.

**Comment by yf13** [comment]
@Timmmm, thanks a lot. So it is to support virtualization on harts without H extension? do you know any open source virtualization solution using this feature?

**Comment by Timmmm** [comment]
Yeah that's my understanding. I have no idea what software actually implements it though. Maybe [one of these](https://www.riscfive.com/risc-v-virtualization/)?

**Comment by yf13** [comment]
many thanks!
