### ISSUE TITLE
The atomicity of A/D bit updating.

### ISSUE THREAD

**Issue by zhuotianshu** [riscv/riscv-isa-manual#1749]
In section 10.3:

> The PTE update must be atomic with respect to other accesses to the PTE, and must atomically perform all tablewalk checks for that leaf PTE as part of, and before, conditionally updating the PTE value.

What are the "tablewalk checks"? Does it mean checking the Valid bit, checking RWX permissions, etc. ? Does it include the "load" in order to get the page table so that I can perform a check?
Does it mean that I have to use a lr/sc pair to access page table: I have to use lr to load the PTE, then perform the check, then use sc to store the new PTE with A/D bit set?

**Comment by aswaterman** [comment]
Yes, you have the right idea.  You could also use a microarchitectural CAS loop instead of LR/SC, or you could define a new AMO micro-op that does the right things to avoid the loop and associated forward-progress concerns.  Either way, there is some complexity.
