### ISSUE TITLE
Unclear wording, if "V" extension guarantes EEW=64 vid and vrgather support on XLEN=32

### ISSUE THREAD

**Issue by camel-cdr** [riscv/riscv-isa-manual#1756]
Section 32.18.3 includes the following statement:

> The V extension supports all vector load and store instructions (Section Section 32.7), except the V extension does not support EEW=64 for **index values** when XLEN=32.

The term "index value" wasn't properly defined previously, but it was used to describe the elements of indexed load/stores, vid and vrgather.

I presume this exception for "index value" was made because indexed load/stores with 64-bit offsets don't make sense in a 32-bit addressed system.
I can't see any technical reason why EEW=64 wouldn't be supported in vid and vrgather, considering that the maximum useful index in both of them is 2^16, but the wording seems to imply this isn't guaranteed to work.

Is there something else in the spec that clarifies this, or is this an oversight?

**Comment by kasanovic** [comment]
This sentence is explicitly about vector load and store instructions, and so the exclusion is on the index values of load and store instructions only.  It does not read on other vector instructions.
