### ISSUE TITLE
ssrdp instruction

### ISSUE THREAD

**Issue by jiahzhang** [riscv/riscv-isa-manual#1758]
The spec says
```
Encoding rd as x0 is not supported for SSRDP.

```
What is the correct behavior if rd is 0? do nothing?

**Comment by ved-rivos** [comment]
This is the specified behavior:
> Zicfiss does not use all encodings of MOP.RR.7 or MOP.R.28. When a MOP.RR.7 or MOP.R.28 encoding is
not used by the Zicfiss extension, the corresponding instruction adheres to its Zimop-defined
behavior, unless redefined by another extension.
