### ISSUE TITLE
Outdated content in CMO CSR State section

### ISSUE THREAD

**Issue by jordancarlin** [riscv/riscv-isa-manual#1759]
Section 20.5 of the CMO chapter (Control and Status Register State) contains the following outdated text: 

> The CMO extensions rely on state in envcfg CSRs that will be defined in a future update to the privileged architecture. If this CSR update is not ratified, the CMO extension will define its own CSRs.

The CMO extensions have been ratified and the Priv ISA manual contains the following already:
> The definition of the CBZE field is furnished by the Zicboz extension.
The definitions of the CBCFE and CBIE fields are furnished by the Zicbom extension.

The note in 20.5 should be removed.

**Comment by wmat** [comment]
Can you go ahead and submit a PR for these changes?
