### ISSUE TITLE
SFENCE.VMA and PMP interactions

### ISSUE THREAD

**Issue by michaeljclark** [riscv/riscv-isa-manual#176]
"As noted on isa-dev, we forgot to write down the interaction between
PMPs and TLBs.  The idea is that VA->PA mappings can be cached, and
the PMP access can occur any time between the page-table walk and the
access itself.  In operational terms, PMPs can be cached in the TLB.
Hence, SFENCE.VMA should be executed after modifying PMPs that
underpin virtual-address translations." @aswaterman 

No required for SFENCE.VMA if satp.vm = bare.

**Comment by aswaterman** [comment]
I believe  https://github.com/riscv/riscv-isa-manual/commit/4a29140ef57e38532b3d3e43c9cd49e07066e7e0 addresses this issue; please reopen if I missed something.

**Comment by jillleon007** [comment]
"If page-based virtual memory is not implemented, memory accesses check the PMP settings synchronously, so no SFENCE.VMA is needed."

How to understand "not implemented"? for example，if the core support sv39，when the satp.vm=bare，Does it need sfence.vma to sync the pmp new config？

**Comment by jillleon007** [comment]
> I believe [4a29140](https://github.com/riscv/riscv-isa-manual/commit/4a29140ef57e38532b3d3e43c9cd49e07066e7e0) addresses this issue; please reopen if I missed something.

"If page-based virtual memory is not implemented, memory accesses check the PMP settings synchronously, so no SFENCE.VMA is needed."

How to understand "not implemented"? for example，if the core support sv39，when the satp.vm=bare，Does it need sfence.vma to sync the pmp new config？

**Comment by gfavor** [comment]
Irrespective of what satp.mode one operates in, if sv39 is supported, that equates to "page-based virtual memory is implemented".  And hence software needs to use an sfence.vma to sync PMP changes.

To help this make sense, note that designs that implement page-based virtual memory will have TLBs and will typically cache translations for all modes of operations.  And, as part of caching translations, the associated PMA and PMP information will also be cached.

So, for Bare mode, trivial 1-to-1 address translations, along with associated PMA and PMP info, will be cached.  In essence, Bare mode is not a special case for all the address datapaths.

**Comment by jillleon007** [comment]
> Irrespective of what satp.mode one operates in, if sv39 is supported, that equates to "page-based virtual memory is implemented". And hence software needs to use an sfence.vma to sync PMP changes.
> 
> To help this make sense, note that designs that implement page-based virtual memory will have TLBs and will typically cache translations for all modes of operations. And, as part of caching translations, the associated PMA and PMP information will also be cached.
> 
> So, for Bare mode, trivial 1-to-1 address translations, along with associated PMA and PMP info, will be cached. In essence, Bare mode is not a special case for all the address datapaths.

Thank you！
