### ISSUE TITLE
reset values of mstatus.mpp and mstatus.spp

### ISSUE THREAD

**Issue by noionion** [riscv/riscv-isa-manual#1771]
Is there a specific requirement for the reset values of mstatus.mpp and mstatus.spp? I found in the Spike code that during initialization, if the U mode exists, mstatus.mpp is set to 0. However, would directly setting it to 2b11 also comply with the specifications?

https://github.com/riscv-software-src/riscv-isa-sim/blob/a2dcf1fd70f359e2cf0a953986c9fe222a6d53c2/riscv/csrs.cc#L566-L577

**Comment by pdonahue-ventana** [comment]
See https://github.com/riscv/riscv-isa-manual/blob/main/src/machine.adoc#reset for the reset requirements.

**Comment by noionion** [comment]
It seems that there are indeed no strict requirements...
