### ISSUE TITLE
Do SSAMOSWAP support byte and half operation？

### ISSUE THREAD

**Issue by leBsky** [riscv/riscv-isa-manual#1772]
In Zabha extension, byte and halfword atomic memory operations are introduced as below:
![30423061-94EF-470a-AB35-3E2508EC1B27](https://github.com/user-attachments/assets/a24bb986-9b5a-4a91-9ca6-5714704acb7b)

For SSAMOSWAP.W/D introduced by Zicfiss extension, Do they support byte and half operation?

**Comment by ved-rivos** [comment]
SSAMOSWAP does not support byte or half word operands.
