### ISSUE TITLE
Zcmt: Questions about jvt CSR

### ISSUE THREAD

**Issue by rogerchang23424** [riscv/riscv-isa-manual#1778]
In the table jump section of `zc.adoc`, few questions want to ask:

1. The CSR index of jvt is 0x017, is the privilege of jvt CSR `URW`?

2. In following quote from spec, we require instruction barrier (fence.i) when updating the jump vector table. Do we also require instruction barrier(fence.i) when writing to jvt CSR?

> Memory writes to the jump vector table require an instruction barrier (fence.i) to guarantee that they are visible to the instruction fetch.

**Comment by aswaterman** [comment]
1. Yes.
2. No.
