### ISSUE TITLE
PMP config CSRs mapping on RV64 running with MXLEN=32

### ISSUE THREAD

**Issue by gameboo** [riscv/riscv-isa-manual#184]
Hello.

When on an RV64, Figure 3.24 shows that the PMPConfig entries are mapped to pmpcfg{0,2}.
When on an RV32, Figure 3.23 shows that the PMPConfig entries are mapped to pmpcfg{0,1,2,3}.

When on RV64, when changing MXLEN to 32, does the mapping of the CSRs change to that of Figure 3.23?

**Comment by gameboo** [comment]
Yes as in we dynamically change the mapping at runtime? (I'm sorry, I am not sure what the "more obvious mapping" is referring to...)

**Comment by aswaterman** [comment]
Yes, the mapping changes at runtime.

**Comment by gameboo** [comment]
ok great, thank you! (sorry a bit dense :p)
