### ISSUE TITLE
MXR for PMPs, not just paging?

### ISSUE THREAD

**Issue by aswaterman** [riscv/riscv-isa-manual#19]
MXR is currently defined to affect only paging.  I think we need to define MXR to affect PMPs, not just paging.  If a PMP marks a region is U-mode execute-only, it is currently impossible to use the MPRV mechanism alone to emulate that instruction.

**Comment by aswaterman** [comment]
Note this would make M-mode X-only PMPs effectively useless (except on M-only implementations, where the MXR bit does not exist).

**Comment by sorear** [comment]
My thought earlier was that MXR would be honored only when MPRV was in effect (ideally, R-only pages would fault when accessed under MXR+MPRV)

**Comment by aswaterman** [comment]
That makes it less likely for software to make MXR-related bugs, but doesn't close the M-mode X-only hole (as you can set MPRV=1, MXR=1, MPP=M).

**Comment by aswaterman** [comment]
Plan is to leave it as defined (only affects paging, not PMPs), and see what happens.
