### ISSUE TITLE
Clearing of load-reservation during context switch is not specified

### ISSUE THREAD

**Issue by asb** [riscv/riscv-isa-manual#193]
The user-level ISA manual states "The privileged architecture specifies the mechanism by which the implementation yields a load reservation during a preemptive context switch." I can find no such description in the privileged manual when searching for "reservation", "load-reserved", "context switch" and similar terms.

This mechanism is surely important for correctness. e.g. if a context switch occurs from thread A to thread B, both of which are executing instructions inside LR/SC pairs. If the same address range is reserved by both threads and the reservation isn't cleared upon context switch you could still see the SC in thread B succeed, even if its original reservation had been cleared (e.g. by a store).

**Comment by aswaterman** [comment]
This is an editing error from when the memory model was merged in.  SC *is* the mechanism for forcibly yielding a load reservation: "an SC must fail if there is another SC between the LR and the SC in program order."

So, the privileged architecture doesn't need to specify anything here.
