### ISSUE TITLE
Question on interactions with SFENCE.VMA 

### ISSUE THREAD

**Issue by gameboo** [riscv/riscv-isa-manual#204]
In the current spec, from what I understand so far:

- writes to `pte`s in memory need to be synchronized with `sfence.vma`
- writes to `pmp` csrs need to be synchronized with `sfence.vma`
- writes to the `satp` csr **do not** need to be synchronized with `sfence.vma` **edit**: to clarify, here, what I mean is that the very next instruction fetch following a write to satp that enable translation should be translated.

I simply want to confirm that this is indeed how the spec should be understood, as it felt slightly odd to me that `pmp` csrs need explicit synchronization and `satp` does not, implying some sort of microarchitectural support (probably a pipeline bubble in the most trivial implementations).

Thanks.

**Comment by aswaterman** [comment]
Yes, that's all true.

**Comment by aswaterman** [comment]
Mostly to make it easier to cache the PMPs inside cache tags, TLB entries, etc.  satp itself doesn't get cached anywhere.

**Comment by gameboo** [comment]
ok. thanks.

**Comment by gameboo** [comment]
Just realised I wanted to confirm something else on the same topic:
Say I have valid PTEs in a cache of some sort, and I update the PMP in such a way that I would no longer be allowed to fetch those PTEs. It is valid behaviour to still hit on those PTEs after the PMP update despite the fact that access to the PTEs is now forbidden, and this until an SFENCE.VMA instruction with rs1=x0 and rs2=x0 is executed. Correct?

**Comment by aswaterman** [comment]
Yeah that's right.

**Comment by gameboo** [comment]
Great thanks.
