### ISSUE TITLE
MCYCLE  ,  MINSTRET   when they are supposed to reset.

### ISSUE THREAD

**Issue by leelakrishnakola** [riscv/riscv-isa-manual#212]
Hi,

Privilege spec says "The mcycle CSR holds a count of the number of cycles the hart has executed since some arbitrary time in the past."

Can you please help explain what is expected to be "**some arbitrary time**".   Does this mean this register will get reset with any event ?

Thanks & Regards,
Leela Krishna.

**Comment by kasanovic** [comment]
This is unclear in the manual.   The M-mode mhpm counter registers are read/write, so count up from when they were last written, or from an arbitrary value at reset.

**Comment by kasanovic** [comment]
I added an update to manual to clarify.
