### ISSUE TITLE
Description of state transition upon exception

### ISSUE THREAD

**Issue by benjaminselfridge** [riscv/riscv-isa-manual#214]
In the RISC-V Reader, there are helpful descriptions of what the hardware does upon exceptions, on pages 105 (M-mode) and 111 (S-mode). However, nowhere in the user-level or privilege ISA manuals is a rendering of this set of atomic state transitions; the reader is left to deduce this on his/her own from the CSR descriptions.

I think this is a very useful thing to include, because it answers the question, "What happens during an exception?" in a single place, which also further clarifies the roles of the various CSRs involved and how exceptional behavior interacts with other aspects of the privileged architecture, in particular the xret instructions.

I would be happy to draft it myself, but I wanted to query first to determine whether I may have missed it somewhere in the spec.

**Comment by aswaterman** [comment]
Naturally, the book and the spec serve two different purposes, but I see your point.

Even so, I think the spec does a decent job as-is.  In "3.1.13 Machine Trap Delegation Registers (medeleg and mideleg)":

"When a trap is delegated to a less-privileged mode x, the x cause register is written with the trap cause; the xepc register is written with the virtual address of the instruction that took the trap; the x tval register is written with an exception-specific datum; the x PP field of mstatus is written with the active privilege mode at the time of the trap; the x PIE field of mstatus is written with the value of the x IE field at the time of the trap; and the x IE field of mstatus is cleared. The mcause and mepc registers and the MPP and MPIE fields of mstatus are not written."
