### ISSUE TITLE
RVWMO "Source and Destination Register Listings" lists RV64F twice

### ISSUE THREAD

**Issue by hahnjo** [riscv/riscv-isa-manual#218]
In section 6.3 (page 52) `RV64F Standard Extension` is listed twice:
https://github.com/riscv/riscv-isa-manual/blob/42f3c82d1a669004e0ccdd5eb6b8fa90d358141a/src/dep-table.tex#L363
https://github.com/riscv/riscv-isa-manual/blob/42f3c82d1a669004e0ccdd5eb6b8fa90d358141a/src/dep-table.tex#L439

I think the second header should be `RV64D` because it is about the `“D” Standard Extension for
Double-Precision Floating-Point`. That would at least be consistent with the `RV32/64G Instruction Set Listings` in Chapter 22.

**Comment by aswaterman** [comment]
Thanks for pointing out this error; I've fixed it.
