### ISSUE TITLE
c.srai a2, 0x0 // Exception or not ?

### ISSUE THREAD

**Issue by Imperas** [riscv/riscv-isa-manual#225]
Hi All

I have a question regarding the instruction
c.srai a2, 0x0

Firstly let me say that the gnu assembler will not allow this to be defined, but from the instruction format itself this can easily be constructed by the following value
0x8601
and inserted into the assembler as 
.short 0x8601

Page 77 of the manual says -
The shift amount is encoded in the shamt field, where shamt[5] must be zero for RV32C. For RV32C and RV64C, **the shift amount must be non-zero**. 

Page 82 of the manual -
C.SRAI (RV32 NSE, nzuimm[5]=1)
but it does not mention the restriction of shamt==0

Which is correct ?
If the shamt=0 for RV32, should this take an exception or not ?

Thx
Lee 

(edit)
interesting references
https://github.com/riscv/riscv-isa-sim/pull/181
https://github.com/riscv/riscv-isa-sim/issues/190

**Comment by aswaterman** [comment]
nzuimm is shorthand for nonzero unsigned immediate. So the table is consistent with the text.

Note that compliance tests should not test whether such illegal opcode a generate traps, because future ISA extensions (standard or nonstandard) could use those opcodes. In other words, trapping is valid behavior, but so is not trapping.

**Comment by Imperas** [comment]
Thanks for the reply, I am not sure why you are referring to compliance tests ?

My question is about the documentation, and whether an exception should be raised or not.
I think you are saying that an exception should NOT be raised for an RV32IC executing the opcode produced by
0x8601  // c.srai a2, 0x0

is my understanding correct ?

or are you saying that in this particular instance of executing this instruction 
> trapping is valid behavior, but so is not trapping.

So my question is, does this opcode constitute an illegal instruction for a specific release of the ISA, irrespective of whether this may change in a future release ?

**Comment by aswaterman** [comment]
My misunderstanding.  These instructions do not trap.  They are HINT instructions in RV32 and RV64.
