### ISSUE TITLE
Question about CSR instructions

### ISSUE THREAD

**Issue by IC-Dream** [riscv/riscv-isa-manual#229]
Hi,

From the riscv-spec-v2.2:
![csrrw](https://user-images.githubusercontent.com/39543344/45864696-69fd4d00-bdad-11e8-8ca1-d983871e1d20.PNG)
When rd=x0, the csrrw shall not read the CSR, but the initial value in rs1 still need write to the CSR, right?
Similarly, when rs1=x0, the csrrs/csrrc shall not write the CSR, but still need write the rd with the zero-extending value of CSR, right?  

Thanks
Dream

**Comment by aswaterman** [comment]
Yeah.

**Comment by IC-Dream** [comment]
Thanks for your quick answer!!!
