### ISSUE TITLE
Should we remove CSR shadow register convention?

### ISSUE THREAD

**Issue by kasanovic** [riscv/riscv-isa-manual#23]
Pro:
+ we expand available CSR address space
+ reduce number of register names in document
+ some registers might have more complex behaviors under new virtualization  scheme
Con:
- need more decoding to determine permissions

**Comment by aswaterman** [comment]
The only shadow registers we actually have are the counters, which may prove to be a special case.  Not sure we need to reserve so much address space for this purpose.  Maybe mark all remaining shadow space as Standard RW space for now, and simply avoid using it to keep our options open.

I don't think permissions decoding needs to become more expensive: can keep 11&10=>read-only and 9:8=privilege mode convention.

**Comment by David-Horner** [comment]
I concur that there is no value in preallocating shadow register ranges.

The question now become how to allocate the non-standard from the read/write as there is no longer a shadow split.

**Comment by kasanovic** [comment]
Updated spec.
