### ISSUE TITLE
Store-conditional success wording confusion.

### ISSUE THREAD

**Issue by ccelio** [riscv/riscv-isa-manual#231]
I found two sentences in the discussion about store-conditional success to be paradoxical. I would like for us to either clarify the laxness of the SC success requirement or to remove the implementation-defined address range.

Sentence 1:

> The SC **must** be to the same address and of the same data size as the latest LR executed.

Sentence 2:

> LR/SC sequences that do not meet these constraints might complete on some attempts on some implementations, but there is no guarantee of eventual success.

What is the intention here? Do we expect/hope/want people to write code to lock a cache line? Are we trying to be parsimonious in the hardware?

**Options:**

1) Remove second sentence and mandate that success only occurs on exact address and size match.
2) Change "must" to "should" and clarify that the address matching range is completely implementation defined. Or alternatively, clarify that the first sentence is for the programmer and the second sentence is for the hardware designer.

**Comment by aswaterman** [comment]
Later text answers this question quite clearly:

An SC may succeed if no store from another hart to the address range reserved by the LR can be observed to have occurred between the LR and the SC, and if there is no other SC between the LR and itself in program order.  Note this LR might have had a different address argument, but reserved the SC's address as part of the memory subset.

**Comment by aswaterman** [comment]
The correct fix to the text is not to remove "must", but to say "In standard software, the SC must...", to make it clear that it's referring to the software, not to the hardware.

**Comment by tommythorn** [comment]
How does that not lead to buggy code succeeding on some platforms and failing on others?  IOW, besides the hardware savings from being imprecise, is there a rationale for this?  To me this clearly constitutes a _change_ from the previous spec, not a clarification.

**Comment by aswaterman** [comment]
I pulled up the v2.1 spec from years ago and it said the same thing using the same words...

**Comment by tommythorn** [comment]
It say "must"

**Comment by aswaterman** [comment]
@tommythorn you are taking that out of context.

The paragraph begins, "In the standard A extension, certain constrained LR/SC sequences are guaranteed to succeed eventually."

The paragraph ends, "R/SC sequences that do not meet these constraints might complete on some attempts on some implementations, but there is no guarantee of eventual success."

In context, the "must" is obviously referring to the forward-progress guarantee.

**Comment by aswaterman** [comment]
I went back and looked at more old specs... the v2.0 just doesn't say anything about this stuff, aside from "sequences that do not meet these constraints might complete on some attempts" -- suggesting to me that this was always valid, but was ambiguous and underspecified.

v2.1 added the stuff about "reserving an arbitrary address range" and "LR might have had a different address argument".

**Comment by asb** [comment]
I can see how it's easy to come to the wrong conclusion when scanning the text for relevant statements, but I agree with Andrew that the natural reading of "The SC must be to the same address
and of the same data size as the latest LR executed." in the context of that paragraph, is that this is a requirement for the forward-progress guarantee.

Regarding rationale, the commentary immediately after that paragraph does explain why a forward-progress guarantee is necessary, and mostly enumerates the freedom that it gives hardware implementers. It doesn't explicitly state the advantages of allowing an implementation-defined reservation granularity, so that might be a worthwhile addition given that most other restrictions are justified.
