### ISSUE TITLE
misaligned instruction fetch exception ???

### ISSUE THREAD

**Issue by IC-Dream** [riscv/riscv-isa-manual#233]
Hi,

For one core which only supports RV32I, all of the control transfer instructions(jump and branch)  would raise a misaligned instruction fetch exception if the target address is not aligned to four-byte boundry, right ? I can find the following description for jumps in spec, but the branchs doesn't document anywhere. 
![branch](https://user-images.githubusercontent.com/39543344/46183008-7596c980-c301-11e8-9d3e-079b81d43955.PNG)

Thanks
Dream

**Comment by aswaterman** [comment]
In the section "Base Instruction Formats," it says "An instruction-address-misaligned exception is generated on a taken branch or unconditional jump if the target address is not four-byte aligned."

(Note that not-taken branches do not generate the exception.)

**Comment by IC-Dream** [comment]
okay, Thanks.
