### ISSUE TITLE
rename *ptbr to *atp?

### ISSUE THREAD

**Issue by kasanovic** [riscv/riscv-isa-manual#24]
problem: *ptbr has "r" on end for register, which is not convention (except legacy fcsr), also contains more than a page table pointer, and not all uses will include a page table pointer.
proposal: *atp for "address translation and protection"

**Comment by aswaterman** [comment]
I like *atp better, but binutils is released and has sptbr name.  Would be best not to change at this point.

**Comment by asb** [comment]
You could always add *atp and keep sptbr as an alias for compatibility.

**Comment by aswaterman** [comment]
That's true.

I'm fine either way.

**Comment by David-Horner** [comment]
I'm hoping that upstream implementations do not entrench obsolete and misleading conventions/specifications, but that they can be depreciated once better alternatives are provided.

**Comment by aswaterman** [comment]
Hauser's take:

> While there are a lot of plausible options, I see the register as
> primarily specifying the root page table:  its location in memory, how to
> interpret it (MODE), and what ASID to associate with it.  I like the word
> "root" better than "base" here, because the active page tables obviously
> form a tree, and "root" is the standard term for this node in a tree data
> structure.  With that logic, I'd probably choose the name 'srpt'.

**Comment by kasanovic** [comment]
Not all values put in this register will necessarily be pointers to a memory-resident table (e.g., some future base+bound scheme that is specified entirely by bits in the register), hence why I was suggesting "*atp" as generic term for address translation and protection specifier. Can be usefully misinterpreted as address translation pointer by reader.
