### ISSUE TITLE
sip / sie register description missing M*IP / M*IE bits

### ISSUE THREAD

**Issue by rbohn** [riscv/riscv-isa-manual#240]
In another [issue](https://github.com/riscv/riscv-isa-manual/issues/153) a set of questions were raised about whether "machine" interrupts / exceptions can be delegated to lower privilege levels. In response to a question about whether MTIP becomes STIP when delegated to supervisor, Andrew stated:

> No, there's no crosstalk between these fields. **If MTIP were delegated, it would show up in the MTIP bit in sip.**

I think this points to a source of confusion in the current specification. Per the description in 4.1.5 "Supervisor Interrupt Registers" **there is no defined MTIP bit in sip.** The corresponding bit position is defined as WPRI, and the ensuing text goes on to describe the U*IP, S*IP.

Based on the responses I believe that sip / sie, as far as the specification is concerned, should have the same bits as mip / mie, with the visibility determined by mideleg as described in the mideleg description.

I think the idea that, for example, mideleg[MTIP] is a potentially-writable bit that allows delegation to a lower privilege mode, yet the lower-privilege xIP register defines the bits as WPRI, leads to a thought process that MTIP gets converted to STIP / UTIP when delegated.

**Comment by rbohn** [comment]
Maybe it's too late for this, but just changing the names of the bits I
think would go a long way towards minimizing sources of confusion. The M /
S / U prefixes create a lot of initial confusion when people are first
reading the spec I think. But they've been named like this for a long time
so I can understand not wanting to change.

I agree a picture would be good. Or even some pseudo code that shows the
relationship between *deleg and *ip / *ie registers (something that looks
like what an eventual formal model might show?).

**Comment by aswaterman** [comment]
Indeed, changing the names isn't in the cards.  Maybe a picture with pseudocode in the caption.
