### ISSUE TITLE
Missing instruction in list of RVC, Quadrant 2

### ISSUE THREAD

**Issue by RolfyYu** [riscv/riscv-isa-manual#241]
In Table of RVC Quadrant 2, when bit[15:13] = 3'b100,
bit[12] = 1 and bit[11:2] = 0 is **C.EBREAK**.

But there is no Reserved mark of
bit[12] = 0 and bit[11:2] = 0

**Comment by aswaterman** [comment]
It looks to me that the C.JR line completely covers that case (note the "RES, rs1=0" to the right of C.JR).
