### ISSUE TITLE
Add rationale for divide-by-zero choice

### ISSUE THREAD

**Issue by kasanovic** [riscv/riscv-isa-manual#25]
Shouldn't be undefined.
-1 was value seen in other simple implementations and drops out of simple hardware implementations.

**Comment by kasanovic** [comment]
Added rationale for choice of overflow quotient values to spec.

**Comment by karlosz** [comment]
I think there is a typo in the rationale where it says `and this check can be inserted after the divide`. The branch to check for division by zero should not be done after the divide instruction. At that point the divisor may have been destroyed, ie. if it was the destination of the divide instruction. Instead, the check must be inserted before the divide instruction.

**Comment by aswaterman** [comment]
That was intentional; putting the branch after the divide is desirable for code scheduling.

The compiler understands that the destination will be overwritten even on a divide by zero, and can choose the destination register accordingly.
