### ISSUE TITLE
SBI acronym expansion

### ISSUE THREAD

**Issue by atishp04** [riscv/riscv-isa-manual#251]
It is mentioned as supervisor binary interface (SBI) in chapter 1
(https://github.com/riscv/riscv-isa-manual/blob/master/src/intro.tex#L126)
while system binary interface (SBI) in Chapter 4.
(https://github.com/riscv/riscv-isa-manual/blob/master/src/supervisor.tex#L9)

I believe it's supervisor binary interface instead of system binary interface. 

I can submit a PR either way.

Regards,
Atish

**Comment by aswaterman** [comment]
It's "supervisor."  I'll fix it.
