### ISSUE TITLE
cache maintenance

### ISSUE THREAD

**Issue by dangerblue** [riscv/riscv-isa-manual#252]
Hi，several question about the cache maintenance in a SMP system.
1.does the fence instruction need to flush the dcache? 
    if not, the description about the fence.i has problem. "To make a store to instruction memory
visible to all RISC-V harts, the writing hart has to execute a data FENCE before requesting that
all remote RISC-V harts execute a FENCE.I" 
  if it does, the fence instruction will cause massive performance loss.
2. dose the sfence.vma need to flush the dcache?
  the same problem as the first one, if not, it need the hart to use a fence instruction to flush the data into the memory, which will be expensive
   if does, the sfence.vma will be expensive
although, the tlb can be cached in dcache, but it still make the implementation complex.

thanks.

**Comment by aswaterman** [comment]
Nothing in the ISA mandates cache flushes.  The ISA specifies some ordering constraints, and whether or not cache flushes are necessary is a property of the microarchitecture.  FWIW, lots of people build RISC-V processors that do not need cache flushes on FENCE, FENCE.I, or SFENCE.VMA.
