### ISSUE TITLE
Clarify that bits 16 and up of *ip/*ie are "custom"

### ISSUE THREAD

**Issue by kasanovic** [riscv/riscv-isa-manual#271]
The figures showing *ip/*ie should be changed to reflect that bits 16 and up are intended for custom fast local interrupts, not reserved for future standard use.

**Comment by aswaterman** [comment]
Here's a screenshot; had to shrink the font size to squeeze it in.

![screen shot 2018-11-26 at 3 13 42 pm](https://user-images.githubusercontent.com/1031106/49047942-e8031900-f18d-11e8-9d48-c3ffa6bf8cdd.png)
