### ISSUE TITLE
CSR Commentary on Side Effects

### ISSUE THREAD

**Issue by acw1251** [riscv/riscv-isa-manual#272]
From https://github.com/riscv/riscv-isa-manual/blob/master/src/csr.tex#L134-L137:
```
  The CSRs defined so far do not have any architectural side effects beyond
  raising illegal instruction exceptions on disallowed
  accesses.  Custom extensions might add CSRs with side effects on
  reads and/or writes.
```
I'm not sure exactly what is meant by "The CSRs defined so far", but if you are considering the floating point CSRs and mstatus from the privileged spec, then writing to any of the floating point CSRs should  have the side effect of setting the mstatus.fs bits to dirty.

**Comment by aswaterman** [comment]
Thanks, amended the comment so it only applies to read side effects, not writes.
