### ISSUE TITLE
Canonical order for Z* extensions.

### ISSUE THREAD

**Issue by kito-cheng** [riscv/riscv-isa-manual#273]
All Z* extension like Zifencei, Zicsr, Zam, Ztso should be listed in Table 28.1 with canonical order, or it's order free between Z* extension?

**Comment by asb** [comment]
My assumption would be that Z extensions would be treated like Xfoo, Sbar, SXbaz and there is no required order between extensions within one of those categories (X/S/SX) them. Though it might be worth suggesting that ISA strings are canonicalised to sort extensions alphabetically within the X/S/SX/Z categories when being stored.

Table 28.1 should really be updated to show how Z should be ordered with Xabc/Sdef/SXghi

**Comment by aswaterman** [comment]
Proposal: they should be ordered first by category (I->M->A->F->D, for example), then alphabetically within a category.

**Comment by kito-cheng** [comment]
> Proposal: they should be ordered first by category (I->M->A->F->D, for example), then alphabetically within a category.

Sound good to me, how about `Ze`? I ask that because E is not listed in the table too, or there is no  `Ze`? if so, it might worse to write into spec?

**Comment by aswaterman** [comment]
There's no concept of `Ze` yet, so I think we can wait to make a decision until `Ze` is created :)
