### ISSUE TITLE
Change of the meaning version of 'G'

### ISSUE THREAD

**Issue by kito-cheng** [riscv/riscv-isa-manual#274]
Meaning of version for G, G2p0 is equal to I2p0_M2p0_A2p0_F2p0_D2p0, however `I` incremented to 2.1 and `F` and `D` has incremented to 2.2, perhaps we can change the definition of `G` version, let it related to version of unprivileged ISA? e.g. G2p0 meaning I2p0_M2p0_A2p0_F2p0_D2p0 and G2p2 meaning
I2p1_M2p0_A2p0_F2p2_D2p2 or I2p1_M2p0_A2p0_F2p2_D2p2_Zicsr_Zifencei ?

**Comment by aswaterman** [comment]
The meaning of G needs to change to encapsulate the new Z-extensions, and we will try to address the versioning issue at that time.

**Comment by kito-cheng** [comment]
I think it's time to face this problem.

@asb @jim-wilson @aswaterman
