### ISSUE TITLE
Spec is unclear on the consequences of implementing "non-conforming" extensions

### ISSUE THREAD

**Issue by asb** [riscv/riscv-isa-manual#288]
Is an implementation that provides "non-conforming" extensions still "RISC-V"?

**Comment by aswaterman** [comment]
That’s determined by the Foundation-chartered compliance-testing effort, not by this document.

**Comment by asb** [comment]
I can find no evidence that is the case. The charter for the Compliance TG as proposed in the meetings on [22nd March](https://workspace.riscv.org/higherlogic/ws/groups/Compliance_TG/documents/meeting_documents/document?document_id=234) and [2nd May 2018](https://workspace.riscv.org/higherlogic/ws/groups/Compliance_TG/documents/documents/document?document_id=248) does not include that responsibility. I can't find any indication that a different charter was adopted, but maybe it's just under-documented...

**Comment by aswaterman** [comment]
It's implicit.  Something that passes the compliance tests is RISC-V.

**Comment by kasanovic** [comment]
An implementation is "RISC-V" if it implements the spec for the components it claims to be compatible with.  For example, an implementation can be "RISC-V RV32IMA" ISA compliant even if it has non-conforming extensions in F and D space.  A platform might declare that non-conforming extensions are non-compliant, but that is not required of all platforms.
