### ISSUE TITLE
Is Zicsr a dependency of the F and D extensions?

### ISSUE THREAD

**Issue by asb** [riscv/riscv-isa-manual#289]
The F extension chapter describes FRCSR, FSCSR, FRRM, FSRM, FRFLAGS, FSFLAGS. These are defined in table 26.3 as expanding to csrrs/csrrw. It would obviously be natural to implement `Zicsr`, but is it a requirement? Is it valid to have e.g. an RV32IF implementation that only supports frcsr/fscsr/frrm/fsrm/frflags/fsflags but none of the other CSRs and not CSRRC/CSRRWI/CSRRSI/CSRRCI (even only for the CSRs introduced in the F extension?).

If F does imply Zicsr, is it necessary to state it in the ISA string? i.e. rv32if would become illegal in the same way rv32id is. EDIT: actually, the ISA manual doesn't seem to express a view either way on whether extensions can be omitted from the ISA naming string in this way, it's just something GCC chose to do. Opened #290 to gain clarity on this.

**Comment by aswaterman** [comment]
Well, there's already plenty of library code in existence that uses the set/clear operations on the FCSR, so having F without Zicsr is not gonna work so well.  I'll make it clear that F depends on Zicsr.
