### ISSUE TITLE
Restrict naming rule can be letters only for X*, S*, SX* and Z*

### ISSUE THREAD

**Issue by kito-cheng** [riscv/riscv-isa-manual#294]
All of naming rule in current spec only said: `name beginning with a letter`, it a little too loosely, I purpose it should be more restrict, the name can be only consists of letters.

> Standard extensions can also be named using a single “Z” followed by a name beginning with a
letter and an optional version number.

> Non-standard subsets are named using a single “X” followed by a name beginning with a letter
and an optional version number.

> Standard supervisor instruction-set extensions are defined in Volume II, but are named using “S”
as a prefix, followed by a supervisor subset name beginning with a letter and an optional version
number.

**Comment by aswaterman** [comment]
Agreed, I'm updating the text to replace "name beginning with a letter" with "alphabetical name"
