### ISSUE TITLE
Fix text regarding accessibility of debug CSRs

### ISSUE THREAD

**Issue by ernie-sifive** [riscv/riscv-isa-manual#295]
https://github.com/riscv/riscv-isa-manual/blob/5f111da2fadf82865af018e473ce728ebfc20622/src/priv-csrs.tex#L109-L111

Debug CSRs in the range 0x7A0-0x7AF are accessible from machine mode.  Only 0x7B0-0x7BF should trap when accessed in machine mode.

**Comment by aswaterman** [comment]
Whoops, looks like we got this right in Table 2.5, but wrong in the text.
