### ISSUE TITLE
Hypervisor guest time delta

### ISSUE THREAD

**Issue by aswaterman** [riscv/riscv-isa-manual#298]
It has been requested that we add htimedelta[h] CSRs so that hosts can lie to guests about the current time, without requiring trapping and emulating.  There is no intent to add equivalent CSRs for cycle/instret.

https://groups.google.com/a/groups.riscv.org/forum/#!searchin/isa-dev/Time$20offset%7Csort:date/isa-dev/9F_-XcUd2kU/bhxHgb62BQAJ

cc @jhauser-us

**Comment by bonzini** [comment]
Please do include the same CSRs for `cycle`, since the SBI set timer callback has absolute cycles as the argument. I agree that instret and performance counters can be handled via trap and emulate.

**Comment by aswaterman** [comment]
sbi_set_timer is specified in terms of the time counter, not the cycle counter.  We're covered, as far as timer interrupts go.
