### ISSUE TITLE
Conditional branch signed offset clarification

### ISSUE THREAD

**Issue by wdc-pnl** [riscv/riscv-isa-manual#306]
The “Conditional Branches” section states:
All branch instructions use the B-type instruction format. The 12-bit B-immediate encodes signed offsets in multiples of 2, and is added to the current pc to give the target address.

The “Unconditional Jumps” section uses a more explicit wording regarding “signed”:
The jump and link (JAL) instruction uses the J-type format, where the J-immediate encodes a signed offset in multiples of 2 bytes. **The offset is sign-extended and** added to the pc to form the jump target address.

The “Conditional Branches” section should be changed to:
All branch instructions use the B-type instruction format. The 12-bit B-immediate encodes signed offsets in multiples of 2 **bytes. The offset is sign-extended** and added to the current pc to give the target address.

**Comment by aswaterman** [comment]
Thanks for the suggestion; keeping the descriptions symmetric reduces confusion.
