### ISSUE TITLE
CSRs with side effects

### ISSUE THREAD

**Issue by brucehoult** [riscv/riscv-isa-manual#316]
In csr.tex:
"The CSRs defined so far do not have any architectural side effects on reads beyond raising illegal
instruction exceptions on disallowed accesses. Custom extensions might add CSRs with side
effects on reads."

Doesn't the CLIC do that?

**Comment by aswaterman** [comment]
Does it?

**Comment by aswaterman** [comment]
I checked the spec, and the side effects are only actioned on writes, as I had hoped.  So this sentence stands for now.
