### ISSUE TITLE
Add ISA extensions dependence/implicit table to ISA spec

### ISSUE THREAD

**Issue by kito-cheng** [riscv/riscv-isa-manual#317]
After https://github.com/riscv/riscv-isa-manual/commit/619b1938bdb2da7fd97853d61e767f455cf2a62a , we've allow implicit extension in ISA string, so I think it worth to add a table to list all dependence/implicit  relation, maybe in  `Chapter 28 ISA Extension Naming Conventions`?

**Comment by aswaterman** [comment]
Agreed.
