### ISSUE TITLE
fence.i privilege 

### ISSUE THREAD

**Issue by dangerblue** [riscv/riscv-isa-manual#318]
Hi, 
As the fence.i is the only instruction that maintain the instruction cache coherence. Fence.i will be implemented as an icache flush in a non-hardware coherent icache. So, what's the execution privilege level of the fence.i instruction? can user level  program execute fence.i?

**Comment by aswaterman** [comment]
Yes.

Note that in the Linux ABI, though, I$ flushing is done with a library call, not with fence.i.

https://github.com/bminor/glibc/blob/43b1048ab9418e902aac8c834a7a9a88c501620a/sysdeps/unix/sysv/linux/riscv/sys/cachectl.h#L27
