### ISSUE TITLE
State of pmpaddr[G-1] after changing from OFF / TOR => NAPOT for G >=1

### ISSUE THREAD

**Issue by rbohn** [riscv/riscv-isa-manual#320]
One clarification on the PMP spec. The specification states that if:

>  the mode is OFF or TOR, then bits pmpaddri[G-1:0] read as all zeros

And similarly if:

> the mode is NAPOT, then bits pmpaddri[G-2:0] read as all ones

Consider the following code:
```
csrwi pmpcfg0, 0
li  t0, -1
csrw pmpaddr0, t0
csrwi pmpcfg0, 0x1f
csrr t0, pmpaddr0
```

What should the value of t0[G-1] be in this case when G >= 1? Is it 0 because when the PMP entry was set to OFF pmpaddr[G-1] read as 0? Or is hardware meant to keep track of what software wrote in bit [G-1] when [G-1] was otherwise defined to read as 0?

**Comment by aswaterman** [comment]
It's the latter option, which we tried to imply by saying "reads as" rather than saying that the register is actually modified.  But it really isn't clear at all.  We'll fix that.
