### ISSUE TITLE
Is NA4 considered illegal for WARL purposes when G>=1?

### ISSUE THREAD

**Issue by rbohn** [riscv/riscv-isa-manual#321]
The specification states:

> When G ≥ 1, the NA4 mode may not be selected. 

Is this meant to indicate that NA4 is illegal for the hardware to read back NA4 in the A field when G>=1, since the A field is defined as WARL? Or is this statement meant to be a prohibition / recommendation to software?

**Comment by aswaterman** [comment]
As you pointed out, the A field is WARL, which I think suffices to answer the question.  But I'll change the text from "may not be selected" to "is not selectable," which I hope will clarify that software is welcome to attempt to select NA4, but the write will not stick.
