### ISSUE TITLE
how to clear stip bit in Smode

### ISSUE THREAD

**Issue by dangerblue** [riscv/riscv-isa-manual#322]
Hi,
As in the description of stip, the Smode timer interrupt pending bit can only be set and clear by Mmode. In a linux system, the S mode timer interrupt will be delegate to S mode, but Smode does not have the permission clear the stip, that would make the system stuck in the timer interrupt servive program. so, what's the consideration of not giving the write permission to S mode

**Comment by aswaterman** [comment]
In the normal use case, the timer-interrupt handler will schedule a new timer interrupt, which should clear STIP.  In all other cases, it should suffice to clear STIE instead.  You can see this thread for a more thorough discussion: https://github.com/riscv/riscv-pk/pull/108
