### ISSUE TITLE
Hypervisor CSR addresses

### ISSUE THREAD

**Issue by avpatel** [riscv/riscv-isa-manual#324]
Please provide exact 12bit addresses of hypervisor CSRs. Currently, this is blocking us to add hypervisor extension in emulators/simulators (i.e. QEMU).

**Comment by aswaterman** [comment]
Here is the tentative assignment (note it’s not frozen):

   200  bsstatus
   204  bsie
   205  bstvec
   210  reserved for bsstatush
   214  tentatively reserved for bsieh
   240  bsscratch
   241  bsepc
   242  bscause
   243  bstval
   244  bsip
   254  tentatively reserved for bsiph
   280  bsatp
   A00  hstatus
   A02  hedeleg
   A03  hideleg
   A12  tentatively reserved for hedelegh
   A13  tentatively reserved for hidelegh
   A80  hgatp

**Comment by avpatel** [comment]
Thanks, we will use tentative CSR addresses for now.

BTW, what are some of these CSRs with "h" suffix namely bsstatush, bsieh, bsiph, hedelegh, and hidelegh ?

**Comment by aswaterman** [comment]
Those hold the upper 32 bits of a CSR for RV32 only. They aren’t fully spec’d yet, and you can ignore them for RV64.

**Comment by aswaterman** [comment]
Closed by https://github.com/riscv/riscv-isa-manual/commit/516b9ed10b7c3bf17593034b66bd2c203d26a510
