### ISSUE TITLE
clarifying xPP language

### ISSUE THREAD

**Issue by pmundkur** [riscv/riscv-isa-manual#331]
There are some things not clear around xPP.

. It's not clear what xPP is set to on reset, especially when taking into account which privilege modes are supported.

  For e.g., it would be nice in the formal spec to also clarify what MPP and SPP are for an M/S system (i.e. no U-mode).

. The current language for xRET is not clear:

  "When executing an xRET instruction, supposing xPP holds the value y, x IE is set to xPIE; the privilege mode is changed to y; xPIE is set to 1; and xPP is set to U (or M if user-mode is not supported)."

  Clearly this cannot apply to SRET in an M/S system, since SPP cannot represent M.

. Suggested clarification:

  Since xPP are WARL, reset should set them to legal values, i.e. if x is a supported privilege level, then xPP should be the lowest supported privilege lower than or equal to x.

  This would mean, for e.g., that MPP and SPP would be S on reset for an M/S system.

  Also, for xRET, it could read "... to 1; and xPP is set to the lowest supported privilege lower than or equal to x."

  This would mean that SRET in an M/S system would always set SPP to S (i.e. SPP could be hardwired to S), and similarly for MRET and MPP.  However, this would be an incompatible change with the current language for M/S systems, since according to it currently MRET should set MPP to M on an M/S system.

  But the reset clarification above would still be compatible with this current language: "If privilege mode x is not implemented, then xPP must be hardwired to 0."

**Comment by aswaterman** [comment]
Per the Reset section, "All other hart state is unspecified."  That includes xPP.  Doing anything else wouldn't be a clarification; it would be a backwards-incompatible change.

Re: xRET: S-mode implies the existence of U-mode, therefore SRET always sets SPP to U.

**Comment by pmundkur** [comment]
"S-mode implies the existence of U-mode": 

It would help if this line was added to this statement in the misa section:
"The “U” and “S” bits will be set if there is support for user and supervisor modes respectively."
which on a literal reading imply that U and S are independent.

M/S systems were causing weird corner cases in the formal spec.

**Comment by aswaterman** [comment]
FWIW, that claim is encoded here 
https://github.com/riscv/riscv-isa-manual/blob/master/src/priv-intro.tex#L157

**Comment by pmundkur** [comment]
Ok, thanks.

**Comment by aswaterman** [comment]
No prob, thanks for the careful consideration of details in the spec, as always.
