### ISSUE TITLE
Behavior of lr-release and sc-acquire encodings unspecified

### ISSUE THREAD

**Issue by joshuascheid** [riscv/riscv-isa-manual#338]
riscv-spec V20181221 Section 8.2:
> The rl bit on an LR instruction must not be set unless the aq bit is also set. The aq bit on an SC
> instruction must not be set unless the rl bit is also set.

This leaves open the "or else, what?" question.

**Comment by aswaterman** [comment]
A valid point; making a PR to clarify.
