### ISSUE TITLE
Does the fence instruction include "barrier+dcache_flush" or just "barrier"?

### ISSUE THREAD

**Issue by csh93chou** [riscv/riscv-isa-manual#341]
Does the fence instruction include just "barrier" or "barrier+dcache_flush"?
If the fence instruction just includes barrier, the core needs to do dcache flush for self modifying code.
(there is no dcache flush instruction in RISC-V standard)
However, fence is usually used for multiple harts ordering control. 
Frequent dcache flushes might degrade the performance.

Best Regards,
Xavier

**Comment by aswaterman** [comment]
`fence` is just a memory barrier, but `fence.i` synchronizes the instruction stream (which in some systems might imply a data cache flush).
