### ISSUE TITLE
Add misa to list of state initialized on reset

### ISSUE THREAD

**Issue by jhauser-us** [riscv/riscv-isa-manual#342]
In the privileged ISA document, section 3.3, "Reset", add CSR `misa` to the list of state that must be initialized on reset.  The need to initialize `misa` is made clear in section 3.1.1; however, section 3.3 fails to include `misa` in its list of state that must be initialized, leaving the state of `misa` reportedly "unspecified" after reset.

**Comment by aswaterman** [comment]
Thanks for pointing that out.
