### ISSUE TITLE
Unsigned Int in RV64 and Macro-op Fusion for base ISA

### ISSUE THREAD

**Issue by dennisyyz** [riscv/riscv-isa-manual#345]
Questions from Alibaba.
1.
Normally, RV64 treats 32-bit data as signed data. This means that when 32 bits are involved in the arithmetic, MSBs are always sign extended to 64 bits. However, this is a disaster for programs such as coremark that use unsigned int as an array index. The array index needs to be zero extended to 64 bits by slli and srli, and then the base address is added to execute the load operation.
A well-known trick is to change the definition of unsigned int to signed int, which is not explicitly prohibited in earlier versions of coremark. With this trick, the coremark performance of the high-performance RV64 processor can be improved by more than 14%.
However, last month EEMBC updated the coremark requirements to make sure that unsigned data type must be treated as an unsigned number:
https://github.com/eembc/coremark/commit/7663f78002d0aa55ea6a047c1dc4e11d43fbeb4f
That is, EEMBC believes that 64-bit architecture should provide adequate support for unsigned int types. This is a realistic need in real world.
By adding indexed load and unsigned offset, you can compensate for 14% of coremark performance loss. Thanks to indexed load and store, the total performance improvement can reach more than 20%.
Does RV64's base ISA have a plan to solve this problem?

2.
In addition to the indexed load and store mentioned above, unsigned extensions (slli and srli), multiply-accumulate is a common operation supported by high-performance processors. Integer execution units can execute these instructions quickly (unsigned extensions require only single cycle execution, and multiply-accumulate execution cycles are the same as multiplication) at a lower cost. 
We know that in order to keep the ISA simple, RISCV recommends using Macro-op fusion to support these operations. However, due to the limitations of the instruction function and register index, not all operations can be compressed to two 16-bit instructions. In some cases (such as the indexed load and store mentioned in the above example), more than two 32-bit instructions are required to complete a hardware operation.
For high-performance processors with high decode widths, instruction fetch efficiency is critical to performance. Instructions that need to be fused will reduce the efficiency of instruction fetch, which in turn affects the overall performance of the processor. In order to compensate for the performance loss, the processor needs to design a more complex fusion strategy, which further increases the complexity of the design.
In addition, in order to compile fused instructions, the compiler needs to align the associated fused instructions. Not only does it hinder compiler optimization, it also reduces the performance of low-cost processors that don't use Macro-op fusion.
The current ISA relies on processors and compilers to provide support for Macro-op fusion, which is contrary to the original intention of simplifying processor and compiler design. How does RISCV view this issue?

**Comment by kasanovic** [comment]
Please post independent issues separately in issue tracker. 

2. multiply-accumulate instructions are being considered as part of P extension. 

I'm closing second issue here, and transferring other issues to separate issue number for discussion.
