### ISSUE TITLE
Tiny inconsistency in rv32.tex, line 877

### ISSUE THREAD

**Issue by fpetrot** [riscv/riscv-isa-manual#349]
Hello guys,
I notice that in a single place in all the specs (line 877 of rv32.tex) the concatenation of bitfields is written with a comma and not a vertical bar:
rv32.tex:877:\multicolumn{2}{c}{offset[12,10:5]} & src2 & src1 & BEQ/BNE & \multicolumn{2}{c}{offset[11,4:1]} & BRANCH \\
should probably be:
rv32.tex:877:\multicolumn{2}{c}{offset[12|10:5]} & src2 & src1 & BEQ/BNE & \multicolumn{2}{c}{offset[11|4:1]} & BRANCH \\
to match all the other occurrences of concatenation.

This doesn't fix some enormous stuff, though :)
Frédéric

**Comment by aswaterman** [comment]
Thanks for pointing that out.
