### ISSUE TITLE
MSTATUS.MPV and MSTATUS.MTL bit position not specified for RV32

### ISSUE THREAD

**Issue by avpatel** [riscv/riscv-isa-manual#360]
Currently MSTATUS.MPV and MSTATUS.MTL bit positions are only specified for RV64 but not for RV32.

**Comment by aswaterman** [comment]
As the commentary says, we plan to put these fields in `mstatush` for RV32.  They'll be in the corresponding bit positions (their RV64 `mstatus` positions, minus 32 bits).

Let's leave this ticket open until we formally introduce the `mstatush` CSR layout.

**Comment by avpatel** [comment]
Thanks Andrew.

At the moment, this missing info is blocking us to extend OpenSBI for hypervisor extension. In fact, we are already 100% code ready in Xvisor and OpenSBI.

It would be great if you can add the MSTATUSH CSR sooner.

**Comment by aswaterman** [comment]
Is the issue just that you don't have the mstatush address?  In the current plan, it will be 0x310.

And you know the bit positions.  So, you should be able to proceed, even though the spec isn't updated yet.

**Comment by avpatel** [comment]
Thanks, we will proceed with 0x310 address for MSTATUSH CSR. This will unblock us.

**Comment by avpatel** [comment]
Closing this issue because spec has been updated.
