### ISSUE TITLE
Must mtime be writable?

### ISSUE THREAD

**Issue by asb** [riscv/riscv-isa-manual#362]
The spec seems a little unclear on this. It does say "Writes to mtime and mtimecmp are guaranteed to be reflected in MTIP eventually, but not necessarily immediately", which to me doesn't seem to definitively indicate that `mtime` must be writable.

I note:
* The SiFive E310 manual describes mtime as RO in the CLINT table, but later in the prose description gives it as read-write https://sifive.cdn.prismic.io/sifive%2F4d063bf8-3ae6-4db6-9843-ee9076ebadf7_fe310-g000.pdf
* The SiFive E34 manual consistently describes it as read-write https://sifive.cdn.prismic.io/sifive%2Ff3810ab6-7a0a-4bcf-b4ea-08ee2801f48f_e34_core_complex_manual_v19_02.pdf
* In this thread, Andrew Waterman says "Even so, mtime is writable" https://groups.google.com/a/groups.riscv.org/forum/#!topic/hw-dev/w8p9T83y-Hs

So - is a read-only mtime register compliant or not?

**Comment by aswaterman** [comment]
The table in the E310 manual is incorrect - it is a read-write register in the core in that chip.  cc @dbarbi1

Thanks for pointing out that "mtime is writable" isn't expressly stated in the spec.  I'm just going to update it to make that explicit.
