### ISSUE TITLE
Instruction Scheduling

### ISSUE THREAD

**Issue by Jack10001** [riscv/riscv-isa-manual#363]
Hello！ I want to know how risc-v schedule instruction!  Can you explain it for me?

**Comment by jim-wilson** [comment]
Instruction scheduling is more of a compiler issue than an ISA issue.  How instruction scheduling works depends on the compiler, as different compilers will have different infrastructure for instruction scheduling.  It will also depend on the target, as different targets will have different pipelines that work best with different instruction schedules.

You weren't very specific about what you are looking for.  If you want general info about instruction scheduling info, then you should probably consult a compiler textbook.  There is also a wikipedia page that you could look at
https://en.wikipedia.org/wiki/Instruction_scheduling

If you want info for a specific target, then get documentation for that target that has info on the pipeline, and instruction latencies.

If you want info for a specific compiler, then try looking at that compiler's documentation and/or source code.

**Comment by Jack10001** [comment]
Thanks a lot!

Jim Wilson <notifications@github.com> 于2019年4月10日周三 上午6:21写道：
