### ISSUE TITLE
Meaning of "error"

### ISSUE THREAD

**Issue by pdonahue-ventana** [riscv/riscv-isa-manual#365]
Section 4.3.1 ("Addressing and Memory Protection") says: "Note that failing to mark a global mapping as global merely reduces performance, whereas marking a non-global mapping as global is an error."

It is unclear what is meant by "error" in this context.  In general, the document should be clear when distinguishing software bugs from hardware-detected error conditions.  Since the former is almost certainly what is meant here, can the wording be changed to "...marking a non-global mapping as global is a software bug" or something similar?  

I notice a similar situation in 3.1.6.2: "In practice, such settings would almost always be an error"
I also suggest "software bug" here.

Other uses of the word "error" seem unambiguous where it is either a noun with an appropriate adjective (e.g., "hardware error") or it is an adjective modifying an appropriate noun (e.g., "error responses from slave devices").

Thanks,

-Paul

**Comment by aswaterman** [comment]
In this case, it means “software did the wrong thing.” The vagueness is
because the hardware takes no corrective action.

**Comment by aswaterman** [comment]
Thanks for the suggestions; hopefully the edits address your concerns.

**Comment by pdonahue-ventana** [comment]
Perfect.  Thank you.
