### ISSUE TITLE
Do you consider adding half-precision floating point instructions?

### ISSUE THREAD

**Issue by hyf6661669** [riscv/riscv-isa-manual#367]
That might be useful in low-end cores.

**Comment by aswaterman** [comment]
Yes, we have reserved encoding space for a half-precision floating-point extension.  It will follow exactly the same pattern as the D and Q extensions.  The vector extension will also support half-precision.

**Comment by hyf6661669** [comment]
@aswaterman 
Can you tell me when do you plan to make the half-precision floating point instructions available?

**Comment by aswaterman** [comment]
I don't have a timeline for the spec, but if you want to get started, just mimic the D/Q extension, but for the arithmetic instructions, set the `fmt` field to `10`, for FLH and FSH, set the `funct3` field to `001`.

**Comment by hyf6661669** [comment]
@aswaterman 
OK, thanks!
