### ISSUE TITLE
Behavior of WFI when interrupts are implicitly disabled by privilege level

### ISSUE THREAD

**Issue by sorear** [riscv/riscv-isa-manual#37]
If a hart executes a WFI in M-mode with mstatus.MIE = mstatus.SIE = 1 and a pending S-mode interrupt, is the WFI required to continue immediately (because there is a pending interrupt), or block (because interrupts are enabled but none can be taken)?  After reading the description a couple times I think it's the former but it could be clearer.

**Comment by aswaterman** [comment]
The former.  I believe it is made unambiguous by noting that delegation registers do not affect WFI; see #37

(Note mstatus.MIE/SIE are already specified to have no effect.)

**Comment by aswaterman** [comment]
Resolved by #39
