### ISSUE TITLE
Exception prioritization

### ISSUE THREAD

**Issue by pdonahue-ventana** [riscv/riscv-isa-manual#372]
Table 3.7 of the privileged architecture spec lists the synchronous exception priority for exceptions that are reported in mcause.

Section 4.1.10 says "Table 4.2 lists the possible exception codes for the current supervisor ISAs, in descending order of priority."

The two tables differ significantly.  Does the priority of exceptions differ depending on whether they are reported to M mode via mcause or to S mode via scause?  I suspect that the answer is no and that the statement about table 4.2 is wrong because load/store exceptions and environment calls cannot possibly be higher than instruction page faults which prevent you from fetching the load/store/ecall to start with.

**Comment by aswaterman** [comment]
Thanks for locating this unfortunate editing error.  The sentence in the supervisor chapter is outdated, and the priority is given by Table 3.7.
