### ISSUE TITLE
Proposal to explicitly declare things as unspecified

### ISSUE THREAD

**Issue by pdonahue-ventana** [riscv/riscv-isa-manual#377]
The recent discussion of FENCE.I behavior [1] brings up a larger concern I have.  There are several cases where it is clear what is expected of software but unclear how much latitude implementations have.  Software should avoid FENCE.I unless it's supported but there was confusion about hardware requirements if a FENCE.I is attempted by software. Atomicity of instruction fetches[2] is also not considered in the base architecture.

It is not obvious if a lack of clarity in any particular case is an attempt to unconstrain hardware or if it is an oversight.  It would be beneficial to all involved if the architecture strived to specify behavior in all cases, even if the specification allows complete freedom.  For instance, other architectures have terms such as:
- MIPS has "UNPREDICTABLE" results and operations.  It has "UNDEFINED" operations and behavior. It has "UNSTABLE" results and values.
- Alpha has "UNPREDICTABLE" results and occurrences and "UNDEFINED" operations.
- ARM has "UNPREDICTABLE" and "IMPLEMENTATION DEFINED" behavior.  It has "UNKNOWN" and "Architecturally UNKNOWN" values.
- Power has “boundedly undefined" behaviors and "undefined value" values.

As a straw man, I propose:
- The term "UNSPECIFIED" should be defined in the introduction to apply to a behavior or value that the architecture intentionally leaves open to extensions, platform standards, or implementations.
- Extensions or platform standards may provide normative content to further constrain "UNSPECIFIED" cases or they may not.  That decision is beyond the scope of the architecture.
- All behavior and values must be defined either concretely or using the term "UNSPECIFIED."  This is the key to providing clarity.
- This term is available to and should be used by extensions for behavior that they want to delegate to other extensions or to platform standards or implementations.  This is the key to providing clarity in extension documentation.

For instance:
- To address the FENCE.I issue, the behavior when decoding a reserved instruction is UNSPECIFIED.
- The atomicity of instruction fetches is UNSPECIFIED.
- On reset, "All other hart state is unspecified" becomes "UNSPECIFIED" to explicitly allow extensions, platform standards, or implementations to specify it (which was likely the goal anyway).
- "The number of supervisor physical address bits is implementation-defined" becomes "UNSPECIFIED" to allow requirements to be introduced by extensions or platform standards, not just implementations.
- The debug extension says "Debuggers must not change hartsel while an abstract command is executing."  If the extension intends not to restrict implementations, it would add clarity to say "If hartsel changes while an abstract command is executing, the behavior is UNSPECIFIED."

[1] https://lists.riscv.org/g/tech-privileged/topic/31223476
[2] https://lists.riscv.org/g/tech-memory-model/topic/31215808

**Comment by kasanovic** [comment]
We believe this has been done, but please add additional PRs for other places that should be marked as UNSPECIFIED.
