### ISSUE TITLE
Document 1.10 SBI

### ISSUE THREAD

**Issue by sorear** [riscv/riscv-isa-manual#38]
Since the old page-injection SBI was documented here, the new one is probably in scope as well.  Preferably also document the basic chainloading protocol (`a0`, `a1`, and `sptbr`) supported by Linux (although Linux has very specific rules about the FDT layout that are probably out of scope for an ISA manual), and pin down a numeric value for `ENOSYS` instead of picking up whatever newlib defines.

(Would a PR draft be useful?)

**Comment by palmer-dabbelt** [comment]
We've made a whole repo for the SBI doc: https://github.com/riscv/riscv-sbi-doc .  The idea here is that this is similar to the ABI manual in that they're not really part of the RISC-V ISA specification but instead a supplementary document.
