### ISSUE TITLE
mcause table in mtval section

### ISSUE THREAD

**Issue by eroom1966** [riscv/riscv-isa-manual#412]
@aswaterman 
Hi Andrew, 
I think the documentation has become a bit disjoint by accident in the privilege spec
the section 3.1.17 on MTVAL, contains the table for the MCAUSE register, 
I think this should appear in the section 3.1.16 section on the MCAUSE register itself
Thx
Lee

**Comment by aswaterman** [comment]
Yeah, LaTeX makes strange figure placement decisions sometime.  Fixed.
