### ISSUE TITLE
`fssr` and `frsr` instructions aren't mentioned for F extension

### ISSUE THREAD

**Issue by laanwj** [riscv/riscv-isa-manual#419]
Just a documentation issue I think: The `fssr` and `frsr` instructions (which set and read the `fcsr`, respectively) aren't mentioned in the specification for the F extension. The names don't appear in the spec at all.

**Comment by aswaterman** [comment]
They’re pseudoinstructions that map to CSR-access instructions. (And they
may well be missing from the documentation.)

**Comment by laanwj** [comment]
Oh.

I'm confused now, this came up in https://github.com/rust-embedded/riscv-rt/issues/29, there was the assumption that these were separate instructions, but if they map to the same thing then it's probably not necessary to mention them.

**Comment by Mel-Chen** [comment]
Hi! I also noticed this issue recently. Are `frsr` and `fssr` instructions obsolete, or renamed to `frcsr` and `fscsr` respectively? Thanks.

**Comment by aswaterman** [comment]
Correct.  But the obsolete aliases will be supported in perpetuity, since
important software (like glibc) relies upon them.

**Comment by laanwj** [comment]
Good to know!
RISC-V `objdump` as of version 2.32 still generates those aliases on disassembly.

**Comment by Mel-Chen** [comment]
Don't worried. I am preparing binutils patches to update `objdump`. :P

**Comment by laanwj** [comment]
Thanks!
