### ISSUE TITLE
Consider requiring that scause bits 4:0 all be implemented

### ISSUE THREAD

**Issue by jhauser-us** [riscv/riscv-isa-manual#426]
The privileged spec's requirements for `scause` effectively force any practical implementation to have bits 3:0 be fully implemented as four writable flip-flops.  It has been conjectured that most if not all existing implementations of `scause` actually have five writable flip-flops for bits 4:0.

In order to provide a set of known usable values for `scause` beyond solely the 17 exception codes defined at supervisor level (3 for interrupts, 14 for synchronous exceptions), I propose that the spec be amended to require that `scause` be capable of holding all values in the range 0 through 31, plus all values in the range 2<SUP>(SXLEN - 1)</SUP> through 2<SUP>(SXLEN - 1)</SUP> + 31.

The ability to store in `scause` values other than the 17 exception codes currently defined can be a prerequisite for machine-level software to be able to emulate other exception causes for S mode.  In particular, the ability to store values 20, 21, and 23 in `scause` may soon be a prerequisite for emulating hypervisor support in a machine having only M/S/U modes.

The proposed new requirement would apply only to `scause`, not to `mcause`.

**Comment by aswaterman** [comment]
I'm all for this.

**Comment by jhauser-us** [comment]
Not that it's important, but I miscounted.  There are 16 exception codes currently defined at supervisor level:  3 for interrupts and 13 for synchronous exceptions.

**Comment by avpatel** [comment]
Looks good to me.
