### ISSUE TITLE
`hcounteren` Privilege. Typo or not?

### ISSUE THREAD

**Issue by Columbus240** [riscv/riscv-isa-manual#437]
The CSR `hcounteren` with ID `0x606` has the privilege `SRW` associated with it, not `HRW` as the ID or its meaning would suggest.

https://github.com/riscv/riscv-isa-manual/blob/4bfae7862e436ce67c1aebaf2d95f0d35c658c51/src/priv-csrs.tex#L235-L238

Is this an accident or is there some purpose in it?

**Comment by aswaterman** [comment]
Typo.  Fixed.  Thanks.

**Comment by Columbus240** [comment]
You’re welcome.
