### ISSUE TITLE
Usage of “RV32I” in the CSR listing

### ISSUE THREAD

**Issue by Columbus240** [riscv/riscv-isa-manual#440]
In the CSR listing, the commentary to some CSRs like `timeh` or `htimedeltah` says “RV32I only”. That would exclude the RV32E base ISA, which would mean that RV32E has less CSRs than RV32I, namely it isn’t able to access the upper halves of these registers.

Is this intentional or should the spec say “RV32 only” as it does for `mstatush`?

**Comment by aswaterman** [comment]
You can make a pull request to replace RV32I with RV32 if you’d like.

**Comment by Columbus240** [comment]
Thank you.
