### ISSUE TITLE
Sign-extension for half-precision convert operations

### ISSUE THREAD

**Issue by kasanovic** [riscv/riscv-isa-manual#446]
Copying over @aswaterman note from vector sign-extension issue so doesn't get lost:
"This brings to mind a tangential issue: in the half-precision scalar extension, what should be the extension behavior of the hypothetical FMV.X.H instruction? FMV.X.W always sign-extends its result in RV64; the primary motivation was to maintain the ABI property that all 32-bit types are sign-extended when held in 64-bit x-registers. Sign-extending FMV.X.H seems like the right thing to do for consistency, though there isn't a strong ABI justification one way or the other."

**Comment by aswaterman** [comment]
Addressed in #496
