### ISSUE TITLE
required compressed instruction support for riscv core

### ISSUE THREAD

**Issue by billasurendra** [riscv/riscv-isa-manual#450]
I have installed riscv tool chain with **RV64IMAFD** support. Cross compiled c program with riscv cross compiler and trying to run executable file in RISC-V board, getting compatible error. some suggestions i got like board is designed without compressed instruction support, but i am trying to running compressed instruction support exe file. Can any one give me solution how to give compressed instruction support for RISC-V core design. Please suggest me how to proceed to add compressed instruction support for my RISC-V core.

Thanks In Advance
Billa

**Comment by kasanovic** [comment]
This site is for issues with the RISC-V ISA specification, not help with tools.  Please post to riscv-sw-dev.
