### ISSUE TITLE
Question about A extension

### ISSUE THREAD

**Issue by hyf6661669** [riscv/riscv-isa-manual#451]
For a simple SoC which only has a single core, single hart RISC-V CPU (the CPU is supposed to support MMU and be able to run Linux), is A extension necessary?
What kind of operations cannot be done successfully without A extension? Can you please tell me some examples? 
Or can I just disable/enable the interrupt (clear/set mstatus.MIE) to do "atomic read-modify-write"?

**Comment by aswaterman** [comment]
The A extension is still useful on single-hart systems for atomicity with
respect to interrupts and context switches. RISC-V Linux requires the A
extension in all cases for this reason.
