### ISSUE TITLE
Risc-v vector extension

### ISSUE THREAD

**Issue by allenderalencar** [riscv/riscv-isa-manual#454]
I`m trying to run some examples from various sources and always get:
"core   0: exception trap_instruction_access_fault, epc 0x0000000000000000
core   0:           tval 0x0000000000000000"

*I tried from: https://github.com/riscv/riscv-gnu-toolchain/issues/460
the example:

- .global main
- main:
- vsetvli t0, x0, e32
- vadd.vv v0, v0, v0 # changed from vadd to vadd.vv
- ret

-run: /path/to/in/bin/riscv64-unknown-elf-as -march=rv64gcv -mabi=lp64f wya.s -o wya.o 
       /opt/isaa/bin/spike --isa=RV64IMAFDCV -l -p1 wya.o

*Tried from the risc-v vector documentation

- loop:
-  vsetvli a3, a0, e32,m8 # Use only 32-bit elements
-  vlh.v v8, (a1) # Sign-extend 16b load values to 32b elements
-  sll t1, a3, 1 # Multiply length by two bytes/element
-  add a1, a1, t1 # Bump pointer
-  vmul.vx v8, v8, x10 # 32b multiply result
-  vsrl.vi v8, v8, 3 # Shift elements
-  vsw.v v8, (a2) # Store vector of 32b results
-  sll t1, a3, 2 # Multiply length by four bytes/element
-  add a2, a2, t1 # Bump pointer
-  sub a0, a0, a3 # Decrement count
-  bnez a0, loop # Any more?

-run: /path/to/in/bin/riscv64-unknown-elf-as -march=rv64gcv -mabi=lp64f cv.s -o cv.o                                          
       /opt/isaa/bin/spike --isa=RV64IMAFDCV -l -p1 cv.o 

*And can't compile: https://github.com/ispras/riscv-avs/tree/master/testsuite/synthetics/rv32v
For some errors like:
rv32v_simple_selfcheck_0000.s:109: Error: illegal operands `vlw.v v0,t1'
rv32v_simple_selfcheck_0000.s:111: Error: illegal operands `vlw.v v1,t1'

-run: /path/to/in/bin/riscv64-unknown-elf-gcc -march=rv64gcv -nostdlib -nostartfiles rv32v_simple_selfcheck_0000.ld -o test.o rv32v_simple_selfcheck_0000.s 

If you have some vector example that works and can be compiled or can help with some hint, I would be very grateful, thank you for your attention.

**Comment by aswaterman** [comment]
This issue belongs on a different repo https://github.com/riscv/riscv-isa-sim
— but briefly, the problem is that you are trying to execute object files, rather than linked programs. If you read the README on that other repo, it will tell you how to build a working “hello world” program.
