### ISSUE TITLE
mtvec's BASE field clarification

### ISSUE THREAD

**Issue by MMRep** [riscv/riscv-isa-manual#459]
The "Machine Trap-Vector Base-Address Register" subsection states that:

1. the BASE field needs to be (at least) 4 bytes aligned
2. in direct mode, the pc is set to BASE
3. in vectored mode, the pc is set to BASE+4*cause

However:

2: isn't the pc set to (BASE << 2) in direct mode
3: and to (BASE << 2)+4*cause in vectored mode
1: and thus 4 byte minimum alignment is always guaranteed?

Maybe I'm just pedantic, but I checked it in hardware to be sure which way it is really implemented.

**Comment by kasanovic** [comment]
The spec clearly shows that BASE[XLEN-1:2] is present in the upper XLEN-2 bits of the mtvec register.
