### ISSUE TITLE
MULHSU - signed operand, again

### ISSUE THREAD

**Issue by bnossum** [riscv/riscv-isa-manual#463]
Referring to manual draft-20191205-80e635f.

$7.1 main text specifies that `rs1` is the signed operand for `MULHSU`. 

However, the note  "MULHSU is used in multi-word signed multiplication..." a few sentences lower down states that  the sign bit resides in the multiplier, that is, `rs2`.

See also issue #270

**Comment by aswaterman** [comment]
Good point.  I'll swap "multiplier" and "multiplicand" in that text to clear things up.

**Comment by aswaterman** [comment]
Closed by e66fce81c290d6cdf1dc66890b417898277eebf8
