### ISSUE TITLE
How do we move data from the scalar register to high bits of the floating-point register?

### ISSUE THREAD

**Issue by BiwefC** [riscv/riscv-isa-manual#464]
By using the RV32D instruction set, how do we move the data from the 32-bit scalar register to high 32-bit of the floating-point register?
And how do we move high 32-bit of the floating-point register to the 32-bit scalar register?

**Comment by kito-cheng** [comment]
Compiler will store the whole FPR into stack and then load high part into GPR, it's the only way to do that as I know.

**Comment by Rolfy360** [comment]
discussed before
https://github.com/riscv/riscv-isa-manual/pull/301

**Comment by kasanovic** [comment]
Duplicates issue, so closing this one.
