### ISSUE TITLE
Ambiguity re: AMOMAX[U].W/AMOMIN[U].W on RV64

### ISSUE THREAD

**Issue by scottj97** [riscv/riscv-isa-manual#465]
I filed a [bug on the Sail model](https://github.com/rems-project/sail-riscv/issues/27) because it is comparing 64 bits of the source register to the 32-bit value loaded from memory, whereas Spike is apparently ignoring the upper 32 bits of the source register.

The A extension chapter of the Unprivileged Spec is not entirely clear about what the correct behavior should be here, though it seems to me that the Spike way makes more sense.

**Comment by aswaterman** [comment]
The upper bits of rs2 should be ignored, as with a store or other AMOs.
