### ISSUE TITLE
CSR write timing, PMP, MSTATUS, etc.

### ISSUE THREAD

**Issue by eak** [riscv/riscv-isa-manual#467]
I want to raise something for consideration:

Currently it looks like writes to PMP are expected to take place for the next instruction, but that isn't natural in a pipelined implementation. This means that PMP writes need to flush the pipeline and refetch subsequent instructions. Is this considered acceptable for performance? It would be nice if sw could do multiple PMP writes and then execute some sort of FENCE.

This is potentially an issue for other CSR writes as well (e.g. writes to mstatus.MPRV), so folks might want to invent a general CSR FENCE mechanism.

**Comment by kasanovic** [comment]
The specification was ratified with PMP writes taking effect immediately.  Some microarchitectural optimizations can remove flushes in some cases.

Some other CSR writes must take effect immediately (e.g., satp), or would require excessive additional FENCE instructions if CSR FENCE was required.
