### ISSUE TITLE
mvendorid bank field is misnamed

### ISSUE THREAD

**Issue by scottj97** [riscv/riscv-isa-manual#468]
Figure 3.2 (mvendorid) says bits [31:7] are "Bank", but the description says that Bank should be the number of continuation codes.

According to [JEDEC standard JEP106](https://www.jedec.org/document_search?search_api_views_fulltext=jep106), the first bank is number 1, and uses 0 continuation codes. Bank 2 uses 1 continuation code, etc.

The bank number and count of continuation codes always differ by 1. Therefore it's misleading to label the field as "Bank" when it's really the count of continuation codes.

How about renaming the field to "Bank - 1"?

**Comment by aswaterman** [comment]
IMO, it's not misnamed, it's just differently encoded.  But there's no doubt it's a potential source of confusion.  I'll add a note.
