### ISSUE TITLE
Bit Setting and Clearing

### ISSUE THREAD

**Issue by steven-bellock** [riscv/riscv-isa-manual#471]
There are many sections of text such as

"The R, W, and X bits, when set, indicate that the PMP entry permits read, write, and instruction execution, respectively. When one of these bits is clear, the corresponding access type is denied."

Obviously an unqualified "set" implies a bit value of 1 and an unqualified "clear" implies a bit value of 0, but this is never specified at the beginning of the manuals.

**Comment by kasanovic** [comment]
I think it is "obvious".
