### ISSUE TITLE
approximate usage of pseudo-instruction sw on mtime example

### ISSUE THREAD

**Issue by fpetrot** [riscv/riscv-isa-manual#472]
Hi guys,
I'll probably be the nitpicker of the day, but in the example page 34 of the privileged spec, the example uses lines such as `sw t0, mtimecmp` while the `sw` pseudo-insn needs a scratch register.
So the full example should probably read as:
```
# New comparand is in a1:a0.
li t0, -1
sw t0, mtimecmp, t1   # No smaller than old value.
sw a1, mtimecmp+4, t1 # No smaller than new value.
sw a0, mtimecmp, t1   # New value.
```
Bye,
Frédéric

**Comment by aswaterman** [comment]
True.
