### ISSUE TITLE
Why doesn't PMP differentiate between U and S?

### ISSUE THREAD

**Issue by shufps** [riscv/riscv-isa-manual#476]
I wonder, why the two unused bits (in priv spec 1.12 set to "00") in pmpcfgx are not used for encoding the minimum privilege level for which the PMP-entry will succeed.

Imagine following scenario (in all three cases the same address-block):
- ROM (which is RAM-based on FPGAs) which is RWX in Machine mode (for instance debugger is uploading code)
- ROM which is RX for S-mode
- ROM which code in U has no access to

This would give the following:
- the debugger may upload code into ROM
- the supervisor may execute code from ROM but it's not allowed to write
- the user-code has no access to such protected memory areas

But in the current implementation this isn't possible because there is no differentiation between U and S.

This leads to following problem:
ROM which isn't accessible in user-mode also isn't accessible in supervisor-mode but code running in machine-mode is allowed to do everything unless the region isn't locked.

That means, privileged code *always* have to run in Machine-mode.

This renders the supervisor-mode completely unusable and the additional level of security is completly lost.

Why did the risc-v foundation design a memory protection like this?

The only reason I can see for this is that there is the assumption that ECALLs which cause a trap to machine mode have to reconfigure the PMP before supervisor-code is executed and restore it afterwards (I'm not sure if restoring the pmpcfgx even is possible currently ... how does supervisor-code return to machine code for restoring the PMP?). But there is a lot of software needed which could be a looot easier if just the two unused bits for minimum privilege level would be used.

Kind regards,
Thomas

**Comment by aswaterman** [comment]
The model here is that M-mode would establish an RX PMP for this region, so that M-mode would have RWX perms and S-/U-mode would have RX perms.  Then S-mode would use its own protection features to lock out U-mode.  This can currently be done with paging.  The Foundation is developing an S-mode PMP extension to accomplish the same sort of thing without the overhead of paging.
