### ISSUE TITLE
DOUBT: Why MSTATUS[FS] can be writable if no Floating Point is available?

### ISSUE THREAD

**Issue by lopesmarcel** [riscv/riscv-isa-manual#490]
- On a RV64IMC (with M/S/U-modes), writing MSTATUS[FS]=0x3 is effective (0x3 means DIRTY), but it's not clear to me why it's not OFF (0x0) if no Floating Point is available.
- But Privileged SPEC states (Extension Context Status in mstatus Register Section):
"In systems that do not implement S-mode and do not have a floating-point unit, the FS field is hardwired to zero."
- Why do we need to implement FS bitfield when S-mode is available and no Floating Point is available?

**Comment by aswaterman** [comment]
So that M-mode software can seamlessly emulate the FPU without S-mode
knowing about it.

**Comment by allenjbaum** [comment]
Can this be closed now?
