### ISSUE TITLE
Make a note about Process Context Identifiers

### ISSUE THREAD

**Issue by Rachus** [riscv/riscv-isa-manual#498]
I couldn't find a mention of mechanisms like process context identifiers in the description of the memory management unit of the privileged ISA specification. These identifiers were big in the news to speed up operating system fixes for the spectre CPU vulnerabilities.

Since it does not seem to be specified, I would propose to either add (optional) support to the MMU specified in the document or to make an explanatory note about it.

**Comment by aswaterman** [comment]
ASIDs are described in the Supervisor chapter.

**Comment by Rachus** [comment]
Thanks, that was overlooked by me. Sorry for disrupting.

**Comment by aswaterman** [comment]
No prob!
