### ISSUE TITLE
purpose of NAPOT pmpaddr all 1s defined as 2^(XLEN+3)-byte range

### ISSUE THREAD

**Issue by chuanhua** [riscv/riscv-isa-manual#504]
What is the rationale for defining all 1's of pmpaddr under NAPOT as 2^(XLEN+3)-byte range?

Under sv32 for RV32, the maximum length of physical address is 34 bit, is it useful to have a 2^35-byte NAPOT range defined?

**Comment by aswaterman** [comment]
I agree it's redundant for the current VM schemes.  But we had to define what that bit pattern means, and "unspecified" was an unpopular answer.

**Comment by chuanhua** [comment]
Thanks for the explanation.
