### ISSUE TITLE
Can PMP differentiate between M and U once PMP entry was locked?

### ISSUE THREAD

**Issue by tsaiyenting** [riscv/riscv-isa-manual#505]
Hi,
Similar to #476 , when pmpcfg.L=1, it seems can't differentiate M and U(S) mode.

Imagine the following case(M mode and U mode only):
For an address block, we would like it to be
-RW for M-mode
-no access for U-mode

It seems we can't achieve this goal directly by using PMP.
Yes, similar function can be achieved by setting lower indexed PMP entry for U-mode before changing from M-mode to U-mode.
But it also creates a moment  M-mode have all access privileges(RWX) at the transition from M-mode to U-mode.

Regards.

**Comment by allenjbaum** [comment]
Your interpretation appears to be correct.
There is a proposal being made for an enhanced PMP (with several other
features) that fixes this problem.
Join the Trusted Execution Environment TG to find out more:
https://lists.riscv.org/g/tech-tee/
