### ISSUE TITLE
Is sfence.vma decoding as illegal instruction when no S-mode?

### ISSUE THREAD

**Issue by Min-Yu** [riscv/riscv-isa-manual#517]
Hi,

As the title, I can't find a clear explanation in specifications (User-Level ISA and Privileged Architecture) for sfence.vma when no S-mode (NOP or illegal instruction). 
Could you clarify this in the specification?

thanks,
Min-Yu

**Comment by jscheid-ventana** [comment]
If you walk through the `SFENCE.VMA` requirements in the context of an M-mode-only implementation, the behavior required ought to be clear.  See also "3.7.2 Physical Memory Protection and Paging".
/reassign @Min-Yu

**Comment by Min-Yu** [comment]
Okay, I got it. Thanks.
