### ISSUE TITLE
will risc-v implement hardware assisted virtual machine extension?

### ISSUE THREAD

**Issue by chillancezen** [riscv/riscv-isa-manual#524]
hi, 
does risc-v plan to implement hardware assisted virtual machine extension like what Intel vt-x did?

hardware helps trap some instructions while other instructions continue to execute at native speed? 

thanks,
Link

**Comment by aswaterman** [comment]
Yes.  Build a copy of the privileged architecture spec in this repository & take a look at chapter 5.

**Comment by chillancezen** [comment]
great!
