### ISSUE TITLE
FADD.S/FSUB.S underflow

### ISSUE THREAD

**Issue by tariqkurd-repo** [riscv/riscv-isa-manual#527]
Hi,

The manual says FADD.S and FSUB.S can set NV, OF, UF, NX.
We cannot find any cases where UF (underflow is set). We have complete FPU verification and used a formal proof to show that it cannot happen.
Can you please confirm if UF is possible, and if it is possible tell us how to set it?

Regards

Tariq Kurd

**Comment by Rolfy360** [comment]
https://stackoverflow.com/questions/19053681/causing-underflow-in-ieee-754-floating-point-format-using-subtraction

**Comment by tariqkurd-repo** [comment]
from that link: "When default exception handling is in effect, a subtraction that produces a tiny (in the subnormal interval1) non-zero result conceptually causes an underflow exception, but there is no observable effect"

I agree, we can't observe it, so I think the ISA manual shouldn't state that it is possible to observe it.

**Comment by Rolfy360** [comment]
Hi Tariq Kurd:
May I ask which formal tool do you use to do the FPU verification?

**Comment by aswaterman** [comment]
Yes, this is all true.

**Comment by tariqkurd-repo** [comment]
Hi Rolfy360 we use Jasper from Cadence

**Comment by Rolfy360** [comment]
> Hi Rolfy360 we use Jasper from Cadence

Thank you for the reply, we use the same one. :)
