### ISSUE TITLE
mstatus.MPRV affects all privilege modes?

### ISSUE THREAD

**Issue by scottj97** [riscv/riscv-isa-manual#528]
Section 3.1.6.3 "Memory Privilege in mstatus Register" begins with: "The MPRV (Modify PRiVilege) bit modifies the privilege level at which loads and stores execute **in all privilege modes.**"

But [this change](https://github.com/riscv/riscv-isa-manual/commit/569d07195a8495460f04592d8455153f730a0f54) makes it so that MPRV is cleared when leaving M mode.

Is it even possible now to have MPRV=1 when not in M-mode?

**Comment by aswaterman** [comment]
Agreed.  The text isn't technically wrong because MPRV can't be 0 outside of M-mode, but it certainly is confusing.

**Comment by scottj97** [comment]
(*) can't be 1 outside of M-mode

**Comment by aswaterman** [comment]
Oops.
