### ISSUE TITLE
Basic virtualization leaves no way to inject "external" interrupts?

### ISSUE THREAD

**Issue by sorear** [riscv/riscv-isa-manual#53]
You can inject a trap by fiddling with pc/sepc/secause/stval, but there's no way to make sip.SEIP be true without cooperation from the PLIC, which makes guests that use WFI-loops tricky to support without falling back to classical virtualization whenever there is a pending interrupt?

**Comment by aswaterman** [comment]
For Rocket we have made the bit writable (so the effective interrupt bit is
the logical OR of the PLIC and the new internal state bit). I forgot to
write this up.

**Comment by sorear** [comment]
It looks like this is also special-cased for RMW operations.

**Comment by aswaterman** [comment]
Yeah.
