### ISSUE TITLE
Clarify for mip.MSIP is read-only in mip

### ISSUE THREAD

**Issue by guanhaohz** [riscv/riscv-isa-manual#536]
In description of Machine-Level CSRs/Machine Interrupt Registers (mip and mie):

Bits mip.MSIP and mie.MSIE are the interrupt-pending and interrupt-enable bits for machine level software interrupts. **MSIP is read-only in mip, and is written by accesses to memory-mapped control registers,** which are used by remote harts to provide machine-level interprocessor interrupts.

Does it mean that we cannot write directly to mip.MSIP, so we need to use some other memory-mapped control registers to influence it? (e.g. MSIP Registers in CLINT, according to Sifive docs)

**Comment by allenjbaum** [comment]
It means that a CSRRW op will cause changes to MSIP.
The only way to cause changes is to perform a STx op to an (implementation
defined) address which will cause MSIP to be modified.

Note that not only is there no universal address (each implementation must
define their own), there is also no definition of precisely what writing to
that address - or set of addresses  - will do, e.g.
 - there may be separate addresses to cause MSIP bits to be set or cleared,
or
 - there could be separate addresses for each individual bit in MSIP

These address(es) are global, in the sense that any hart can modify MSIP on
a hart by writing to that address, including the hart that contains that
CSR.
Each hart has  their own unique global address(es) that will enable
modifying the MSIP CSR for that specific hart.

**Comment by guanhaohz** [comment]
@allenjbaum Thank you for your answer
MSIP is read-only in mip
SSIP is writable in mip
