### ISSUE TITLE
Can cached translations be visible when translation is off?

### ISSUE THREAD

**Issue by palmer-dabbelt** [riscv/riscv-isa-manual#538]
The `sfence.vma` text describes translations as being cacheable and the `satp` text describes 0 as translations being off.  From that I'd expect that turning off translation in `satp` prevents cached translations from being visible, as translation is off (as opposed to having an identity translation).  As a result, we don't need a `sfence.vma` after the CSR write that turns off translation in `satp`.

I don't really have any issue with that behavior, but it's a bit subtle and I thought it would go the other way before reading the text.  If that's the desired behavior, we should put another note in the sfence.vma describing the situation.

**Comment by aswaterman** [comment]
Since we write "SFENCE.VMA is used to synchronize updates to in-memory memory-management data structures with current execution", and satp is not an in-memory memory-management data structure, aren't we already on solid footing?

**Comment by palmer-dabbelt** [comment]
I was considering this to fall into the "reusing an ASID" category, which normally requires a fence.

**Comment by alercah** [comment]
It doesn't seem inconsistent with ASIDs to me: changing the ASID in `satp` doesn't require a fence to load the correct table; reusing it to point at a new page table does, because you need to flush any previously stored tables associated with that ASID.

**Comment by aswaterman** [comment]
Decision made in side discussions is to clarify current intended behavior.

**Comment by alercah** [comment]
Would it maybe make sense to also mention that changes to `satp` that update ASID take effect immediately, so that it's clearer that ASIDs can be freely moved in and out of `satp` if the page table is the same, as opposed to reusing an ASID for a new, different page table?

**Comment by aswaterman** [comment]
@alercah Yeah, I suppose we say something close to the inverse (SFENCE is necessary if an ASID is recycled), but we don't explicitly remark that SFENCE is unnecessary when merely switching ASIDs.  I'll update accordingly.
