### ISSUE TITLE
RISC-V Assembly Programmer's Handbook chapter superseded by riscv-asm-manual

### ISSUE THREAD

**Issue by jrtc27** [riscv/riscv-isa-manual#540]
This chapter does not belong here as this should just be the ISA, and these days there is the separate riscv-asm-manual repository. The chapter should be removed, and a suitable reference to riscv-asm-manual added. See #539.

**Comment by aswaterman** [comment]
Agreed. The intro chapter or RV32 chapter can cite the ASM manual so people reading a PDF can still conveniently click through.

**Comment by aswaterman** [comment]
@jrtc27 I'm going to remove the chapter from the spec to hasten things along.  Is there any chance you're willing help improve the riscv-asm-manual, e.g., by migrating the content from the removed chapter?
