### ISSUE TITLE
Wording Clarification on PMP Action

### ISSUE THREAD

**Issue by billhuffman** [riscv/riscv-isa-manual#542]
The description of PMP action says: "Attempting to execute a store, store-conditional (regardless of success), or AMO
instruction whose effective address lies within a PMP region without write permissions raisesstore access-fault exception."

This might give the idea that the store-conditional could succeed in this case.  Of course it can't.  But it might avoid confusion if "regardless of success" were changed to "regardless of potential success"

**Comment by aswaterman** [comment]
Or maybe just delete “regardless of success”?

**Comment by David-Horner** [comment]
That's my preference.
An SC succeeds whenever the lock on the cacheline is retained, even if the
write will fail, so the old wording is ok though misleading and the
proposed wording is not specific enough to make a distinction about lock
success.

**Comment by billhuffman** [comment]
Removing is fine with me too.

**Comment by aswaterman** [comment]
OK, done.  Thanks for bringing this up.
