### ISSUE TITLE
CSRRS/CSRRC definition

### ISSUE THREAD

**Issue by pdonahue-ventana** [riscv/riscv-isa-manual#549]
Zicsr says this of CSRRS:
> Any bit that is high in rs1 will cause the corresponding bit to be set in the CSR, if that CSR bit is writable. Other bits in the CSR are unaffected (though CSRs might have side effects when written).

and this of CSRRC:
> Any bit that is high in rs1 will cause the corresponding bit to be cleared in the CSR, if that CSR bit is writable. Other bits in the CSR are unaffected.

The lack of symmetry with respect to side effects is strange since I assume that CSRRC can also have side effects.

More importantly, I assume that the statement that "other bits in the CSR are unaffected" is not intended.  For instance, consider these situations (which I assume are all indirect effects rather than side effects):
- if only M and U modes are supported then the privileged architecture suggests that it is valid to have only a single flop for mstatus.MPP (in which case setting/clearing one of the MPP bits will affect the other bit)
- if misa.D=misa.F=1 and then CSRRC clears only misa.F then the privileged architecture seems to require that misa.D must be cleared
- other WARL sanitization cases

Perhaps "other bits in the CSR are unaffected except via indirect effects or side effects"?

**Comment by aswaterman** [comment]
The definition is supposed to be symmetric. The parenthetical is merely there for clarification and isn’t necessary for completeness. It probably makes sense to either remove it from CSRRS or add it to CSRRC.

**Comment by pdonahue-ventana** [comment]
That makes sense.  And the prohibition on CSRRS/CSRRC changing bits other than those in the mask?  The requirements of the privileged architecture with respect to WARL are at odds with the requirements of the unprivileged architecture in this section.

**Comment by aswaterman** [comment]
I think the text should say that "other bits are not explicitly written".  It's of course true that they could change because of the bits that are written.

**Comment by pdonahue-ventana** [comment]
Sounds good to me.  Thanks.

**Comment by aswaterman** [comment]
Fixed, thanks for bringing this up.
