### ISSUE TITLE
Some CB format ops use rd'; but format and other CB ops use rs1'

### ISSUE THREAD

**Issue by allenjbaum** [riscv/riscv-isa-manual#570]
Table 16.1 describe the CA format and CI format register specifier fields as rd'/rs1 and rs2, but CB format describes only rs1'. The branch ops description use the rs1' description,  but the shifts and logicals which use CB format (and actually store a result) use only the term rd', although it is used for both a source and a destination - even though table 16.1 lists it as rs1'. It would (arguably) be more consistent to list it as rd'/rs1' even though branch ops don't store a result - but in any case, we should have all ops use that field and table 16.1  to match in their use.

**Comment by aswaterman** [comment]
Agreed, the best solution is to change the field to say "rd'/rs1'".  I also changed the description of the format to say Branch/Arithmetic, to avoid the question, "why do branches need rd?"
