### ISSUE TITLE
Does RISC-V offer a Rotate instruction?

### ISSUE THREAD

**Issue by MarcusJohnson91** [riscv/riscv-isa-manual#580]
I can't find a clear answer online, and I just downloaded the userspace pdf and searched for Rotate, ROR, and ROL and found nothing.

So, does RISC-V offer a Rotate instruction?

**Comment by David-Horner** [comment]
On Sun, Sep 13, 2020, 04:11 Marcus Johnson, <notifications@github.com>
wrote:

> I can't find a clear answer online, and I just downloaded the userspace
> pdf and searched for Rotate, ROR, and ROL and found nothing.
>
> So, does RISC-V offer a Rotate instruction?
>
The base instruction set does  not include rotate.
It can be synthesized in 3 instructions.
However, the bit manipulation extension does.
https://github.com/riscv/riscv-bitmanip
