### ISSUE TITLE
Where is the mtime register?

### ISSUE THREAD

**Issue by xiaoxiaohuixxh** [riscv/riscv-isa-manual#589]
Hi,i cant find the addr for mtime register from riscv-isa-manual.any one can help?thx a lot!

**Comment by stnolting** [comment]
The actual address is up to the system architect.

The _privileged architecture manual_ states:
> Platforms provide a real-time counter, exposed as a memory-mapped machine-mode read-write register

The system time from the MTIME unit's `mtime` register can also be read via the `time[h]` CSRs:

![grafik](https://user-images.githubusercontent.com/22944758/94027746-790f9f00-fdbb-11ea-99cb-e0300965b0ed.png)

**Comment by xiaoxiaohuixxh** [comment]
that is,thanks a lot!!
