### ISSUE TITLE
Incorrect LaTeX in dep-table.tex prevents PDF output

### ISSUE THREAD

**Issue by zaitseff** [riscv/riscv-isa-manual#593]
A superfluous `&` character on line 418 in `src/dep-table.tex` prevents the output PDF from being generated by `pdflatex` using `build/Makefile`.  In particular, the last part of the output of running `make` produces:

    ! Extra alignment tab has been changed to \cr.
    <recently read> \endtemplate 
    
    l.418    FCVT.D.S & {\em rs1} & {\em rd} & NV &  &
                                                        \\
    !  ==> Fatal error occurred, no output PDF file produced!

Attached is a patch generated by `git diff` to fix this.

* [dep-table-fix.txt](https://github.com/riscv/riscv-isa-manual/files/5314363/dep-table-fix.txt)

**Comment by aswaterman** [comment]
Interestingly, it compiles fine with pdflatex on my machine (TeX Live 2012).  Version/distribution differences, I suppose.  Thanks.
