### ISSUE TITLE
riscv.org/specifications/ moved to riscv.org/technical/specifications/

### ISSUE THREAD

**Issue by rdbrown1au** [riscv/riscv-isa-manual#596]
Please update the URL in the main page, riscv-isa-manual/releases/tag/archive and where-ever else

**Comment by aswaterman** [comment]
I've asked for a redirect to be added instead so that the old link remains valid.  If that doesn't happen, I'll update the link here.

**Comment by cetola** [comment]
Redirect in place. Thanks for the head's up.
