### ISSUE TITLE
RV32I version description

### ISSUE THREAD

**Issue by towoe** [riscv/riscv-isa-manual#618]
https://github.com/riscv/riscv-isa-manual/blob/2c07340049ea7f91013b84bb1a8d798fb3e2d8d2/src/rv32.tex#L4

Should this be 'version 2.1'? I guess as the version is already specified in the chapter title this can also just be deleted as in RV64I?

**Comment by kasanovic** [comment]
Thanks for catching this. I'll delete the duplicate version in body text.
