### ISSUE TITLE
What is the state of the sail annotated version? Where is it?

### ISSUE THREAD

**Issue by David-Horner** [riscv/riscv-isa-manual#623]
What is the state of the sail annotated version? Where is it?

**Comment by allenjbaum** [comment]
Sail annotated ISA spec: in
https://github.com/rems-project/riscv-isa-manual/blob/sail/
README.SAIL                             <--how to annotate
annotated unpriv spec --> release/riscv-spec-sail-draft.pdf
release/riscv-spec-sail-draft.pdf   <-- annotated source
 annotated     priv spec--> release/riscv-privileged-sail-draft.pdf

These have NOT been kept up-to-date. Unpriv probably matches ratified spec;
Priv probably matches v1.11, but anchor points are known not to be in the
correct positions in many case.
