### ISSUE TITLE
shoudld va address be page aligned when use sfence.vma rs1,x0 to invalid TLB ?

### ISSUE THREAD

**Issue by leBsky** [riscv/riscv-isa-manual#624]
In RV39, the page size is divided into 1g page, 2m page and 4k page. When software uses sfence.vma rs1, x0 to invalid TLB by va, is it necessory to align the va according to the page size? For example, address 0x80000000 is a 1g page, then I want to invalid this 0x80000000 1g page in TLB by sfence.vma rs1,x0. Is any address in this huge page ok or only page aligned address 0x80000000 is allowed ?

**Comment by pdonahue-ventana** [comment]
The description of sfence.vma says:
> For the common case that the translation data structures have only been modified for a single address mapping (i.e., one page or superpage), rs1 can specify a virtual address within that mapping​ ​to effect a translation fence for that mapping only.​

​So it's "a virtual address within that mapping" where "that mapping" refers to "one page or superpage."  There's no requirement to align to the start of a page.
