### ISSUE TITLE
behavior clarification when pmp configuration with R=0 and W=1

### ISSUE THREAD

**Issue by leBsky** [riscv/riscv-isa-manual#631]
The 1.11 riscv-privileged spec states that PMP combination R=0 and W =1 is reserved for future use, but it's not clear that what the behavior should be in this kind of situation. Should pmp deny any access that matches the entry with R=0 and W=1 ? Please clarify this.

**Comment by jscheid-ventana** [comment]
Still unclear?

**Comment by aswaterman** [comment]
Usual meaning of reserved: software shouldn't do that if it wants defined behavior; hardware's behavior is not specified.
