### ISSUE TITLE
Propose reordering fields of VCFGD value

### ISSUE THREAD

**Issue by jhauser-ucberkeley** [riscv/riscv-isa-manual#66]
For the vector operations extension (current draft 0.2), the source value for a VCFGD instruction has a set of fields in this order:
  X128, F128, X64, F64, F32, F16, X32, X16, X8
(Depending on the base XLEN, fields X128, F128, and X64 may be required to be zeros.)  The order of the fields would follow a more consistent pattern if they were rearranged as
  X128, F128, X64, F64, X32, F32, X16, F16, X8
Note that it might be considered an additional minor advantage of this order that a single LUI instruction suffices to load a register with values for fields F64, X32, and F32 together.

**Comment by kasanovic** [comment]
outdated.
