### ISSUE TITLE
Clarify hard reset

### ISSUE THREAD

**Issue by pdonahue-ventana** [riscv/riscv-isa-manual#662]
The privileged spec says:
> Implementations that distinguish different reset conditions should only use 0 to indicate the most complete reset
(e.g., hard reset).

There are multiple interpretations of this parenthetical phrase.  [One](https://lists.riscv.org/g/tech-tee/message/824) is that "hard reset" is just an example of the most complete reset but the most complete reset could also be cold reset or power-on reset or whatever.  [The other](https://lists.riscv.org/g/tech-tee/message/825) is that the thing called "hard reset" is the most complete reset, though other resets may also map to the most complete reset.

This matters because other RISC-V specs (particularly the ePMP spec) refer to hard reset and treat it specially, assuming that this parenthetical phrase defines it.  Even if the ePMP spec is clarified, it would be good to either remove this parenthetical example altogether or say something like "the most complete reset which shall henceforth be known as hard reset."

**Comment by aswaterman** [comment]
There's only one valid interpretation in standard English--something I know you know but are just being charitable about.  I'm going to short-circuit this discussion by eliminating the stray phrase from the text, which has no normative consequence.
