### ISSUE TITLE
A question about the `fence.i` and the `fence r,r` following it

### ISSUE THREAD

**Issue by zhengxiaolinX** [riscv/riscv-isa-manual#667]
Hi team,

I am a bit confused about the usage of [`fence.i`](https://github.com/riscv/riscv-isa-manual/blob/master/src/memory.tex#L965) here, which says to substitute `isb` on ARM, a `fence r,r` is also needed. BTW I cannot find the previous discussion in the memory model task group. I'm wondering what may happen  without the `fence r,r` following and what is the difference between single `fence.i` and `isb`.

Thanks,
Xiaolin

**Comment by zhengxiaolinX** [comment]
I have seen the description of [isync](https://github.com/riscv/riscv-isa-manual/blob/master/src/memory.tex#L934) I still cannot get it though -- I wonder if it means that in the software programmer's level, a `fence.i` must be followed by a `fence r,r` in usage?
Thanks in advance.

**Comment by aswaterman** [comment]
I'm hoping @daniellustig will chime in here.  My best guess is that `isb` implies additional semantics that often aren't necessary.  There's certainly nothing incorrect about using `fence.i` by itself, even if it isn't quite equivalent to `isb`.

**Comment by daniellustig** [comment]
On ARM, a sequence "load; compare; branch; isb; load" implies enforced memory ordering between the two loads, but on RISC-V the sequence "load; compare; branch; fence.i; load" does not.

As Andrew said, there's nothing wrong with using `fence.i` by itself if the intention is to flush the i-cache etc.  OTOH if you are porting from ARM code but have no information about the intention behind the `isb`, then inserting the `fence r,r` ensures the load-load memory ordering in that sequence is also maintained.

**Comment by zhengxiaolinX** [comment]
Thanks! I appreciate your help - it really helps a lot.

Thanks,
Xiaolin
