### ISSUE TITLE
Reverse order of "push and pop" for return-address stack

### ISSUE THREAD

**Issue by jhauser-ucberkeley** [riscv/riscv-isa-manual#67]
The ISA section on "Control Transfer Instructions" (currently 2.5) discusses hints for a return-address stack.  In the cases where an RAS is both pushed and popped by an instruction, the pop occurs first, followed by the push.  For less risk of misunderstanding, at a minimum I recommend saying "pop and push" or "pop, then push" instead of "push and pop".  Also, change "pushed and popped" to "popped and pushed" in the comment.

**Comment by aswaterman** [comment]
I believe this is resolved by ff93ec3f3567510d11882691ec3dfe8b35874617
