### ISSUE TITLE
Interrupt Delegation from VS to VU

### ISSUE THREAD

**Issue by henry-hsieh** [riscv/riscv-isa-manual#676]
Let say a design supports both H and N extension. How does the hardware distinguish the interrupts for VU and normal U mode? It seems there is no `vsideleg` defined in current spec.

**Comment by aswaterman** [comment]
The N extension is effectively deprecated and we do not have any current plans to support it in conjunction with the hypervisor extension.

**Comment by henry-hsieh** [comment]
Thanks. I'll leave the issue open in case you want to support it in future.

**Comment by gfavor** [comment]
Will revise this in the future if the N extension is revived.
