### ISSUE TITLE
Explicify DIV/REM for inexact division, especially negatives

### ISSUE THREAD

**Issue by jhauser-ucberkeley** [riscv/riscv-isa-manual#68]
The definitions for the DIV and REM instructions don't actually say what the results should be when the division is inexact (remainder is nonzero), other than "integer division" and "remainder of the corresponding division".  For solely positive operands, convention might be sufficient to imply the remainder is positive and thus the division rounds down (or toward zero), but this is less certain for negative operands.  I feel sure you want the same division and remainder operations as the C language, but I don't know that every reader will share those assumptions.

**Comment by aswaterman** [comment]
I've updated the documentation to state that the result is rounded towards zero in 3de73dedf7822bf35f0fa603e400c4f25c99b6d9 -- thanks!
