### ISSUE TITLE
[r**33**]()13

### ISSUE THREAD

**Issue by zaurbey** [riscv/riscv-isa-manual#690]
[r**33**]()

__Originally posted by @zaurbey in https://github.com/bybit-exchange/api-connectors/issues/95#issuecomment-886120018__

**Comment by zaurbey** [comment]
[_zcr2_]()

**Comment by zaurbey** [comment]
> [_zcr2_]()

22

**Comment by nick-knight** [comment]
I have trouble believing this account is under the direct control of a human being. I suggest the admins block it.

**Comment by aswaterman** [comment]
Agreed & done.
