### ISSUE TITLE
Hypervisor exception priority

### ISSUE THREAD

**Issue by pdonahue-ventana** [riscv/riscv-isa-manual#706]
Table 3.7 of the privileged spec lists the synchronous exception priorities. The hypervisor chapter adds guest page faults and virtual instruction exceptions but I don't see where it states how they are prioritized (either in a table or in prose). I have intuition about the priorities but it should be explicit.

@jhauser-us

**Comment by jhauser-us** [comment]
Addressed by #711.

**Comment by aswaterman** [comment]
Resolved by #711.
