### ISSUE TITLE
Specify NaN box checking for all f.p. sources except for transfer operations

### ISSUE THREAD

**Issue by jhauser-ucberkeley** [riscv/riscv-isa-manual#71]
Concerning floating-point NaN boxing, the ISA specification says
> Floating-point compute and sign-injection operations calculate results based on the FLEN-bit values held in the f registers.  A narrow *n*-bit operation, where *n* < FLEN, checks that input operands are correctly NaN-boxed, i.e., all upper FLEN - *n* bits are 1.

In fact, *all* instructions that have floating-point sources need to do this except for the transfer operations defined in the previous paragraph (floating-point loads and stores, FL*, FS*, and floating-point moves to/from the fixed-point registers, FMV.X.* and FMV.*.X).  Not only the compute and sign-injection instructions, but also the conversion instructions, compare instructions, and FCLASS instructions need to consider NaN boxing of smaller-than-FLEN sources, and interpret improperly boxed inputs as NaNs.

The next paragraph makes a separate statement that NaN box checking is done for conversions from floating-point to integer, but still leaves out compare and FCLASS instructions.

It would be better and simpler, after first defining the transfer operations and their blind bit-copying behavior, to specify (once) that all other instructions do NaN box checking for smaller-than-FLEN floating-point inputs read from the f registers.

**Comment by kasanovic** [comment]
Incorporated in e7a897f
