### ISSUE TITLE
Effective address width when S mode and U mode has different XLEN

### ISSUE THREAD

**Issue by dennisyyz** [riscv/riscv-isa-manual#719]
In a system using SV-39, RISC-V privileged spec defines the behavior of address calculation and page fault detection:
`Instruction fetch addresses and load and store effective addresses, which are 64 bits, must have bits 63–39 all equal to bit 38, or else a page-fault exception will occur.`

My question is **in a system where S mode and U mode use different XLENs, what is the bit width of the effective address**?

For example, the XLEN of M mode and S mode is 64, and SV-39 vertual memory system is used. The XLEN of U mode is 32 (specified by UXL). There are two possible definitions for the bit width of the effective address in U mode:

1. **The bit width of the effective address in U mode is still 64**. The 32-bit address calculation result will be **sign-extended** to 64-bit, and then the page fault will be detected according to the definition above. This will cause the virtual address space of U mode to be divided into **two separate 2GB address spaces**:
0x00_0000_0000-0x00_7FFF_FFFF and 0xFF_8000_0000-0xFF_FFFF_FFFF

2. **The bit width of the effective address in U mode is 32**. This means that the effective address calculated by all instructions and load/store is only valid in the LSB 32, and the MSBs should be **zero-extended** to 64 bits. The virtual address space of U mode is still **a continuous 4GB**:
0x00_0000_0000-0x00_FFFF_FFFF

**Please clarify the bit width of the effective address in systems that support different XLENs in different privileged modes.** This will affect the processor's processing of the MSBs of the virtual address and the allocation principle of the operating system's virtual address space.

**Comment by aswaterman** [comment]
As the spec says, user addresses are taken mod 2^UXLEN.  An equivalent way of saying that is that the address is truncated to UXLEN bits then zero-extended before going through the address-translation process.
