### ISSUE TITLE
Simplify specification of NaN box creation

### ISSUE THREAD

**Issue by jhauser-ucberkeley** [riscv/riscv-isa-manual#72]
The ISA document currently says more than once that when a particular kind of instruction writes a smaller-than-FLEN value to an f register it
> creates a valid NaN-boxed value by setting all upper FLEN - *n* bits of the destination f register to 1.

In fact, as currently specified, this is universally true for *all* smaller-than-FLEN writes to an f register.  It would be simpler and clearer to say just once, early on, that writing any value of size *n* bits < FLEN to an f register sets the upper FLEN - *n* bits of the destination register to all 1s.

**Comment by kasanovic** [comment]
Incorporated in 926f81f
