### ISSUE TITLE
About offset(0x7FFFFBF9) in PC Relative 

### ISSUE THREAD

**Issue by luyahan** [riscv/riscv-isa-manual#732]
If offset is 0x7FFFFBF9,it couldn't be process correctly by
```
    int32_t Hi20 = (((int32_t)imm32 + 0x800) >> 12);
    int32_t Lo12 = (int32_t)imm32 << 20 >> 20;
    auipc(rd, Hi20);  // Read PC + Hi20 into scratch.
    jr(rd, Lo12);     // jump PC + Hi20 + Lo12
```
Because 0x7FFFFBF9 + 0x800 is overflow, rd = pc + -2147484679(0xFFFFFFFF7FFFFBF9)
so offset couldn't been generate correctly.

And these case will make a mistake when offset + 0x800 is not int32:
![image](https://user-images.githubusercontent.com/22358871/132613219-6d6be75a-7636-4101-9b8e-042a0de23e46.png)

Call far-away subroutine:
**auipc x1, offset[31 : 12] + offset[11]  jalr x1, offset[11:0](x1)**
Tail call far-away subroutine:
**auipc x6, offset[31 : 12] + offset[11]  jalr x0, offset[11:0](x6)** 

Should we consider this situation?

**Comment by aswaterman** [comment]
You are correct that, in RV64, the range of PC-relative addressing is not
quite 2 GiB. It’s effectively (2 GiB - 2 KiB). The linker enforces this
rule, so there is no chance of incorrect code generation.
