### ISSUE TITLE
Proposal for F, D, Q, ZFINX, ZDINX, ZQINX: add extra FP mathematical calculation instructions

### ISSUE THREAD

**Issue by ethindp** [riscv/riscv-isa-manual#736]
I'm not sure how to submit this or where to go, so apologies if this is the completely (wrong) place to submit this kind of proposal. This could possibly be a new extension to the F/D/Q/ZFINX/ZDINX/ZQINX extensions, since at least F, D, and Q are raddified and not up for amendment, or at least that's what I understand from the ISA manual.

Currently the floating-point instructions are fairly limited in terms of computational capabilities. Considering that most other processors implement some of these, it only makes sense that RISC-V should as well.

As such, this proposal proposes to add some extra computational instructions to the floating-point arithmetic capabilities of RISC-V, particularly the following if not overly complicated: FCOS, FEXPO2, FSIN, FTAN, FLOG, FLOG10, FLOG1P, FLOG2. (I was perhaps hoping to add the majority of the functions in a standard implementation of `libm` as native instructions, but I understand that some of them, such as acos, asin, asinh, ..., are fairly complex and, to my knowledge, no hardware implementation of these exists, and the implementation in hardware may in fact be slower than that in software.)

Ultimately, the goal is to achieve a fast and accurate implementation of the essential trigonometric functions, if such is possible. If this exceeds the boundaries of the standard ISAs, and is more intended for particular things like math coprocessors, that is fine too. Perhaps this could be called something like ZTRIG or ZFPMATH (with perhaps future additions for more trigonometric functions)?

**Comment by jnk0le** [comment]
LKCL was pushing those some time ago. here is what's left from it: https://libre-soc.org/ztrans_proposal/
There was also some discussion on isa-dev list.
