### ISSUE TITLE
C.LUI immediate field should be nzimm, not nzuimm?

### ISSUE THREAD

**Issue by jhauser-ucberkeley** [riscv/riscv-isa-manual#74]
Instruction C.LUI has a 6-bit immediate constant specified as "nzuimm[17:12]", but this constant is then said to be sign-extended.  Should this be written "nzimm" instead of "nzuimm"?  (If not, what does the 'u' stand for?)

**Comment by aswaterman** [comment]
Indeed, fixed in 3e6b37033d0ec9a2e0cc132b885655afa100589e, thanks.
