### ISSUE TITLE
A/D PTE Update Rules

### ISSUE THREAD

**Issue by damageboy** [riscv/riscv-isa-manual#742]
Hi,
Reading the `A`, `D` (access, dirty) bit update scheme in the manual, it specifies (slightly reformatted below):

> When a virtual page is accessed and the A bit is clear, or is written and the D bit is clear, the
implementation sets the corresponding bit(s) in the PTE.
> 
> - The PTE update must be atomic with respect to other accesses to the PTE
> - must atomically check that the PTE is valid and grants sufficient permissions.
> - The PTE update must be exact (i.e., not speculative), and
> - Observed in program order by the local hart. 
> 
> Furthermore, the PTE update must appear in the global memory order no later than the explicit memory > access, or any subsequent explicit memory access to that virtual page by the local hart. The ordering on > loads and stores provided by FENCE instructions and the acquire/release bits on atomic instructions
>  also orders the PTE updates associated with those loads and stores as observed by remote harts.

While the spec clearly states the PTE must be marked as "valid and grants sufficient permissions.", it does not go into the question of the `PPN` value at the time of the update.

In other words, the entire process of updating the `D` / `A` bits is described using virtual-address only terminology and does not prevent a `D` bit update, for example, from being generated while a virtual address is pointing to PPN<sub>1</sub> while the PTE itself is translating the same address to PPN<sub>2</sub>.

Is this a desired intention of the address translation mechanism?

**Comment by aswaterman** [comment]
It is.  Software that cannot tolerate this possibility should use a "break before make" strategy: clear the PTE's valid bit and perform a TLB shootdown before changing the PPN.
