### ISSUE TITLE
Clarity for condition when virtual instruction trap will occur

### ISSUE THREAD

**Issue by saadkhalid-10xe** [riscv/riscv-isa-manual#743]
In privileged spec (Hypervisor Extension, Version 1.0.0-rc), it is mentioned:

> When V=1, a virtual instruction exception (code 22) is normally raised instead of an illegal instruc-
tion exception if the attempted instruction is HS-qualified but is prevented from executing when
V=1 due to insufficient privilege or because the instruction is expressly disabled by a supervisor
or hypervisor CSR such as scounteren or hcounteren

The condition for scenarios where virtual exception will take place of illegal instruction exception is a bit ambiguous. Its mentioned that attempted instruction should be HS-qualified and,
1) "insufficient privilege" 
or
2) "because the instruction is expressly disabled"

The other way of reading it is,
1) HS-qualified and "insufficient privilege" 
or
2) "because the instruction is expressly disabled"

Do you think it should have more clarity?

**Comment by allenjbaum** [comment]
Are yo asking if is this whether the definition is interpreted as A & (B or
C) or as (A&B) or C ? (A=HS qualified, B= insufficiaent priv, C=expressly
disabled)

**Comment by saadkhalid-10xe** [comment]
> Are yo asking if is this whether the definition is interpreted as A & (B or C) or as (A&B) or C ? (A=HS qualified, B= insufficiaent priv, C=expressly disabled)

yes.

**Comment by jhauser-us** [comment]
Addressed by #773.
