### ISSUE TITLE
a question about the "fence" instruction

### ISSUE THREAD

**Issue by jiamenghan** [riscv/riscv-isa-manual#799]
Hi, all.
  I have a questio about the execution of fence instruction.

Given a instruction stream `sw data, (memory); fence iorw, iorw; sw flag (memory)`
Does the “fence” instruction itself ensure the pre-ordered `sw data, (memory)` have beed stored to the coherent point (such as dcache) ? or the completion of subsequent `sw flag,(memory)` ensure that the the data have beed stored to the coherent point? or only storing the flag to the coherent point ensuring that the data have beed stored to the coherent point?

It is meanful because it decides whether the CPU can still postpone the execution of previous st instructions when `fence` completes until the subsequent ld/st instructions being fenced appear.

**Comment by aswaterman** [comment]
Ordering only, not completion.

**Comment by jiamenghan** [comment]
Thx for the answer
