### ISSUE TITLE
PMP and MPRV description misleading

### ISSUE THREAD

**Issue by scottj97** [riscv/riscv-isa-manual#807]
The PMP description in 3.7 says:

> PMP checks are applied to all accesses whose effective privilege mode is S or U, including instruction fetches in S and U mode, data accesses in S and U mode when the MPRV bit in the mstatus register is clear, and data accesses in any mode when the MPRV bit in mstatus is set and the MPP field in mstatus contains S or U.

Since [this change](https://github.com/riscv/riscv-isa-manual/commit/569d07195a8495460f04592d8455153f730a0f54) MPRV cannot be 1 outside of M-mode, so this is misleading when it qualifies accesses in S and U mode with MPRV being clear.

Suggestion:

> PMP checks are applied to all accesses whose effective privilege mode is S or U, including instruction fetches and data accesses in S and U mode, data accesses in M mode when the MPRV bit in mstatus is set and the MPP field in mstatus contains S or U, and HLV/HLVX/HSV instructions from any mode.

(See #528 for a similar change.)

**Comment by aswaterman** [comment]
The HLV/HSV instructions haven't been introduced by this point, so I'm going to leave them out.
