### ISSUE TITLE
Is `Zhinxmin` not yet ratified?

### ISSUE THREAD

**Issue by omasanori** [riscv/riscv-isa-manual#808]
The commit b35a54079e0da11740ce5b1e6db999d1d5172768 updates the status of some extensions including `Zfinx`, `Zdinx`, and `Zhinx` but leave `Zhinxmin`. Is it intentional?

**Comment by aswaterman** [comment]
That’s a bug. I’ll fix it.

**Comment by omasanori** [comment]
Thanks!
