### ISSUE TITLE
Can an M-mode interrupt be taken when core is in M-mode and interrupt is delegated?

### ISSUE THREAD

**Issue by jrahmeh** [riscv/riscv-isa-manual#849]
Section 3.1.8 of the privileged spec (may 13, 2022) states:

> Traps never transition from a more-privileged mode to a less-privileged mode. For example, if M- mode has delegated illegal instruction exceptions to S-mode, and M-mode software later executes an illegal instruction, the trap is taken in M-mode, rather than being delegated to S-mode. By contrast, traps may be taken horizontally. Using the same example, if M-mode has delegated illegal instruction exceptions to S-mode, and S-mode software later executes an illegal instruction, the trap is taken in S-mode.

And section 3.1.9 states:

> An interrupt i will trap to M-mode (causing the privilege mode to change to M-mode) if all of the following are true: (a) either the current privilege mode is M and the MIE bit in the mstatus register is set, or the current privilege mode has less privilege than M-mode; (b) bit i is set in both mip and mie; and (c) if register mideleg exists, bit i is not set in mideleg.

If a core is running at M-mode, and machine timer interrupt is enabled and pending and delegated to S-mode, and MSTATUS.MIE is 1, will the timer interrupt be taken?  Section 3.1.9 says no (because of c).  Section 3.1.8 implies that it will be taken and the core will stay in M-mode.

**Comment by aswaterman** [comment]
3.1.8 says traps “may” be taken horizontally, not “will” be. Perhaps it should say “some traps”. In any case, 3.1.9 gives the answer you’re looking for.
