### ISSUE TITLE
remove unused sourceless embedded code copy of bbding CTAN module

### ISSUE THREAD

**Issue by pabs3** [riscv/riscv-isa-manual#85]
`src/bbding.sty` is a sourceless embedded code copy of the bbding CTAN module and as far as I can tell it is not used by the build process at all. Please remove it and the mention of it in `src/preamble.tex`.

https://www.ctan.org/pkg/bbding
https://wiki.debian.org/EmbeddedCodeCopies

**Comment by aswaterman** [comment]
It does appear that we no longer rely on the bbding package.  We had included the style file in the repo because one of the popular TeX distributions (I forget which) did not provide it.

**Comment by pabs3** [comment]
Looks like this can be closed as you removed the file in git.
