### ISSUE TITLE
what is the instruction to Raise invalid opcode exception?

### ISSUE THREAD

**Issue by yuyang-ok** [riscv/riscv-isa-manual#850]
https://mudongliang.github.io/x86/html/file_module_x86_id_318.html
just like x86 platfrom.

**Comment by kasanovic** [comment]
The instruction with all zeros is guaranteed to be an illegal instruction, from intro chapter "Encodings with bits [15:0] all zeros are defined as illegal instructions."

**Comment by yuyang-ok** [comment]
ok, thanks.
