### ISSUE TITLE
the term non-standard is being used as "non-standard" and nonstandard. I suggest you pick one

### ISSUE THREAD

**Issue by mark-riscv** [riscv/riscv-isa-manual#851]
example:
"RISC-V has been designed to support extensive customization and specialization. Each base integer
ISA can be extended with one or more optional instruction-set extensions, and we divide each RISCV instruction-set encoding space (and related encoding spaces such as the CSRs) into three disjoint
categories: standard, reserved, and custom. Standard encodings are defined by the Foundation,
and shall not conflict with other standard extensions for the same base ISA. Reserved encodings
are currently not defined but are saved for future standard extensions. We use the term nonstandard to describe an extension that is not defined by the Foundation. Custom encodings shall
never be used for standard extensions and are made available for vendor-specific non-standard
extensions. We use the term non-conforming to describe a non-standard extension that uses either
a standard or a reserved encoding (i.e., custom extensions are not non-conforming). Instruction-set
extensions are generally shared but may provide slightly different functionality depending on the
base ISA."

the term non-standard is used both and without a hyphen in this paragraph.

**Comment by kasanovic** [comment]
non-standard is the preferred form.

there are only a few nonstandard in current spec.
