### ISSUE TITLE
[PMP] Will pmp(i-1)cfg be locked when locking TOR pmp(i)cfg?

### ISSUE THREAD

**Issue by YenHaoChen** [riscv/riscv-isa-manual#866]
Hello,

From privileged spec 20211203, page 60:
If PMP entry i is locked, writes to pmpicfg and pmpaddri are ignored. Additionally, if PMP entry i is locked and pmpicfg.A is set to TOR, writes to pmpaddri-1 are ignored.

Question:
Changing the pmpcfg results in a different pmpaddr value. If PMP entry i is locked and pmpicfg.A is set to TOR, will writes to pmpcfgi-1 be ignored?

Best regards,
Howard

**Comment by gfavor** [comment]
The spec does not state any constraint on writing to pmpicfg-1, so writes to pmpicfg-1 will still be allowed. 

Note that whether with or without locking of PMP entry i, pmpaddri-1 is being shared between entry i (with its A=TOR) and entry i-1.  Hence programming of the two pmpcfg's must take that into account.  The simplest is for PMP entry i-1 to have A=OFF, but any A configuration of PMP entry i-1 is allowed (including A=TOR for PMP entry i-1).  The point is that locking of PMP entry i doesn't change this sharing situation (other than locking down the shared address)

**Comment by YenHaoChen** [comment]
Thank you
