### ISSUE TITLE
Typo in table 28.1 about definition of the G extension

### ISSUE THREAD

**Issue by allenjbaum** [riscv/riscv-isa-manual#872]
The spec in both chapters 26 and 28.3 says                    “G” = “IMAFDZicsr_Zifencei”.  
It looks like the entry in table 28.1 is incorrect and says. “G” = “IMADZicsr_Zifencei”.  (F ismissing)

**Comment by aswaterman** [comment]
Not a typo. D implies F.

**Comment by gfavor** [comment]
It would be desirable for all three definitions of 'G' to be identical (i.e. either include F or don't) to avoid confusion.  Also note that the definition in table 28.1 is also different from the other two definitions in not including the Zicsr extension - former presumably being incorrect.

**Comment by aswaterman** [comment]
Resolved via #874.
