### ISSUE TITLE
confusing text about U*IP bits in mip

### ISSUE THREAD

**Issue by mwachs5** [riscv/riscv-isa-manual#88]
The spec says "if a privilege level is not supported, the associated pending and interrupt enable bits are hardwired to zero in mip and mie registers".

That makes it sound like if a core supports U-mode, then they are *not* wired to zero. But I think the intention was that if the core doesn't support N-extension, then they are wired to zero. Suggest changing the above phrase to something like "if interrupts in a privilege level are not supported..."

**Comment by kasanovic** [comment]
Clarified:
"For all the various interrupt types (software, timer, and external),
if a privilege level is not supported, or if U-mode is supported but
the N extension is not supported, than the associated pending and
interrupt-enable bits are hardwired to zero in the {\tt mip} and {\tt
  mie} registers respectively.  Hence, these are all effectively
\warl\ fields."
