### ISSUE TITLE
Unclear abbreviation `GC extension`

### ISSUE THREAD

**Issue by goekce** [riscv/riscv-isa-manual#885]
I am reading the manual for the first time and could not understand what `GC` stands for:

https://github.com/riscv/riscv-isa-manual/blob/10eea63205f371ed649355f4cf7a80716335958f/src/intro.tex#L352-L352

C extension makes sense, but G extension does not exist. Is this a bug or feature?

**Comment by ethindp** [comment]
`GC` means "General with Compressed", I think. The RISCVxG extension contains the I, A, M, F, and D instruction sets. The `C` part of that acronym means that the `C` instruction set extension is added for compressed instructions.

**Comment by goekce** [comment]
Makes sense, thanks!

If you are right, then `G` should be defined in the intro to avoid confusion. What do the authors think?

**Comment by aswaterman** [comment]
Agreed, the forward reference to G probably resulted from years of editing.  Fixed.
