### ISSUE TITLE
Unclear dependency relationship between H, S, and U

### ISSUE THREAD

**Issue by alexrp** [riscv/riscv-isa-manual#899]
From a cursory glance through the privileged spec, I gathered that M is required while H, S, and U are optional. What's not clear to me is whether any of the latter 3 modes depend on one another. Intuitively, I would imagine that H depends on S which depends on U, but it isn't explicitly spelled out, so then again, maybe not?

Whatever the case may be, it seems like it might be worth spelling this out explicitly somewhere.

**Comment by allenjbaum** [comment]
The legal combinations (which I thought we spelled out are:
M
MU
MUS
MUSH

No other combinations are legal as far as I know.

**Comment by alexrp** [comment]
There is indeed a table in §1.2 "Privilege Levels" looking similar to that, but there is no mention of how H fits in there. That plus the overall wording in that section led me to believe that the table was only meant as a guideline.

FWIW, I think adding H into the table and renaming the "Supported Modes" column to "Required Modes" (or something to that effect) would make things clearer.

**Comment by pdonahue-ventana** [comment]
> From a cursory glance through the privileged spec

You might want to look at table 1.2 and the text immediately below it, plus the beginning of the hypervisor extension as Scott mentioned.

**Comment by alexrp** [comment]
Closing since the information seems to be there and I just missed it.
