### ISSUE TITLE
Non-zero D/A/U bits in a non-leaf PTE

### ISSUE THREAD

**Issue by jrahmeh** [riscv/riscv-isa-manual#900]
Section 4.3.1, has the following:

> For non-leaf PTEs, the D, A, and U bits are reserved for future standard use. Until their use is defined by a standard extension, they must be cleared by software for forward compatibility.

What should an implementation do if the D, A, and U bits are found to be non-zero in a non-leaf PTE? Raise an exception? If so, what kind of exception?

**Comment by pdonahue-ventana** [comment]
"If pte.v = 0, or if pte.r = 0 and pte.w = 1, **or if any bits or encodings that are reserved for
future standard use** are set within pte, stop and raise a page-fault exception corresponding
to the original access type."

**Comment by jrahmeh** [comment]
Thanks
