### ISSUE TITLE
Machine Timer

### ISSUE THREAD

**Issue by lopataz** [riscv/riscv-isa-manual#901]
in 3.2.1 Machine Timer Registers (mtime and mtimecmp)

> A machine timer interrupt becomes pending whenever mtime contains a value greater than or equal to mtimecmp, treating the
> values as unsigned integers. The interrupt remains posted until mtimecmp becomes greater than
> mtime (typically as a result of writing mtimecmp).

Does it mean
- a single Interrupt is posted anytime  mtime>= mtimecmp
- Interrupts are posted "pressed on" IF mtime>= mtimecmp

Thoughts:
1st case acts as a trigger and is normal behavior of a timer
2nd case is dummy comparison, there's no way to disable interrupt when it's on

**Comment by scottj97** [comment]
Interrupts are disabled as soon as the timer interrupt is taken (because that sets `mstatus.mie=0`). The handler will write to `mtimecmp` to reset the timer (and clear the interrupt) before returning.
