### ISSUE TITLE
Unclear which PPN to use in virtual address resolution

### ISSUE THREAD

**Issue by jethrogb** [riscv/riscv-isa-manual#92]
In the [Virtual Address Translation Process, step 4](https://github.com/riscv/riscv-isa-manual/blob/8df1abd/src/supervisor.tex#L1209), it's not clear which PPN to use for the next level.

**Comment by jethrogb** [comment]
I think it should read `a=pte.ppn[LEVELS - 1 : 0]`

**Comment by aswaterman** [comment]
They are equivalent in this context: pte.ppn means "the entire array", and pte.ppn[LEVELS-1:0] equivalently means "first LEVELS entries in the array"
