### ISSUE TITLE
Behavior of “SRET in S-mode will set MPRV=0 or not” is contradictory

### ISSUE THREAD

**Issue by BiwefC** [riscv/riscv-isa-manual#921]
In Privilege 1.12 preface, the spec says:

> Changed MRET and SRET to clear mstatus.MPRV when leaving M-mode.

However in Section 3.1.6.1 says:

> An MRET or SRET instruction is used to return from a trap in M-mode or S-mode respectively. When executing an xRET instruction, supposing xPP holds the value y, x IE is set to xPIE; the privilege mode is changed to y; xPIE is set to 1; and xPP is set to the least-privileged supported mode (U if U-mode is implemented, else M). If xPP̸=M, xRET also sets MPRV=0.

Following the first discription, executing SRET in S-mode not **leave** M-mode, so it will not clear mstatus.MPRV. However in this scenario, SPP must not be M, so it will set MPRV to 0 when following the second discription.

So what is the correct behaivor of MPRV when executing SRET in S-mode?

**Comment by scottj97** [comment]
If you're in S-mode, MPRV will always be 0, because the only way to set MPRV=1 is from M-mode, and the only way to leave M-mode is via SRET or MRET which will then set it back to 0.

So, it doesn't matter if SRET in S-mode clears MPRV or not. It will always be 0 already.

**Comment by BiwefC** [comment]
Thanks~
