### ISSUE TITLE
How does delegation increase performance?

### ISSUE THREAD

**Issue by YenHaoChen** [riscv/riscv-isa-manual#940]
Hello,

The spec says the purpose of delegation is to increase performance. How does the delegation improve performance? The delegation makes a trap being handled at a lower privilege level. However, the spec does not mention why handling a trap in a lower privilege level can benefit the performance. Does a lower privilege level usually have a more efficient trap handler?

Additionally, do we have other reasons (benefits) for supporting delegation?

Best regards,
YenHaoChen

![image](https://user-images.githubusercontent.com/39526191/208351755-59ad8ce7-9abb-46f2-9b11-67039f47f7b0.png)

**Comment by aswaterman** [comment]
To pick a specific example, page faults generally need to be handled by supervisor OSes. If all of those exceptions first go to M-mode, then extra instructions need be executed before S-mode can process the exception.

**Comment by YenHaoChen** [comment]
Thank you
