### ISSUE TITLE
Software breakpoint exceptions are permitted to write either 0 or the pc to xtval

### ISSUE THREAD

**Issue by tariqkurd-repo** [riscv/riscv-isa-manual#982]
This is listed as a change since Supervisor ISA 1.11 at the start of the document:

`Software breakpoint exceptions are permitted to write either 0 or the pc to xtval.`

but I don't see any mention of it in the text for MTVAL - has it been ommitted?

Also - I presume that `software breakpoint` means `ebreak` but it would be helpful to define the term as it is not defined in the document.

**Comment by ZenithalHourlyRate** [comment]
https://github.com/riscv/riscv-isa-manual/commit/51522f98b5cae989c7d161e00b20a08483a2301e

It is not omitted, but the sentence in the spec is indeed subtle. A breakpoint can be either hardware breakpoint or software breakpoint.

**Comment by tariqkurd-repo** [comment]
That is so subtle I had read the paragraph in question at least twice before and not noticed it.
It would be much clearer to have a table of exception type which _must_ write non-zero to mtval (if mtval is implemented as non-zero) and which _may_ write non-zero listing the choices. Including the text `hardware breakpoint` and `software breakpoint` in the table would have resolved this immediately without filing this issue, as that's the phrase used in the changes since v1.11

**Comment by allenjbaum** [comment]
I suspect that in this particular case, EPC holds the relevant address, so
there is no loss of functionality.

**Comment by tariqkurd-repo** [comment]
yes it does, so there is no loss of functionality.
